### ISSUE TITLE
2.11 and 2.12 have no deploy at bintray

### ISSUE THREAD

**Issue by shijinkui** [sbt/sbt-native-packager#1002]
http://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/

```
scala_2.10/
scala_2.9.2/
```

**Comment by shijinkui** [comment]
`can't expand macros compiled by previous versions of Scala`

**Comment by muuki88** [comment]
This is because sbt is using scala `2.10`. I'm currently working on a cross build for sbt `1.0.0-M6` in #1000. Then there'll be `2.10` and `2.12`.

**Comment by charegre** [comment]
Binaries for `Scala 2.11` are not there yet

**Comment by nigredo-tori** [comment]
@charegre, AFAIK, no SBT version uses Scala 2.11.
