### ISSUE TITLE
how to insert a custom command into start script

### ISSUE THREAD

**Issue by bulecode** [sbt/sbt-native-packager#1007]
i want to add a mkdir command into start script. 
i use command 'dist' to package.
 only insert into linux script is ok.
Please excuse my poor English

**Comment by muuki88** [comment]
Hi @bulecode 

> Please excuse my poor English

No worries :) 

> i want to add a mkdir command into start script.

The [customize section](http://sbt-native-packager.readthedocs.io/en/stable/archetypes/java_app/customize.html#start-script-customizations) in the docs should give you the hints you need.

If you simply want to add a folder I recommend reading the [customize mappings section](http://sbt-native-packager.readthedocs.io/en/stable/formats/universal.html#universal-conventions) for the universal plugin, which helps you adding content to your package.

**Comment by bulecode** [comment]
@muuki88 
first,thank you very much.
i want to add a empty folder in my package.
when i see you suggestion , i thank use script is fool ,
but when i want to solve it in build.sbt is always failed,
my build.sbt file main content:
`enablePlugins(JavaServerAppPackaging)

mappings in Universal ++= {
  // optional example illustrating how to copy additional directory
  directory("scripts") ++
    // copy configuration files to config directory
    contentOf("src/main/resources").filter(x => !x._2.endsWith("Mapper.xml"))
      .filter(x => !x._2.equals("mybatis-config.xml")).toMap.mapValues("config/" + _)
}



scriptClasspath := Seq("../config/") ++ Seq("*")

javaOptions in Universal ++= Seq(
  // -J params will be added as jvm parameters X开头的jvm参数需要 -J
//  "-J-Xmx64m",
//  "-J-Xms64m",
  "-J-XX:+UseG1GC",
  "-J-Xloggc:../edr3logs/gc.log"
//  "-Dcom.sun.management.jmxremote.port=1090",
//  "-Dcom.sun.management.jmxremote.ssl=false",
//  "-Dcom.sun.management.jmxremote.authenticate=false"
)
//生成jvm配置文件
bashScriptConfigLocation := Some("${app_home}/../config/jvm.ini")`

so,please you help me complete this code. empty folder name is  edr3logs

**Comment by muuki88** [comment]
Try adding these files under `src/universal/scripts` and you have to do nothing in your `build.sbt` :)
