### ISSUE TITLE
Pass proxy configuration to the application in startup script

### ISSUE THREAD

**Issue by tartakynov** [sbt/sbt-native-packager#1015]
In *nix world, there is a widely accepted set of environment variables for proxy configuration:`http_proxy`, `https_proxy`, `ftp_proxy`, `no_proxy`. SBT [already](http://www.scala-sbt.org/0.13/docs/Setup-Notes.html) picks up those variables.

But in Java a quite different set of system properties is accepted as described in the following document http://docs.oracle.com/javase/7/docs/technotes/guides/net/proxies.html Many HTTP libraries support Java-style system properties out of the box, whereas *nix standard `http_proxy` stays neglected. 

It would be very handy to have a setting `bashScriptUseSystemProxy` (it may be a different name) which would enable translation of `http_proxy` and `no_proxy` environment variables into following Java arguments upon startup: `http.proxyHost`, `http.proxyPort`, `http.nonProxyHosts` 

## Information

- What sbt-native-packager are you using
1.2.0
- What sbt version
0.13.13
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
MacOS
- What package are you building (e.g. docker, rpm, ...)
RPM, Universal zip
- What version has your build tool (find out with e.g. `rpm --version`)
rpm (RPM) 5.4.15
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)
CentOS 7

**Comment by muuki88** [comment]
Thanks for your feature request.

I'm not sure if native-packager is the right place to put this into.
Setting java options for a specific runtime behavior is not related to creating
packages.

Putting this in the [Recipe section](http://sbt-native-packager.readthedocs.io/en/stable/recipes/index.html) in the documentation would be okay, but the feature itself is out-of-scope for native-packager, I'm afraid.
