### ISSUE TITLE
Duplicated startup script names in universal zip

### ISSUE THREAD

**Issue by atrosinenko** [sbt/sbt-native-packager#1016]
When the project contains several main classes with the same name in different packages, universal zip contains multiple startup scripts with the same name inside the `bin/` directory.

## How to reproduce

1. Unzip the attached example: [native-packager-bug.zip](https://github.com/sbt/sbt-native-packager/files/1245294/native-packager-bug.zip)
2. Run `sbt 'universal:packageBin'`

## Expected behaviour

Create differently named startup scripts (for example, prepend their name with package name when clashes occur).

## Actual behaviour

The created file contains duplicated file names:
```
$ unzip -l target/universal/test-1.0.zip 
Archive:  target/universal/test-1.0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     5403  2017-08-23 15:00   test-1.0/lib/test.test-1.0.jar
  5246851  2017-07-25 13:47   test-1.0/lib/org.scala-lang.scala-library-2.12.3.jar
     9159  2017-08-23 15:00   test-1.0/bin/test
     9159  2017-08-23 15:00   test-1.0/bin/test
     4064  2017-08-23 15:00   test-1.0/bin/test.bat
     4064  2017-08-23 15:00   test-1.0/bin/test.bat
---------                     -------
  5278700                     6 files
$ unzip target/universal/test-1.0.zip 
Archive:  target/universal/test-1.0.zip
  inflating: test-1.0/lib/test.test-1.0.jar  
  inflating: test-1.0/lib/org.scala-lang.scala-library-2.12.3.jar  
  inflating: test-1.0/bin/test       
replace test-1.0/bin/test? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
```

## Information

Version information:
sbt: 1.0.0
sbt-native-packager: 1.2.2
build system: Ubuntu 16.04.3 LTS

**Comment by muuki88** [comment]
Thanks a lot for your detailed bug report.

Do you have the time to open a pull request for this? [This is the code line|https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala#L132-L150] responsible for this behavior. I'll guide and help you if you feel unsure if you are up to the task ( which I'm sure you are :sunglasses: )

**Comment by atrosinenko** [comment]
I hope I can look at it on the weekend. Meanwhile, why upper case names mangled like `UIExample -> u-i-example`? What if generate names with the original capitalization and resort to this scheme only when name clashes occur (on case-insensitive filesystems) -- wouldn't it look more readable?
