### ISSUE TITLE
SystemV service template does not actually generate any logs

### ISSUE THREAD

**Issue by timcharper** [sbt/sbt-native-packager#1021]
## Expected behaviour

Logs should be generated to the specified file when `daemonStdoutLogFile := Some("appname")` is provided

## Actual behaviour

The file is not created and all process output is discarded.

## Information

- What sbt-native-packager are you using: `1.2.2`
- What sbt version: `0.13.x`
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ): `Debian`
- What package are you building (e.g. docker, rpm, ...): `Deb`
- What version has your build tool (find out with e.g. `rpm --version`): Using `JDebPackaging`
- What is your target system (e.g. Ubuntu 16.04, CentOS 7): `Debian Jessie with SystemV`

**Comment by timcharper** [comment]
I wonder if the assumption is flawed in that redirects can be specified via an environment variable:

The below program does not output to `greetings.txt`, is simply outputs `hello >> greetings.txt`

```
#!/bin/sh
args=">> greetings.txt"
echo hello $args
```

**Comment by timcharper** [comment]
I can provide a repro case, if helpful. Getting a SystemV OS with OpenJDK 8 is a bit of a feat, I am not sure the best way to write an integration test for this.

**Comment by muuki88** [comment]
Sorry for the late reply here as well 😢  and thanks for the pull request.
Integration tests are really hard for these ones and SystemV is really messy, so
I'm fine with releasing your change and see if others have issues with the new
way of starting the service. Thanks for the detailed commit message with the
related SO question 😍
