### ISSUE TITLE
Upstart init script does not source environment variables, nor does it pass environment variables on

### ISSUE THREAD

**Issue by timcharper** [sbt/sbt-native-packager#1023]
## Expected behaviour

When I generate an upstart template, I would expect that the environment variables specified in `/etc/default/{my-service-name}` would be sources and used by Upstart.

## Actual behaviour

`/etc/default/{my-service-name}` is ignored entirely. Further, the `sudo` command, by default, resets all environment variables, so even if any were specified in the init file, they would be ignored.

## Information

- What sbt-native-packager are you using: `1.2.2`
- What sbt version: `0.13.x`
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ): `Ubuntu`
- What package are you building (e.g. docker, rpm, ...): `debian`
- What version has your build tool (find out with e.g. `rpm --version`)
- What is your target system (e.g. Ubuntu 16.04, CentOS 7): `Ubuntu 14.04`

**Comment by muuki88** [comment]
Sorry for the very late reply 😢 I must have overlooked this one.

I took a look at the code and it seems this hasn't been implemented yet.
For example the [debian systemv start script](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-debian-template#L17) sources the config file, while the [upstart script](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/upstart/start-template) doesn't seem to contain any code doing this.
