### ISSUE TITLE
Add support for --chown flag for ADD/COPY Docker commands

### ISSUE THREAD

**Issue by ahjohannessen** [sbt/sbt-native-packager#1029]
As `--chown` for ADD/COPY has landed in moby here: https://github.com/moby/moby/pull/34263 I think it would be awesome if the following could be done:

 - check docker version using `sys.process.Process` (something a la `docker version --format '{{.Server.Version}}'` and if version is applicable then use `--chown` approach in order to save that notorious duplicate layer that doubles up on application size.

@muuki88 WDYT?

**Comment by muuki88** [comment]
I like the docker version idea. However I would persist the version in in a setting, e.g. `dockerVersion`. 
We may be able to support different things base on that property.

Adding this `chown` feature would be really nice. Would you like to open a pull request for this?

**Comment by ahjohannessen** [comment]
I like you version idea as well. I will look into it, because our images are unreasonably large.

**Comment by muuki88** [comment]
Thanks a lot . Looking forward 😍

**Comment by ahjohannessen** [comment]
@muuki88 oh god OSS is great sometimes 😊 Was thinking about doing this next weekend and then some great champ chimes in and does it! Awesome :)
