### ISSUE TITLE
Provide means to set umask of user?

### ISSUE THREAD

**Issue by keirlawson** [sbt/sbt-native-packager#1032]
It would be great if there was some means of setting the umask of a user created by an RPM build via native-packager. Obviously this can be done with some other provisioning tool but this strikes me as a relatively common requirement that might be worth incorporating directly in native-packager?

**Comment by muuki88** [comment]
Take a look at the `LinuxPackageMapping`.  There are already ways of setting POSIX permissions. Is there something missing?

**Comment by keirlawson** [comment]
I'm wanting to set the default permissions of files created by my process rather than files installed by the package (for example, log files) - for this I need to set the user's umask I believe

**Comment by muuki88** [comment]
Aaaaah. 😃 Thanks for clarifying 😊

That sounds reasonable. What would an ideal API for that look like?

**Comment by keirlawson** [comment]
I guess a daemonUserMask property as part of the Java server application archetype?

**Comment by muuki88** [comment]
With type `Option[String]` an `None` as default I guess? Where would we put the `umask` command. This needs to be part of the bash script, right?

**Comment by keirlawson** [comment]
Ok digging into this a bit more, it seems atleast on our systems (CentOS with System V) the most "correct" place to stick the umask is in `/etc/default/appname` - so settings the umask can be done already using the etc-default-systemv template.  Perhaps rather than adding a new option it might just be better to document this approach for others that might need it?

**Comment by muuki88** [comment]
That sounds even better! 😎 
Less settings mean less maintenance.

**Comment by adrianbn** [comment]
@muuki88 / @keirlawson sorry to revive this issue but I think we still may need this. In CentOS 7 with systemd, setting the umask in `/etc/default/appname` does not seem to work. It'd be needed in `/usr/lib/systemd/system/appname.service` under the `[Service]` label as per `man systemd.exec`.

**Comment by mkurz** [comment]
Added docs for a more general way how to set umask, not just when using System V/systemd: #1274
