### ISSUE TITLE
MAINTAINER in Dockerfile

### ISSUE THREAD

**Issue by NeQuissimus** [sbt/sbt-native-packager#1033]
As per moby/moby#25466, the `MAINTAINER` keyword has been deprecated.
I believe we still use it.

Instead, a `LABEL` is supposed to be used now.

I may send in a PR soon-ish but wanted to open the issue for tracking, in case I do not get around to it.

**Comment by muuki88** [comment]
Thanks for taking care of this 😍
I'm currently on vacation so I won't be able to release anything.

How do we make sure to not break older clients?

**Comment by NeQuissimus** [comment]
`LABEL`s have existed forever and a half (Docker 1.6.0). They are just moving the one-off `MAINTAINER` onto that mechanism.

**Comment by muuki88** [comment]
Okay perfect 👍 looking forward for your PR 😍

**Comment by NeQuissimus** [comment]
#1034

**Comment by muuki88** [comment]
Thanks 😅 
Not used to work on my phone 😁
