### ISSUE TITLE
Support SBT 1.0

### ISSUE THREAD

**Issue by bharath12345** [sbt/sbt-native-packager#1041]
## Expected behaviour
Upgrade from SBT 0.13.16 to 1.0.1 should work

## Actual behaviour
plugin jar for SBT 1.0 does not get resolved

## Information

- What sbt-native-packager are you using
1.2.0

- What sbt version
1.0.1

- What scala version
2.12

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
MacOS

- What package are you building (e.g. docker, rpm, ...)
zip (universal) and docker

Do I have to add any new repo to the resolvers? If so, what exactly?

**This works:**
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.2.0/jars/sbt-native-packager.jar ...
[info] 	[SUCCESSFUL ] com.typesafe.sbt#sbt-native-packager;1.2.0!sbt-native-packager.jar (8450ms)

**This does NOT work:**
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0//1.2.0/ivys/ivy.xml
...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-native-packager;1.2.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**This ALSO does NOT work:**
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_1.0//1.2.0/ivys/ivy.xml
...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.sbt#sbt-native-packager;1.2.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by muuki88** [comment]
Thanks for your question. You are not using the SBT 1.0 compatible version. `1.2.2` is the first version supporting SBT 1.x.
See https://github.com/sbt/sbt-native-packager/releases/tag/v1.2.2
