### ISSUE TITLE
[Idea] JDK 9's jlink & sbt-native-packager?

### ISSUE THREAD

**Issue by ScalaWilliam** [sbt/sbt-native-packager#1043]
I'm wondering if there's anything that can be done with sbt-native-packager and JDK 9's jlink?

Here's the JEP:
- http://openjdk.java.net/jeps/282

Regards,
William

**Comment by muuki88** [comment]
Hi,

This is an interesting topic. I'm not sure yet if this is in scope for native-packager. Still if you have a good use case 😀

**Comment by avkonst** [comment]
I have got a use case for this. My current build process is the following:
* As an intermediate step, I use sbt-native-packager to produce self-sufficient (but still dependent on JRE) zip package.
* As the next step, I unpack this zip to inside of a Docker image based on openjre-alpine docker image (https://github.com/docker-library/openjdk/blob/b4f29ba829765552239bd18f272fcdaf09eca259/8-jre/alpine/Dockerfile). As a result, I have got self sufficient redistributable image for docker.

However, the size of the image is a problem: 5MB Alpine Linux OS + 30MB my java classes + 90MB JRE. So, I would like to use jlink to cut these 90MB of JRE. My build process would look like the following:

* Use sbt-native-package (which invokes jlink) to produce a zip package, which includes my java application classes, script runner and minimal image of JRE produced by jlink
* Unpack this zip tarball to inside of my docker image based on bare Alpine Linux image which is only 5MB.

As a result, I should get the same redistributable docker image, but much smaller in size.

**Comment by zabhi** [comment]
Here is a parallel effort working to bring this to maven: [maven-jlink-plugin](https://maven.apache.org/plugins/maven-jlink-plugin/)

**Comment by Sciss** [comment]
any news on this? wondering how I can create jdk bundled installation packages compatible with Java 11 using sbt-native-packager; I need to build for Linux, Windows, Mac, but only run Linux, so this seems all very complicated. Would jlink offer a solution here?

**Comment by muuki88** [comment]
@nigredo-tori created an amazing jlink plugin. Available since `v1.3.21` and improved till the latest version (v1.3.25)
