### ISSUE TITLE
question: are jar files compressed?

### ISSUE THREAD

**Issue by avkonst** [sbt/sbt-native-packager#1046]
- I would like to understand if jar files, produced by the plugin, are compressed? It seems they are copied as is from the maven repository. 
- How can I change the compression level? If it is not possible, would it be possible to add this feature?

Clarification: my goal is to produce the smallest-footprint of working java application (footprint is measured by the size of unpacked tarball content produced by the universal build).

## Information

- What sbt-native-packager are you using
Universal
- What sbt version
0.13.x
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Windows, Ubuntu
- What package are you building (e.g. docker, rpm, ...)
zip tarbals
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)
java (OS independent)

**Comment by muuki88** [comment]
Hi. Thanks for your question.

native-packager doesn't alter the resulting jars in any way. It takes it as sbt produces them via the `packageBin` task. IIRC jars are actually `zip` files so they are already compressed.

@dwijnand may know more about the `packageBin` task?

**Comment by dwijnand** [comment]
Yeah jar files are glorified zips, so mildly compressed.

I did hear a rumour though that there's an alternative, better compression algorithm that was merged into the jdk years and years ago but no-one uses. If better compression is your need, maybe you should look into that claim.

**Comment by muuki88** [comment]
Thanks @dwijnand :smile:

@avkonst if you find something interesting regarding a better jar compression, it would be awesome if you share it here and repopen the issue. Maybe there is a way to integrate it in native-packager.

**Comment by matanster** [comment]
At the core, do all jars built with `sbt package` and `sbt assembly` compress all files included in them?

**Comment by muuki88** [comment]
neither of those tasks are part of `sbt-native-packager`.

`sbt assembly` comes from the sbt-assembly plugin and `package` is IIRC from sbt itself.
