### ISSUE TITLE
question: How do I pass JVM option to container ?

### ISSUE THREAD

**Issue by unoexperto** [sbt/sbt-native-packager#1047]
Guys, how do I pass JVM option to app inside docker container ?

I tried `javaOptions in Docker ++= Seq("-Dconfig.file=conf/staging.conf")` but it doesn't seem to reach produced launcher script.

I'm on SBT 0.13.12, plugin version is 1.2.0, host system Linux Mint 18.2

**Comment by muuki88** [comment]
Thanks for your question @unoexperto . You are applying the wrong configuration scope.
See the [documentation for customizing the application archetype](http://sbt-native-packager.readthedocs.io/en/stable/archetypes/java_app/customize.html)

```
javaOptions in Universal ++= Seq(...)
```

should work fine.
