### ISSUE TITLE
After upgrading to version 1.3.0, sbt started throwing "docker: 'version --format '{{.Server.Version}}'' not a docker command" warnings on console

### ISSUE THREAD

**Issue by kpritam** [sbt/sbt-native-packager#1051]
## Expected behaviour
Upgrading to packager version 1.3.0 should not result into any warnings on console
E.g. Just run `sbt`

## Actual behaviour
After upgrading to sbt-native-packager 1.3.0, can see following warnings on sbt console:
docker: 'version --format '{{.Server.Version}}'' is not a docker command.

I have docker v17.09.0-ce-mac35 (19611) installed on my machine and it does give me correct version when above command is run from separate terminal:
`~/T/csw-prod:master$ docker version --format '{{.Server.Version}}'`
`17.09.0-ce`

## Information

- What sbt-native-packager are you using?
1.3.0

- What sbt version
1.0.2

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
macOs (iterm2 3.1.3)

**Comment by muuki88** [comment]
Thanks for your detailed bug request and trying out the new release.
I hope this is not an issue with the way java spawns external processes. I'm not familiar with docker on mac, but there is still a vm involved to run docker, right?


cc @mrfyda

**Comment by kpritam** [comment]
No, Docker has added native support for mac hence VM is not involved.
