### ISSUE TITLE
[Feature Request] Universal plugin, directory output format

### ISSUE THREAD

**Issue by woky** [sbt/sbt-native-packager#1061]
Currently it's possible to package application in various types of archives. Universal plugin should also support just creating a directory and skip the archiving step.

Use case: I develop on my local PC and test on remote host. Libraries don't change much. I can use `rsync` to sync changes in local application (one jar most of the time) to the remote. But currently I have to unpack the archive every time I want to upload my changes. It's waste of resources and time to pack/unpack every time I need to upload the changes.

I realize that this is not the typical use case for a _packager_ plugin, but it'd useful and the plugin could do it easily (it does it already behind the scenes). Sometimes, it's not necessary to use an archive. In the end the archive will be unpacked anyway.

EDIT: [sbt-pack](https://github.com/xerial/sbt-pack) works well for my case.

**Comment by muuki88** [comment]
Hi @woky 

Thanks for your feature request. This is actually already available via the `stage` task.
It generates an output directory `target/universal/stage` where all files are simply laid out.

Maybe you could add a small section in the [UniversalPlugin Format documentation](https://github.com/sbt/sbt-native-packager/blob/master/src/sphinx/formats/universal.rst) for future users :)
