### ISSUE TITLE
Remove carriage return characters when loading configuration files.

### ISSUE THREAD

**Issue by JustinPihony** [sbt/sbt-native-packager#1074]
This is to mimic https://github.com/sbt/sbt-launcher-package/pull/166 Without the fix the following yields `Invalid initial heap size: -Xms512M`

```
javaOptions in Universal ++= Seq(
"-J-Xms512M",
"-J-Xmx2G",
"-J-server" 
)
```

## Expected behaviour

Do not throw exception

## Actual behaviour

> Invalid initial heap size: -Xms512M
> Error: Could not create the Java Virtual Machine
> Error: A fatal exception has occurred. Program will exit.

## Information

https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template#L266 should be

`cat "$1" | sed '/^\#/d;s/\r$//'`

**Comment by muuki88** [comment]
Thanks a lot for your detailed bug report :) Sorry for replying so late.

Would you like to provide this fix as a pull request?
