### ISSUE TITLE
windows bat launch script passes jvm options incorrectly if they have '=' sign

### ISSUE THREAD

**Issue by Vistritium** [sbt/sbt-native-packager#1090]
Related to stage goal of "Java Command Line Application" and generated .bat files

When selecting options, for example like this:
`javaOptions in Universal ++= Seq(
  "-J-XX:GCTimeRatio=18"
)`

Generated .bat script when launched trims the option-string at '=' sign, so it becomes
`-XX:GCTimeRatio` instead of `-XX:GCTimeRatio=18`

I have debugged a little and in this loop: https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bat-template#L136
When I print params that are being iterated I see that the options got separated: "XX:GCTimeRatio" and "18" are different elements as if = was a separator.

**Comment by muuki88** [comment]
Thanks for your bug report. I'm not a windows specialist. Can you add some more information, e.g.

- what sbt version are you using
- what windows OS
- what sbt-native-packager version are you using

If you have time and feel confident, you could either write a regression test and open a pull request (we already have a bunch of windows tests in `src/sbt-test/windows`) or you could even propose a fix in a pull request.

If you need any help with sbt, feel free to ask :)
