### ISSUE TITLE
unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.1.4: not found

### ISSUE THREAD

**Issue by shshankar1** [sbt/sbt-native-packager#1100]
## Expected behaviour

sbt compile should be successful.

## Actual behaviour
Required version is not available in artifactory and giving below error:
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-native-packager_2.11_0.13/1.1.4/sbt-native-packager-1.1.4.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-native-packager;1.1.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

## Information
build.sbt:

```sbt
addSbtPlugin("com.typesafe.sbt" %% "sbt-native-packager" % "1.1.4")

scalaVersion := "2.11.8"

name := "USparkScala Project"

val sparkVersion = "1.6.0"

resolvers ++= Seq(
  "bintray-sbt-plugin-releases" at "http://dl.bintray.com/content/sbt/sbt-plugin-releases",
  "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
)

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core"              % sparkVersion withSources()
)

/*
mappings in Universal ++= {
 directory(baseDirectory.value/"data") -> ""
}*/
```

**Comment by muuki88** [comment]
You need to put the

```
addSbtPlugin("com.typesafe.sbt" %% "sbt-native-packager" % "1.1.4")
```

into `project/plugins.sbt` not in your `build.sbt`. The plugins are added to the _project_ that builds your _project_ :)

I recommend the [sbt plugins documenation](https://www.scala-sbt.org/0.13/docs/Using-Plugins.html) as a good read :)

**Comment by rsinghIND** [comment]
@muuki88  @shshankar1  
![Screenshot from 2019-04-16 09-01-01](https://user-images.githubusercontent.com/42250206/56180304-6d487680-6026-11e9-8e0b-58f1492bf276.png)
I am getting the following error. I have placed the plugins in project/plugins.sbt.

**Comment by orientez** [comment]
> @muuki88 @shshankar1
> ![Screenshot from 2019-04-16 09-01-01](https://user-images.githubusercontent.com/42250206/56180304-6d487680-6026-11e9-8e0b-58f1492bf276.png)
> I am getting the following error. I have placed the plugins in project/plugins.sbt.

I have the same problem after adding plugins in project/plugins.sbt.

**Comment by muuki88** [comment]
Have you tried the latest version `1.3.23` ?

**Comment by greebie** [comment]
https://dl.bintray.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.3.25/ivys/ivy.xml is an invalid url.  Is this related to typesafe moving to lightbend?

Going to https://repo.typesafe.com/ tells me that the files are being re-directed.  They suggest you include:

Resolver.typesafeIvyRepo("releases") https://repo.typesafe.com/typesafe/ivy-releases/
Resolver.typesafeRepo("releases") https://repo.typesafe.com/typesafe/maven-releases/

for your plugins.

**Comment by normana400** [comment]
did the plugin get moved from "com.typesafe.sbt" to "com.github.sbt"?

addSbtPlugin("com.github.sbt" %% "sbt-native-packager" % "1.9.4")

**Comment by ekerstens** [comment]
This issue still seems relevant to the [current documentation](https://www.scala-sbt.org/sbt-native-packager/gettingstarted.html) which points users to download from "com.typesafe". Was only able to figure out the install by finding this thread.
