### ISSUE TITLE
Custom name for tgz archive

### ISSUE THREAD

**Issue by AntonYurchenko** [sbt/sbt-native-packager#1120]
Hi, i have a question:
After `universal:packageZipTarball` I have archive `target/universal/myProject-1.0.8.tgz`.
How can I change name of tgz archive? For example `target/universal/myArchive.tgz`

**Comment by muuki88** [comment]
IIRC you can override the `packageName` setting.

Something like

```scala
packageName in Universal := "myArchive.tgz"
```

However I would not really recommend this. Usually you should depend on that task and get the `FIle` value from the `universal:packageZipTarball` task instead of relying on side-effecting IO writes.
