### ISSUE TITLE
Auto generated scripts drop last character if its an `r` 

### ISSUE THREAD

**Issue by tobyweston** [sbt/sbt-native-packager#1121]
## Expected behaviour

`sbt universal:packageBin` generates the following script fragment:

```
loadConfigFile() {
  cat "$1" | sed '/^\#/d;s/\r$//'
}
```
But when run on Mac against the following:

```
-J-server
-J-Xms256m
-J-Xmx512m
-Dcom.sun.management.jmxremote=true 
-Dcom.sun.management.jmxremote.port=1616 
-Dcom.sun.management.jmxremote.authenticate=false 
-Dcom.sun.management.jmxremote.ssl=false 
```

## Actual behaviour

It drops the `r` from `server`, so the JVM fails to start with:

```
Unrecognized option: -serve
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```

You can verify independently of script generation from a terminal by cat'ing the `application.ini` or similar into `sed`. As can be seen here:

```
$ cat src/universal/conf/application.ini | sed '/^\#/d;s/\r$//'
-J-serve
-J-Xms256m
-J-Xmx512m
-Dcom.sun.management.jmxremote=true 
-Dcom.sun.management.jmxremote.port=1616 
-Dcom.sun.management.jmxremote.authenticate=false 
-Dcom.sun.management.jmxremote.ssl=false 

$ cat src/universal/conf/application.ini 
-J-server
-J-Xms256m
-J-Xmx512m
-Dcom.sun.management.jmxremote=true 
-Dcom.sun.management.jmxremote.port=1616 
-Dcom.sun.management.jmxremote.authenticate=false 
-Dcom.sun.management.jmxremote.ssl=false
```

Windows seems fine.

Dropping the `\r` from the `sed` command seems to help. Tested with the following

```
ryder
slider
server
murder
```
...before I ran out of r words

**Comment by dwickern** [comment]
That's supposed to strip carriage return but `sed` works differently on OSX/BSD where `\r` matches a literal `r`. We had the same issue in sbt's own launcher: https://github.com/sbt/sbt-launcher-package/issues/186

Would you mind opening a PR with the same fix from https://github.com/sbt/sbt-launcher-package/pull/187?

**Comment by tobyweston** [comment]
Will do, looks good:

$ echo server | sed '/^\#/d;s/\r$//'
serve
$ echo server | sed $'/^\#/d;s/\r$//'
server

Should l leave the `ash` equivalent alone?

**Comment by dwickern** [comment]
I suppose it wouldn't hurt to update the ash script too... I don't have any experience with it personally

**Comment by tobyweston** [comment]
PR #1122

**Comment by anilkumarmyla** [comment]
I hit the same error while using `-J-XX:+HeapDumpOnOutOfMemoryError`, got intrigued and found this issue

@muuki88 any chance there will be a new release of sbt-native-packager with this fix?

**Comment by muuki88** [comment]
Thanks for the reminder :heart_eyes: Haven't released in a while. A new version will be up today.

**Comment by muuki88** [comment]
done :)

**Comment by anilkumarmyla** [comment]
thank you @muuki88 , will give the new version a try!
