### ISSUE TITLE
Manage graalvm native images

### ISSUE THREAD

**Issue by valdo404** [sbt/sbt-native-packager#1123]
Hi,

Is there any plan to support builds of native executables using graalvm. ie `native-image`.

if not, would you be interested in a prototype + a Pull Request ? I'm playing with it.

Thanks.

**Comment by muuki88** [comment]
Thanks for your notice. 

There are plans now 🤗 this sounds like a very interesting use case for native-packager. I would love to discuss this on prototype pull request. I haven't had the time yet to tinker around with graalvm 😋

**Comment by ScalaWilliam** [comment]
Yes please.

**Comment by lbialy** [comment]
I'd love to help, I'm currently working on a side project containing http4s app compiled to a native binary and I was able to get some insight into DOs and DONTs with `native-image` tool and SVM. Are you guys on gitter?

**Comment by muuki88** [comment]
Thanks for offering your help @lbialy :heart: 

While sbt-native-packager has a gitter channel, I'm very grateful for all discussion happening on github issues and pull requests. I understand that this is more time consuming and not very interactive, but researching the past is a lot easier :wink: ... gitter discussions are hard to find, reconstruct and relate.

@valdo404 if you need any help to get started, feel free to ask. I can recommend the `DockerPlugin` or `RpmPlugin`, which are the most straightforward and clean format plugins.

**Comment by ScalaWilliam** [comment]
I 100% support discussing most things on GitHub @muuki88 . Much easier to read history and context.

**Comment by ScalaWilliam** [comment]
I took on it: https://github.com/sbt/sbt-native-packager/pull/1165

**Comment by ScalaWilliam** [comment]
This is solved. https://sbt-native-packager.readthedocs.io/en/latest/formats/graalvm-native-image.html
