### ISSUE TITLE
systemd vendor preset: enabled - can I change this

### ISSUE THREAD

**Issue by tobyweston** [sbt/sbt-native-packager#1127]
I'm loving the packager at the moment ❤️. We use it in production with the Universal packager but it's really come into its own for a hobby project with great Debian support... anyway, that's just a way to butter you up in order to comment on the below 😄 

I've got things setup to run with systemd and it looks like, by default, the service will be enabled:

```
systemctl list-unit-files
UNIT FILE      STATE    
my-app         enabled <--- HERE!   
```
Which I understand to mean the application will attempt to startup and my users shouldn't need to mess about with `systemctl start my-app` and so on (correct me if I'm wrong).

The fragment below suggests this is the "vendor preset". Which I guess is me...

 ```
$ systemctl status temperature-machine.service 
● my-app.service - my-app
   Loaded: loaded (/lib/systemd/system/my-app.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-05-01 20:17:29 UTC; 7s ago
  Process: 2046 ExecStartPre=/bin/chmod 755 /run/my-app (code=exited, status=0/SUCCESS)
  Process: 2044 ExecStartPre=/bin/chown my-app:my-app /run/my-app (code=exited, status=0/SUCCESS)
  Process: 2041 ExecStartPre=/bin/mkdir -p /run/my-app (code=exited, status=0/SUCCESS)
 Main PID: 2050 (java)
   CGroup: /system.slice/my-app.service
           └─2050 java -Djava.rmi.server.hostname=10.0.1.15 -Xms256m -Xmx512m -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=1616 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxr

May 01 20:17:29 momo systemd[1]: Starting my-app...
May 01 20:17:29 momo systemd[1]: Started my-app.

$ sudo systemctl stop my-app.service 
```

Can I change that? Should I be googling `systemd presets`? Can't quite find the right thing...

If it's a case of editing the template, I could do a PR similar to #441 and #540.

**Comment by muuki88** [comment]
> anyway, that's just a way to butter you up in order to comment on the below :smile: 

works for me :joy: 

> I've got things setup to run with systemd and it looks like, by default, the service will be enabled

That's correct. I figured out that the `serviceAutostart` setting doesn't seem to work with `systemd` though :disappointed: And you probably found the issue. I haven't seen the 

```
Loaded: loaded (/lib/systemd/system/my-app.service; enabled; vendor preset: enabled)
```

but it looks like there is an additional setting in `systemd` services file that control this behavior.
I consider this a bugfix if you can make the `serviceAutostart` setting work for systemd. And that would be awesome :tada:

**Comment by muuki88** [comment]
If I understand [the freedesktop systemd documentation](https://www.freedesktop.org/software/systemd/man/systemd.preset.html) correctly, we would need to add a `*.preset` file for the service if it should not be enabled by default.

**Comment by tobyweston** [comment]
I think I read somewhere that the .preset files come with the dist, is that right? Does that mean we won’t be able to affect it?

**Comment by tobyweston** [comment]
Yep, seems reasonable. I can't see a way to achieve this then, shall we close the ticket?

**Comment by muuki88** [comment]
Yeah. This is unfortunate 😣
