### ISSUE TITLE
Java 10 breaks Unix launcher script

### ISSUE THREAD

**Issue by GreyCat** [sbt/sbt-native-packager#1128]
Generated Unix launcher script includes this check:

```bash
  elif [[ ! "$java_version" > "1.6" ]]; then
    echo
    echo The java installation you have is not up to date
    echo $app_name requires at least version 1.6+, you have
    echo version $java_version
    echo
    echo Please go to http://www.java.com/getjava/ and download
    echo a valid Java Runtime and install before running $app_name.
    echo
    exit 1
  fi
```

This obviously breaks when running using Java 10, because something like `10.0.1` is less than `1.6` when compared stringwise. It could have broken earlier with stuff like `"1.10" < "1.6"`, but I guess we were just lucky as these haven't existed.

## Expected behaviour

Running a generated launcher script launches the process.

## Actual behaviour

```
The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.1

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .
```

Launching with `-no-version-check` works, but is, of course, very wrong.

## Information

- What sbt-native-packager are you using: 1.3.2
- What sbt version: 1.1.1
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ): Debian
- What package are you building (e.g. docker, rpm, ...): basically anything that  (zip, deb, staging)
- What version has your build tool (find out with e.g. `rpm --version`): N/A
- What is your target system (e.g. Ubuntu 16.04, CentOS 7): Linux or OS X

**Comment by muuki88** [comment]
Thanks for your detailed report.

#1111 should have fixed that.

**Comment by GreyCat** [comment]
Thanks, I've missed that!
