### ISSUE TITLE
Can sbt-native-packager help to create Release files?

### ISSUE THREAD

**Issue by tobyweston** [sbt/sbt-native-packager#1129]
I couldn't see anything in the docs, but can it help me create a `Release` file?

Manual steps would be along the lines here https://unix.stackexchange.com/questions/403485/how-to-generate-the-release-file-on-a-local-package-repository 

and it would help me avoid the following warning on `apt-get update`:

```
Reading package lists... Done
W: The repository 'http://example.com/debian ./ Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details
```

**Comment by muuki88** [comment]
Thanks for your feature request.

IIRC native-packager doesn't produce a release file. When you activate `JDebPackaging` a changelog file is generated.

What are the contents of a release file? I fear that this may be out of scope for native-packager

**Comment by tobyweston** [comment]
Thanks for the reply, the `Release` file looks big and scary so would be inclined to agree with you being out of scope.

Out of interest, can you point me at more docs RE the changelog file creation. I could use that to report more with `apt-cache` and mine is currently blank.

See https://wiki.debian.org/DebianRepository/Format#A.22Release.22_files for file format, if I can find an example file (I had one earlier!), I'll post it for reference.

**Comment by muuki88** [comment]
Sorry for not replying :grimacing: I'm not sure how jdeb creates the changelogs.
