### ISSUE TITLE
how to package CLI app on MacOS?

### ISSUE THREAD

**Issue by rolandjohann** [sbt/sbt-native-packager#1133]
I am familiar with RPM, Deb, Docker and in the old days the universal zip. Today I wanted to install a Scala CLI app on my mac and recognized that there is no rule of thumb how to do that.
The desired way is to do that via some sort of package manager, so one don't have to move files into different places at file system.

How do you install apps at MacOS?

**Comment by muuki88** [comment]
Thanks for your question @rolandjohann  :)

sbt-native-packager provides two ways for building `dmg` files, which are AFAIK the common package format for MacOS X. I have never build a native

- [Universal Plugin](https://sbt-native-packager.readthedocs.io/en/latest/formats/universal.html#build) provides a `universal:packageOsxDmg` task. 
- [JdkPackager](https://sbt-native-packager.readthedocs.io/en/latest/formats/jdkpackager.html#settings) can build two kinds of mac osx packages. It simply wraps the java8 javapackager interface. 

hope that helps :)

If you found a good solution would you mind sharing it here?

**Comment by rolandjohann** [comment]
already tried both ways.

DMG output will install the app to Applications directory.
As far as I can remember JdkPackager was the same.

What I need is a way to install the app as CLI and use it from shell. Therefore the CLI must be placed at some directory which is in the PATH.

As of now, one must package with `universal:packageBin`, unzip to `/usr/local/bin` or somewhere else. On new release old binaries must be removed and start from beginning - this is anarchy 😉
This is due lack of native package manager at MacOS.

I had the hope that someone came across this issue already and has a proper solution.

**Comment by LeifW** [comment]
On OSX you can use the `pkgbuild` command to create a package that installs a command-line program to e.g. `/usr/local/`.
Example invocation: https://github.com/idris-lang/Idris-dev/blob/master/mkpkg.sh#L61

**Comment by dportabella** [comment]
@rolandjohann , did you find a solution?

**Comment by rolandjohann** [comment]
@dportabella not yet. Currently I `stage` the project and use the starter script at `target` dir...
