### ISSUE TITLE
can sbt-native-packager be used to pack /test ?

### ISSUE THREAD

**Issue by abioneperhobby** [sbt/sbt-native-packager#1136]
I'm developing a suite of test that use scalatest as testing framework.

Normally, /test cover software developed in /src folder , but in this case, there is any software. There are only tests. 

In /src there are some utility classes. 

The project is sbt related.

I would to pack the project in order to create a docker image to put on aws ec2 to be able to run test on the cloud.

can sbt-native-packager be used to pack test?

thanks.

**Comment by muuki88** [comment]
Sure. There are multiple ways to do this.

First you could simply add the `sourceDirectories in Test` to the `sourceDirectories in Compile`. 

Or you can write your tests directly in the source directory. After all if your package runs tests, than these are the source files.

Last option could be to add the `packageBin in Test` to `univeral:mappings`.


What you should do in all cases is specify a `mainClass` ( either `in Compile` or `in Test`, depending on the solution you choose ). The main class would be the scalatest main class.

**Comment by abioneperhobby** [comment]
@muuki88 thanks for the tips. 

i choose the solution to add sourceDirectories in Test and maintain the actual file structure.

i modified build.sbt adding

`scalaSource in Compile := baseDirectory.value / "test"`

but this change the package (my package is qa. , and code is not able to find other classes in qa. anymore) so i tried with

`unmanagedSourceDirectories in Compile += baseDirectory.value / "test"`

that don't break the code. it is right?

i don't understand what you are suggesting me about the test main class. i don't have any main class in the test, because every single class can be runned alone in order to cover a test. 

![image](https://user-images.githubusercontent.com/2149815/42386028-aa6b2638-813e-11e8-9a0c-69ae2b266e28.png)

can you give me other helps about the main class?

thanks.
