### ISSUE TITLE
dockerUpdateLatest doesn't update latest

### ISSUE THREAD

**Issue by jtownley** [sbt/sbt-native-packager#1141]
## Expected behaviour
When `dockerUpdateLatest in Docker := true` in in build.sbt
and command `sbt docker:publish` is executed
should publish the version tag and latest tag to repo

## Actual behaviour

- Only version tag is published to repo
- The lastest tag is not published if latest is not there 
- The lastest tag is not updated if it is there.

## Information

- What sbt-native-packager are you using: 1.3.6
- What sbt version: 1.1.6
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ): Mac (10.13.6)
- What package are you building (e.g. docker, rpm, ...): docker 

Docker Version: 
```
docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

Of Note:
- Publishing to nexus repository.
- version tag publishes correctly.
- Doesn't have any information in the log about even trying this.

**Comment by muuki88** [comment]
Thanks for your detailed nnig report 👍

Have you tried 

```scala
dockerUpdateLatest := true
```

Settings already prefixed with `docker*` don't require any additional scoping.

**Comment by tonyamelnychuk** [comment]
Are there any updates on this fix? It seems I faced the same issue: this `dockerUpdateLatest := true` does not update an existing docker image tagged as 'latest' if I run `docker/publish` 2 times e.g . I expected that it has to update the latest image with every new module version..

**Comment by nimaeskandary** [comment]
I'm having issues with a multi project build (github.com/vinyldns). If i set `dockerUpdateLatest` to `true` it does not update latest nor if I set `dockerUpdateLatest in project1` to `true`

**Comment by muuki88** [comment]
> It seems I faced the same issue: this dockerUpdateLatest := true does not update an existing docker image tagged as 'latest' if I run docker/publish i.e 2 times

If the build returns the same output, the docker image shouldn't change, right? We configure `dockerAliases` (see [DockerPlugin](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L99-L106)) with a `latest` tag.

The `dockerAliases` are then appended to the `dockerBuildOptions` in the form of `-t ${alias.toString}`, see [DockerPlugin](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L113-L115). This should result in somthing like

```bash
$ docker build --force-rm -t aliasOne -t latest .
```
