### ISSUE TITLE
Rpm: publish

### ISSUE THREAD

**Issue by tolikr** [sbt/sbt-native-packager#1143]
I build rpm package with rpm:packageBin. It produces nice formatted file: "app-2.8.18-1.noarch.rpm".
But when i publish it with rpm:publish:
1. Name changed to "app-2.8.18-SNAPSHOT.rpm"
2. packet placed in strange location "com/my/package/app/2.8.18-SNAPSHOT/app-2.8.18-SNAPSHOT.rpm"

Is there option to change this behaviour or i should write my own custom publish plugin?

# Information
- What sbt-native-packager are you using 1.3.6
- What sbt version 1.1.6
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) Ubuntu
- What package are you building (e.g. docker, rpm, ...) rpm
- What version has your build tool (find out with e.g. `rpm --version`) RPM version 4.14.1
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)  CentOS 7

**Comment by muuki88** [comment]
Thanks for your detailed report.
Native-packager offers an `RpmDeployment` plugin, but it's not well supported as the scope is building packages.

If the `RpmDeployment` plugin doesn't help, the best idea as you mentioned, is to write your own publishing plugin.

**Comment by dwickern** [comment]
`rpm:publish` would publish the artifact to a maven repository. The filename and path you see are maven conventions.

**Comment by tolikr** [comment]
In resolvers i found basePatterns implicit parameter override it artefactPattern field publish works as i expected.
