### ISSUE TITLE
Version check doesn't work for openjdk 10

### ISSUE THREAD

**Issue by antonwierenga** [sbt/sbt-native-packager#1145]
## Expected behaviour
No 'java is not up to date' message when java 1.6 is required and I have openjdk 10 installed.

## Actual behaviour
The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.2

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .

$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)

## Information
sbt-native-packager 1.1.4
sbt.version=0.13.11

**Comment by muuki88** [comment]
Thanks for your detailed report 👍

This should be already fixed in the latest native-packager version.

**Comment by yogeshbidari** [comment]
I am facing same issue with OpenJdk11 on centos8.

LOG:

The java installation you have is not up to date
requires at least version 1.6+, you have
version 11.0.6

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .


$java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)



**Information**
sbt-native-packager 1.3.6
sbt.version=0.13.11
