### ISSUE TITLE
Default dockerBaseImage value should be set to Java 8.

### ISSUE THREAD

**Issue by wjlow** [sbt/sbt-native-packager#1146]
## Expected behaviour

Not setting `dockerBaseImage` should default to some version of Java 8, which is the most recent Java version that is supported by Scala.

## Actual behaviour

`dockerBaseImage` is set to `openjdk:latest`, the `latest` tag [changed from 8 to 10 recently](https://github.com/docker-library/openjdk/commit/73d767bdc5525a71654cb3309f8338a5dd8f89d2). This can cause problems in Scala apps.

## Information

- What sbt-native-packager are you using: 1.3.6
- What sbt version: 1.1.1
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ): MacOS
- What package are you building (e.g. docker, rpm, ...): docker
- What version has your build tool (find out with e.g. `rpm --version`): 18.03.0-ce
- What is your target system (e.g. Ubuntu 16.04, CentOS 7): Not sure

**Comment by muuki88** [comment]
Thanks for your detailed report 👍

Would you mind fixing this? This sounds like a reasonable suggestestion. IIRC there maybe something like `openjdk:java8-latest`?

**Comment by wjlow** [comment]
Yup, `openjdk:8` should give the latest Java 8.

I can try and raise a PR!

**Comment by wjlow** [comment]
Raised https://github.com/sbt/sbt-native-packager/pull/1147
