### ISSUE TITLE
Automatic relaese process from travis

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#1148]
The current release process requires a few manual steps and credentials on my (@muuki88) machine.
In order to allow any maintainer to release native-packager we need to move the process to travis.

- [x] use [sbt-gpg](https://github.com/jodersky/sbt-gpg) which has already nice tutorial on how to do this on travis
- [x] provide an encrypted github API key
- [x] install [github changelog generator](https://github.com/github-changelog-generator/github-changelog-generator) and use the encrypted github API key to generated the changelog
- [ ] document the process
- [x] check if [sbt-dynver](https://github.com/dwijnand/sbt-dynver) works for us
- [ ] push back to github: [tutorial 1](https://gist.github.com/willprice/e07efd73fb7f13f917ea), [tutorial 2](https://gist.github.com/Maumagnaguagno/84a9807ed71d233e5d3f)
- [ ] test with @dwickern 

[sbt-graphql](https://github.com/muuki88/sbt-graphql) already has such a process. Maybe we can take some hints there as well.

**Comment by muuki88** [comment]
`sbt-release` fails because of the detached HEAD state of the github repository.
https://travis-ci.org/sbt/sbt-native-packager/jobs/420972225

```
fatal: ref HEAD is not a symbolic ref
[error] java.lang.RuntimeException: Nonzero exit value: 128
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:134)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:104)
[error] 	at sbtrelease.Git.currentBranch(Vcs.scala:138)
[error] 	at sbtrelease.Git.trackingRemoteCmd$lzycompute(Vcs.scala:133)
[error] 	at sbtrelease.Git.trackingRemoteCmd(Vcs.scala:133)
[error] 	at sbtrelease.Git.hasUpstream(Vcs.scala:136)
[error] 	at sbtrelease.ReleaseStateTransformations$.$anonfun$checkUpstream$1(ReleaseExtra.scala:215)
[error] 	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$.$anonfun$releaseCommand$8(ReleasePlugin.scala:193)
```

**Comment by muuki88** [comment]
Maybe try sbt-release-early or take a look at https://github.com/olafurpg/sbt-ci-release/blob/master/readme.md

**Comment by muuki88** [comment]
Done. Documented in the developer guidelines.

**Comment by muuki88** [comment]
@dwickern can you try to release a sbt-native-packager version as described in https://github.com/sbt/sbt-native-packager/wiki/Developer-Guide#release-and-publish

**Comment by dwickern** [comment]
I pushed a `v1.3.8-M15` tag and I can see it published on bintray. Amazing work on this!

**Comment by muuki88** [comment]
Awesome 🤩🎉 

Now you can release as well 😎
