### ISSUE TITLE
Found conflicts in dependencies

### ISSUE THREAD

**Issue by tolikr** [sbt/sbt-native-packager#1153]
## Expected behaviour

'sbt' should not show any warnings.

## Actual behaviour

I see warnings when i add plugin sbt-native-packager.

> 
> [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
> [warn]  * org.codehaus.plexus:plexus-utils:3.0.17 is selected over {2.1, 1.5.5}                
> [warn]      +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)                   
> [warn]      +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)              
> [warn]      +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)                    
> [warn]      +- org.apache.maven:maven-model:3.2.2                 (depends on 3.0.17)        
> [warn]      +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)           
> [warn]      +- org.apache.maven:maven-artifact:3.2.2              (depends on 3.0.17)          
> [warn]      +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)           
> [warn]      +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)            
> [warn]      +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)                   
> [warn]      +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 2.1)                     
> [warn]  * com.google.guava:guava:20.0 is selected over {10.0.1, 16.0}                          
> [warn]      +- com.spotify:docker-client:8.9.0                    (depends on 20.0)             
> [warn]      +- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.8.8 (depends on 16.0)       
> [warn]      +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 10.0.1) 
> 

## Information

- What sbt-native-packager are you using 1.3.6
- What sbt version 1.1.6
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) Ubuntu

**Comment by davideicardi** [comment]
I have the same warnings, solved using:

```
// resolve plugin dependencies conflict
dependencyOverrides += "org.codehaus.plexus" % "plexus-utils" % "3.0.17"
dependencyOverrides += "com.google.guava" % "guava" % "20.0"
```

Not sure if there are better ways...

**Comment by muuki88** [comment]
Thanks for sharing this @davideicardi :heart: 

The issues came with the sbt 1.x upgrade. [See the FIXME entry in the `build.sbt`](https://github.com/sbt/sbt-native-packager/blob/master/build.sbt#L30). I haven't figured out a way to resolve this yet. The `JDebPlugin` seems to eagerly initialize the settings even if it's not applied.

**Comment by tolikr** [comment]
Some conflicts have disappeared after updating to sbt-native-packager 1.3.15.

> [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * org.scala-lang.modules:scala-xml_2.12:1.1.1 is selected over 1.0.5
[warn]      +- com.typesafe.sbt:sbt-native-packager:1.3.15 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.0.5)
[warn]      +- org.scoverage:scalac-scoverage-plugin_2.12:1.3.1   (depends on 1.0.5)
[warn]  * com.google.guava:guava:20.0 is selected over 18.0
[warn]      +- com.spotify:docker-client:8.14.3                   (depends on 20.0)
[warn]      +- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.9.6 (depends on 18.0)
[warn] Run 'evicted' to see detailed eviction warnings

**Comment by muuki88** [comment]
From which version? Can you try `1.3.17`. The docker client is now in provided scope again. So if you don't require docker, it should work fine.

**Comment by tolikr** [comment]
With 1.3.17 output is:

>[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * org.scala-lang.modules:scala-xml_2.12:1.1.1 is selected over 1.0.5
[warn]      +- com.typesafe.sbt:sbt-native-packager:1.3.17 (scalaVersion=2.12, sbtVersion=1.0) (depends on 1.0.5)
[warn]      +- org.scoverage:scalac-scoverage-plugin_2.12:1.3.1   (depends on 1.0.5)
[warn] Run 'evicted' to see detailed eviction warnings

**Comment by muuki88** [comment]
Do you use the `scala-xml` library somewhere or does this cause any issues?

**Comment by tolikr** [comment]
> does this cause any issues
I think only warn message.

> Do you use the `scala-xml` library somewhere
It used in build.sbt as project dependencies.

**Comment by muuki88** [comment]
Okay :+1:  If this doesn't cause any issue then we're good. There tend to be a lot of eviction warnings in jvm land :cry:
