### ISSUE TITLE
I cannot use sbt-native-packager to build a setup for test classes

### ISSUE THREAD

**Issue by liebichw** [sbt/sbt-native-packager#1157]
## Expected behaviour

I wanted to use the sbt-native-packager plugin to create a setup for certain test classes (for internal use in our team).
I tried to use the method shown in https://stackoverflow.com/questions/31186204/how-to-add-a-project-test-jar-to-a-package/31367788#31367788 (i.e. add a mapping for the test-jar).

## Actual behaviour

This works insofar as the "stage" command now also creates and adds the test jar. But it complains that no mainClass was found and thus no start script was created.
If I call "test/stage", the result is the same.
When I set the "mainClass in Compile" setting to the wanted class, a start script is created, but it fails because the test-jar is not present in this script's classpath!

## Information

I am using
- sbt-native-packager version 1.3.6
- sbt version 1.1.6
- I am running the build under gentoo linux
- I just tried to get a "stage" working (an universal build is enough). A universal ZIP file with bash and cmd start scripts is fully enough for me.

**Comment by liebichw** [comment]
I found newer plugin releases (strange - github tells me 1.3.6 is the latest release and offers me to show newer tags?), but the problem persisted also with the plugin version 1.3.9.

**Comment by muuki88** [comment]
Thanks for your detailed issue :hugs: This question is similar to #1136 I guess. 

Your attempt doesn't work, because adding something to the `mappings`, doesn't add it to the `classpath`. These are two separate things. You can extend your solution like this

```scala
// adds the test jar to mappings
mappings in Universal += {
  // generates the test package
  val testjar = (packageBin in Test).value
  // maps this file to your lib folder in your output package
  testjar -> s"lib/${testjar.getName}"
},
scriptClasspath += (packageBin in Test).value.getName
```

If you `inspect` the `scriptClasspath` task you will see the description:

```
[info] Task: scala.collection.Seq[java.lang.String]
[info] Description:
[info] 	A list of relative filenames (to the lib/ folder in the distribution) of what to include on the classpath.
```

**Comment by er1c** [comment]
This approach works for a single project, but in a multi-project (e.g. https://github.com/muuki88/sbt-native-packager-examples/blob/master/multi-module-build/build.sbt) doesn't include any of the `dependsOn` test artifacts.  Is it also possible to modify/give an example where the `sbt test/stage` produces a different result than simply `sbt stage`?

**Comment by er1c** [comment]
I semi-figured out one of my issues.  Adding the `inConfig(Test)` allows this to trigger in scope properly to `sbt test:stage`.  The current issue I am working on, is trying to get the aggregate/dependsOn test packages also added.  I had to add the `NativePackagerHelper.fromClasspath((managedClasspath in Test).value, ".", _ ⇒ true).map(_._2) :+` stuff to get the scalatest dependency added.  If there is a better method for that I'm interested :)

```
  .settings(inConfig(Test)(Seq(
    mainClass in Compile := Some("org.scalatest.tools.Runner"),
    scriptClasspath ++=
      NativePackagerHelper.fromClasspath((managedClasspath in Test).value, ".", _ ⇒ true).map(_._2) :+
        (packageBin in Test).value.getName,

    mappings in Universal ++= {
      val testJar = (packageBin in Test).value

      NativePackagerHelper.fromClasspath((managedClasspath in Test).value, "lib", _ ⇒ true) :+
        (testJar → s"lib/${testJar.getName}")
    },
  )))
  // always run all commands on each sub project
  .aggregate(foo, bar, baz)
  // this does the actual aggregation
  .dependsOn(foo, bar)
```
