### ISSUE TITLE
fileDescriptorLimit could not set according to system default value

### ISSUE THREAD

**Issue by SyinChwunLeo** [sbt/sbt-native-packager#1158]
## Expected behaviour

when packaging, sbt-native-packager will use default value of fileDescriptorLimit or use user defined. If is it possible to use the ulimit value of app running machine?

for example, I package using the default value (1024), but the app running machine is 100000, when I check /proc/PID/limits, the "Max open files" is 1024, not 100000.

If I set a fixed value, the app will run on different machines, and their system "max open files" are different. Maybe it is unreasonable to use a fixed value when packaging

**Comment by SyinChwunLeo** [comment]
* I run the application on CentOS 7 and set configurations in /etc/security/limits.conf as follows:
```shell
*  soft   nofile    1000000
*  hard  nofile     1000000
```     
    and using ulimit -Hn  or ulimit -Sn command return 1000000.    
* My sbt-native-packager is version 1.2.0    
```java
 addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.0") 
```
* I use `systemd`    
```java
enablePlugins(RpmPlugin, JavaServerAppPackaging, SystemdPlugin)
```
* When I do not use `fileDescriptorLimit := Some("1000000")` this configuration, the `Max open files` is 1024 (this is the default value https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala line 78) When using `fileDescriptorLimit := Some("1000000")`, `Max open files` is 1000000.
* app's `Max open files` can be found by `cat /proc/PID/limits`.

**Comment by muuki88** [comment]
Thanks for the more detailed explanation :smile: 

At the moment we don't have conditional template replacements. [This is the systemd template](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemd/start-template#L20) that renders the systemd service conf. Is there a "magic" value that says "use system default"? 

I haven't had any issue with file descriptor limits. What's the use case for making this limit not application specific?

**Comment by SyinChwunLeo** [comment]
I catch this case by a bug, In our application, HttpClient jar is used to  call RESTFUL API, unfortunately， after running period of time, app throws "too many files open" exception.

**Comment by muuki88** [comment]
Thanks for sharing 🤗 

I guess then there's no need to configure this in another way, right?

**Comment by SyinChwunLeo** [comment]
maybe

**Comment by tolikr** [comment]
Systemd ignores limits from places like limits.conf.
https://serverfault.com/questions/628610/increasing-nproc-for-processes-launched-by-systemd-on-centos-7
