### ISSUE TITLE
Docker - Only publish "latest"

### ISSUE THREAD

**Issue by sambokai** [sbt/sbt-native-packager#1159]
Hi guys,

is there a way to specify that we only want to publish the `latest` image. 

We use `dockerUpdateLatest = true` and we do not change version numbers using sbt. 

That means that our published images will always have the `latest` and `1.0` tags. 
We only want to publish the `latest` one. 

Is there a way to specify which images to publish by tag?

**Comment by muuki88** [comment]
Thanks for your question @sambokai 

You can override the `dockerAliases` setting and only add what you need.
For more information [see the DockerPlugin documentation](https://sbt-native-packager.readthedocs.io/en/stable/formats/docker.html?highlight=dockerAliases)
