### ISSUE TITLE
Cannot append classifier to the tgz generated by Universal

### ISSUE THREAD

**Issue by LeonardMeyer** [sbt/sbt-native-packager#1160]
## Expected behaviour
(What I actually want to do is in the title, but here what I tried below) 
I expect SBT to publish my tgz as generated by my overriden `universal:packageZipTarball` task.

## Actual behaviour
When I execute the task `universal:publish` I expect SBT to publish the tgz archive generated by `universal:packageZipTarball`, which I redefined to add the classifier like so : 

```
    packageZipTarball in Universal := {
      val originalFile = new RichFile((packageZipTarball in Universal).value)
      val (base, ext) = originalFile.baseAndExt
      val newFileName =
        if (isSnapshot.value) {
          optClassifier.value.map(base + "-" + _ + "." + ext).getOrElse(originalFile.name)
        } else originalFile.name
      val oldFile = originalFile.asFile
      val newFile = new File(oldFile.getParentFile.getPath + "/" + newFileName)
      IO.move(oldFile, newFile)
      newFile
    }
```
Except it's not using my classified tgz but a regular one without the classifier (I am confused as to how he generates/gets it)

## Information

- What sbt-native-packager are you using : 1.3.6
- What sbt version : 1.1.6
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) :  Mint
- What package are you building (e.g. docker, rpm, ...) : tgz
- What version has your build tool (find out with e.g. `rpm --version`) : No idea
- What is your target system (e.g. Ubuntu 16.04, CentOS 7) : N/A

**Comment by LeonardMeyer** [comment]
@muuki88 I tried that. It works locally when I run `universal:packageZipTarball` (i.e archive has the classifier) but as soon as I use `universal:publishLocal` or `universal:publish` it doesn't. The archive is respectively named xxxx.tgz or xxxx-SNAPSHOT.tgz, when I want xxxx-SNAPSHOT-classifier.tgz

**Comment by muuki88** [comment]
Are you using the `UniversalDeployment` plugin? Publishing is not in the scope of native-packager, this is why there's not much documentation on that topic

**Comment by LeonardMeyer** [comment]
@muuki88 Yes the `UniversalDeployPlugin` is enabled on my apps.

**Comment by LeonardMeyer** [comment]
Solved it doing this: 

```
    packagedArtifacts in Universal := {
      (packagedArtifacts in Universal).value.map {
        case (art, file) => addClassifier(isSnapshot.value, classifier.value, art) -> file
      }
    },
    artifacts in (Universal, packageZipTarball) := {
      val snapshot = isSnapshot.value
      val jiraId = jiraTicket.value
      (artifacts in (Universal, publish)).value.map(addClassifier(isSnapshot.value, classifier.value, _))
    }
```
