### ISSUE TITLE
WindowsPlugin: support multiple .wxs inputs

### ISSUE THREAD

**Issue by nigredo-tori** [sbt/sbt-native-packager#1176]
This would be useful when working with custom WiX scripts - for example, when harvesting a directory using `heat`. Since `heat` generates a separate `.wxs` file, the only option to use it with the current `packageBin` implementation would be transforming it to an include file, which is incredibly ugly, and would require working around the copy logic.

Both `candle` and `light` support using multiple input files, so implementing this feature can be as simple as replacing `wixFile: TaskKey[File]` with `wixFiles: TaskKey[Seq[File]]`, and updating `packageBin` implementation accordingly. If there's a need to preserve compatibility with the code that uses `wixFile`, we can keep `wixFile` and just do this:
```scala
wixFiles := List(wixFile.value)
```

**Comment by muuki88** [comment]
Thanks for this feature request. Would you like to make a pull request for this?
