### ISSUE TITLE
LinuxPackageMappings in Rpm. Cannot resolve symbol packageMapping for sbt 0.13.15

### ISSUE THREAD

**Issue by CloseRa** [sbt/sbt-native-packager#1180]
Hello, there was a problem after upgrading the version sbt 0.13.5 to 0.13.15 and sbt-native-packager 0.8.0-M1 to 1.0.1. Now IntelJ Idea cannot resolve symbol packageMapping.

In the version sbt-native-packager 0.8.0-M1, the packageMapping method was in com.typesafe.sbt.packager.linux.LinuxPlugin. This method is now in com.typesafe.sbt.packager.linux.LinuxMappingDSL and cannot be imported. 
Please, help!

![image](https://user-images.githubusercontent.com/21340860/50087729-0b136c80-0212-11e9-83c8-86521aa76953.png)

**Comment by muuki88** [comment]
With `1.x` we updated to auto plugins. If you write scala code you need to import the methods explicitly you want to call. In `*.sbt` files these are available through the `autoImport` sbt magic.

So

```scala
import com.typesafe.sbt.packager.linux.Mapper._
```

fixes your issue.

- https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/linux/LinuxMappingDSL.scala
- https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala#L25
