### ISSUE TITLE
sbt packageZipTarball is slower than sbt dist

### ISSUE THREAD

**Issue by ikr0m** [sbt/sbt-native-packager#1182]
## Expected behaviour
`sbt packageZipTarball` should finish its job almost same time as `sbt dist`

## Actual behaviour
`sbt packageZipTarball` is 3 times slower than `sbt dist`
`sbt dist` takes 13 seconds, `sbt packageZipTarball` takes around 40 seconds.

## Information
Checked with sbt 1.1.0 and sbt 1.2.7
Checked on Kubuntu 16.04, centos 7
I run these commands from terminal. 
> sbt universal:packageZipTarball
> sbt dist

**Comment by ikr0m** [comment]
My project has 3 subprojects. I use playframework 2.6 and scala 2.12.7

**Comment by kardapoltsev** [comment]
Could you post logs somewhere please? Do both commands run for each project?
