### ISSUE TITLE
1.6.0 not compatible with Lagom 1.4.10

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt-native-packager#1184]
After Play 2.6.20 the Play dependency to `sbt-native-packager` [bumped to `1.3.15`](https://github.com/playframework/playframework/blob/2.6.x/framework/project/plugins.sbt#L8).

`sbt-reactove-app` uses `sbt-native-packager` by [extending `DockerKeys`](https://github.com/lightbend/sbt-reactive-app/blob/275bad4a771860d73e0a514d0746c805713dc15b/src/main/scala/com/lightbend/rp/sbtreactiveapp/SbtReactiveAppPlugin.scala#L95). `DockerKeys` in `sbt-native-packager` changed in the `1.3.x` family (new fields added in `1.3.12` and `1.3.14`).

Using `sbt-reactive-app` with Play `2.6.21` is not possible:

```
...
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project lagom-minimal-deployment-sample from build.sbt ...
[error] java.lang.AbstractMethodError
[error]         at com.typesafe.sbt.packager.docker.DockerKeys.$init$(Keys.scala:25)
[error]         at com.lightbend.rp.sbtreactiveapp.SbtReactiveAppPlugin$localImport$.<init>(SbtReactiveAppPlugin.scala:95)
[error]         at com.lightbend.rp.sbtreactiveapp.SbtReactiveAppPlugin$localImport$.<clinit>(SbtReactiveAppPlugin.scala)
[error]         at com.lightbend.rp.sbtreactiveapp.DeployableApp.projectSettings(Deploy.scala:193)
[error]         at com.lightbend.rp.sbtreactiveapp.DeployableApp.projectSettings$(Deploy.scala:36)
[error]         at com.lightbend.rp.sbtreactiveapp.BasicApp$.projectSettings(App.scala:260)
[error]         at com.lightbend.rp.sbtreactiveapp.SbtReactiveAppPlugin$.projectSettings(SbtReactiveAppPlugin.scala:109)
[error]         at com.lightbend.rp.sbtreactiveapp.SbtReactiveAppPlugin$.projectSettings(SbtReactiveAppPlugin.scala:46)
[error]         at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1062)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
...
```

Both `sbt-reactive-app` `1.5.0` and `1.6.0` fail.

This is arguably a Play issue and not a `sbt-reactive-app` issue though.

**Comment by ignasi35** [comment]
This issue doesn't belong to this repo. Moving to `sbt-reactive-app`.

Apologies,

**Comment by dwijnand** [comment]
Btw I think it's _also_ an sbt-native-packager issue because adding a field to a trait is binary incompatible.

**Comment by muuki88** [comment]
Thanks for pointing this out :smiley: 

Responsible PRs
- #1137
- #1138

I think the main issue here is that these traits a public. They aren't meant to be use. As @dwijnand [correctly points out](https://github.com/lightbend/sbt-reactive-app/issues/168#issuecomment-452719311) one should use the `autoImport` object.

**Comment by muuki88** [comment]
Maybe we mark all `*Keys` traits as private?

**Comment by dwijnand** [comment]
That's also binary incompatible.

I think you should deprecate `DockerKeys` so users move away from it.

**Comment by dwijnand** [comment]
Also, I think you should MiMa check the code.

**Comment by muuki88** [comment]
> That's also binary incompatible.

I know :stuck_out_tongue_winking_eye: Deprecating and then making them private should be the way to go. Maybe now there's enough stuff to actually make a `2.x` version.

#1185

(Milestone `2.0`](https://github.com/sbt/sbt-native-packager/milestone/5)
