### ISSUE TITLE
Defining a user in multi-stage builds

### ISSUE THREAD

**Issue by jw3** [sbt/sbt-native-packager#1195]
Using v1.3.16 and the multi-stage feature from #1190

The first stage of the multi-stage build may not have adequate rights to perform the `chmod` if the base image was already using an unprivileged user.

You should be able to reproduce this using something like

```
  dockerBaseImage := "fabric8/java-centos-openjdk8-jdk",
  dockerPermissionStrategy := DockerPermissionStrategy.MultiStage,
  dockerChmodType := DockerChmodType.UserGroupWriteExecute
```

Which produces a first stage of

```
FROM fabric8/java-centos-openjdk8-jdk as stage0
WORKDIR /opt/docker
RUN id -u daemon || useradd --system --create-home --uid 1001 --gid 0 daemon
COPY opt /opt
RUN ["chmod", "-R", "u=rwX,g=rwX", "/opt/docker"]
```

User of the fabric8 image is already non-root
```
$ docker run --rm fabric8/java-centos-openjdk8-jdk whoami
jboss
```

Could specify a user via configuration, or perhaps the first stage can safely be switched to `USER root`?

**Comment by jw3** [comment]
The errors produces are a list of chmod failures

```
chmod: changing permissions of '/opt/docker': Operation not permitted
chmod: changing permissions of '/opt/docker/bin': Operation not permitted
...
```

**Comment by muuki88** [comment]
Thanks for the detailed report :+1: 

I guess running the `stage0` with `USER root` is a viable option as this doesn't affect the application image. Would you like to open a PR for this?

@eed3si9n any objections?

**Comment by eed3si9n** [comment]
That makes sense.

**Comment by eed3si9n** [comment]
Pull request here - https://github.com/sbt/sbt-native-packager/pull/1197

**Comment by muuki88** [comment]
`v1.13.17` is on its way
