### ISSUE TITLE
Docs for specific version not published (regression)

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt-native-packager#1203]
Docs for recent versions (e.g. [`1.3.17`](https://sbt-native-packager.readthedocs.io/en/v1.3.17/) and [`1.3.18`](https://sbt-native-packager.readthedocs.io/en/v1.3.18/)) were not published.

This seems like a regression of https://github.com/sbt/sbt-native-packager/issues/1087

**Comment by muuki88** [comment]
Seems the same issue. Readthedocs seems to be a bit slow. The process for `1.3.18` just now triggered.

**Comment by ignasi35** [comment]
https://sbt-native-packager.readthedocs.io/en/v1.3.18/ is now available. Thanks @muuki88

**Comment by mkurz** [comment]
Can you please publish docs for 1.3.19? Thanks!
