### ISSUE TITLE
Is there a way to skip tests?

### ISSUE THREAD

**Issue by omnipresent07** [sbt/sbt-native-packager#1204]
## Expected behaviour

`sbt 'set test in Test := {}' -batch hmda-platform/docker:stage` does not skip tests

neither does

`sbt 'set test in assembly := {}' -batch hmda-platform/docker:stage` does not skip tests

## Actual behaviour

`sbt 'set test in Test := {}' -batch hmda-platform/docker:stage` should skip tests

## Information

- What sbt-native-packager are you using
`1.3.2`
- What sbt version
`1.2.0`
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
`Mac`
- What package are you building (e.g. docker, rpm, ...)
`docker`
- What version has your build tool (find out with e.g. `rpm --version`)
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)
`Mac`

**Comment by muuki88** [comment]
Thanks for your bug report :smile: 

From your explanation it looks like you are actually using `sbt-assembly`, which does run tests during assembly if not configured otherwise. `sbt-native-packager` doesn't configure anything to run tests during build.
