### ISSUE TITLE
Error "Reference to undefined setting: makeBashScripts from dockerAdditionalPermissions" (since v1.3.18)

### ISSUE THREAD

**Issue by thomschke** [sbt/sbt-native-packager#1205]
Since v1.3.18 when you [write a docker-project from scratch](https://sbt-native-packager.readthedocs.io/en/latest/formats/docker.html#write-from-scratch) like

```
lazy val `root` = (project in file("."))
  .enablePlugins(DockerPlugin)
  .settings(
    dockerCommands := Seq(
      ...
    )
  )

```
## Expected behaviour

`sbt` loads the project.

## Actual behaviour

```
[info] Loading settings for project root from build.sbt ...
[error] Reference to undefined setting:
[error]
[error]   makeBashScripts from dockerAdditionalPermissions ((com.typesafe.sbt.packager.docker.DockerPlugin.projectSettings) DockerPlugin.scala:111)

```
## Information

- What sbt-native-packager are you using
v1.3.18
- What sbt version
1.2.8
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
MacOS
- What package are you building (e.g. docker, rpm, ...)
docker

**Comment by muuki88** [comment]
This was introduced in #1201 .

We should remove the dependency on `makeBashScripts` and replace the defaults with the sbt-native-packager wide convention that things in `bin` should be executable.
