### ISSUE TITLE
javaOptions in Universal doesn't have effect in custom plugin

### ISSUE THREAD

**Issue by prophe05** [sbt/sbt-native-packager#1208]
I try to create custom plugin, that use Universal plugin,
I want to set javaOptions in Universal like:

```
override def requires = UniversalPlugin

override def projectSettings: Seq[Setting[_]] = Seq(
  javaOptions in Universal := {
      val log = sLog.value
      log.warn("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
      Seq(
        "-Dconfig.file=./conf/production.conf"
      , "-Dlogback.configurationFile=./conf/logback.xml"
      )
    }
)
```

but there is no effect.

## Expected behaviour
.ini file should be generated
log message should appear

## Actual behaviour

no result

## Information

- sbt-native-packager, 1.3.18
- sbt version - 1.2.6
- MacOS
- package is docker

**Comment by kardapoltsev** [comment]
I think an output of `sbt inspect universal:javaOptions` could be helpful

**Comment by prophe05** [comment]
sure

[info] Task: scala.collection.Seq[java.lang.String]
[info] Description:
[info]  Options passed to a new JVM when forking.
[info] Provided by:
[info]  ProjectRef(uri("file:/Users/au/workspace/ivy/account/"), "root") / Universal / javaOptions
[info] Defined at:
[info]  (com.typesafe.sbt.packager.archetypes.JavaAppPackaging.projectSettings) JavaAppPackaging.scala:45
[info] Reverse dependencies:

[info]  Universal / mappings
[info] Delegates:
[info]  Universal / javaOptions
[info]  javaOptions
[info]  ThisBuild / Universal / javaOptions
[info]  ThisBuild / javaOptions
[info]  Zero / Universal / javaOptions
[info]  Global / javaOptions
[info] Related:
[info]  Global / javaOptions

**Comment by kardapoltsev** [comment]
Could you show please how do you enable plugins in your project? What command did you run?

**Comment by prophe05** [comment]
This is simplified version of my plugin

```
import sbt._
import Keys._
import com.typesafe.sbt.SbtNativePackager._
import com.typesafe.sbt.packager.universal.UniversalPlugin

/** sets the build environment */
object BuildEnvPlugin extends AutoPlugin {

  // make sure it triggers automatically
  override def trigger = AllRequirements
  override def requires = UniversalPlugin

  override def projectSettings: Seq[Setting[_]] = Seq(
    javaOptions in Universal := {
      val log = sLog.value
      log.warn("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
      Seq(
        "-Dconfig.file=./conf/application.conf"
      , "-Dlogback.configurationFile=./conf/logback.xml"
      )
    }
  }
}
```

This is a project where I use it:

```
enablePlugins(JavaAppPackaging, DockerPlugin, BuildEnvPlugin)

lazy val root = project
	.in(file("."))
	.settings(
		name := appName
	,	version := appVersion
	,	libraryDependencies ++= appDependencies
	,	fork in run := true
	)
```

**Comment by prophe05** [comment]
`override def requires = JavaAppPackaging && UniversalPlugin`

solved the problem
