### ISSUE TITLE
Idea: package an app for homebrew?

### ISSUE THREAD

**Issue by Fristi** [sbt/sbt-native-packager#1210]
It would be convenient to
- write a CLI tool in Scala
- package them with Graal / scala-native?
- install them via homebrew

Is this hard to accomplish?

It's just an idea, shoot at it :-)

**Comment by muuki88** [comment]
Thanks @Fristi for your input.

> package them with Graal

This is already possible with native-packager :sunglasses: 

> package them with scala-native

There is an example repository demonstrating this for scala-native and scalajs with node:
https://github.com/muuki88/scala-target-examples

> install them via homebrew

This is out-of-scope for native-packager. Native-packager builds packages, but doesn't deploy them :smile:
