### ISSUE TITLE
how to question :: integration with gitlab CI

### ISSUE THREAD

**Issue by stefangweichinger** [sbt/sbt-native-packager#1213]
I am trying to write a .gitlab-ci.yml that uses "sbt docker:publish" to generate and push a new image for each new commit to the gitlab repo. And I still haven't figured out how and where to configure that.

I assume I would have to call "sbt docker" with the $CI_COMMIT_TAG variable or so, could someone please point me at some example or howto? Thanks a lot.

**Comment by muuki88** [comment]
Hi @stefangweichinger 
Thanks for your question and sorry for the late reply.

The question is how you want to version (tag) your docker file. This is generally an sbt configuration. You could use the `$CI_COMMIT_TAG` env variable in your build.sbt and set the `version` with it.

```
version := "1.0-" + sys.env("$CI_COMMIT_TAG`")
```

**Comment by stefangweichinger** [comment]
thanks @muuki88 , will try in a few days (after other projects)

**Comment by stefangweichinger** [comment]
@muuki88 :: I changed my mind and tried it quickly, "sbt docker: publish" fails with 

```
"[error] java.util.NoSuchElementException: key not found: $CI_COMMIT_TAG`". 
```


The quoting seems wrong to me, the "`" in your example is single ... even removing that single quote fails. trying to figure it out now.

**Comment by nigredo-tori** [comment]
@stefangweichinger, it should be this (without the dollar sign and the backtick):
```scala
version := "1.0-" + sys.env("CI_COMMIT_SHA")
```
Note that `CI_COMMIT_TAG` is only defined [when building tags](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html), which is probably not what you want.

There are other problems with this solution - for one, it doesn't work with local builds. These can be worked around, but I highly recommend using [sbt-dynver](https://github.com/dwijnand/sbt-dynver) instead.

**Comment by stefangweichinger** [comment]
@nigredo-tori thanks for the pointer, that sounds very helpful. Starting to play with it and solving the next issues on my way.

**Comment by stefangweichinger** [comment]
@nigredo-tori , unfortunately it bails out with:

```
[error] invalid argument "my_app:1.7.2+195-77097a7b+20190504-1512" for "-t, --tag" flag: invalid reference format
```

The format looks the same as in the README of the plugin ... maybe you can help?

**Comment by nigredo-tori** [comment]
@stefangweichinger, AFAICT, [this](https://github.com/dwijnand/sbt-dynver#docker-compatible-version-strings) should work.

**Comment by stefangweichinger** [comment]
@nigredo-tori thanks, I overread that. Forgive my newbie-questions, do I simply have to add it to build.sbt?

**Comment by nigredo-tori** [comment]
>  do I simply have to add it to build.sbt?

Yes.

**Comment by stefangweichinger** [comment]
didn't work for me, but the other lines do:

```
version in ThisBuild ~= (_.replace('+', '-'))
 dynver in ThisBuild ~= (_.replace('+', '-'))
```

**Comment by nigredo-tori** [comment]
> didn't work for me, but the other lines do:

Sorry, looks like `dynverSeparator` has not made it into a release yet. The `.replace` thing should work OK.

**Comment by stefangweichinger** [comment]
yes, it does so far. I close here, thanks

**Comment by stefangweichinger** [comment]
one more, I struggle with getting the image-name right.
I try that via setting the variable dockerRepository and it seems I am thinking too complicated.

At best I would prefer to be able to make use of the variables the GitLab CI provides, for example

`CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest`

(How) can I use such variables with `sbt docker:publish` ? maybe someone might share a pointer or an example ...

**Comment by elha-da** [comment]
Hi,

I set version of my docker image like that `sbt 'set version in Docker := "dev"' docker:publish` I think you can do same with *packageName* ...
I hope helped you

Me, when I run `sbt docker:publich` in *sbt-openjdk-8-alpine* container I get this Exception 
```
java.io.IOException: Cannot run program "docker" (in directory ..../target/docker/stage"): error=2, No such file or directory

.........

Caused by: java.io.IOException: error=2, No such file or directory

.........
```

any ideas ?

Thanks

**Comment by nigredo-tori** [comment]
@stefangweichinger, you can do something along the lines of:
```scala
Docker / dockerAlias := sys.env.getOrElse("CI_REGISTRY_IMAGE", sys.error("CI_REGISTRY_IMAGE not set"))
```
See https://www.scala-sbt.org/sbt-native-packager/formats/docker.html for more.

@elha-da, you don't have `docker` in your build container. The way `DockerPlugin` works,  you need SBT, JDK *and* Docker in your container at the same time. You would have to find or make an image like this, and run your build in that.

**Comment by elha-da** [comment]
@nigredo-tori Thanks :+1:

**Comment by nigredo-tori** [comment]
@elha-da, it seems I'm not entirely correct. Skimming through the `DockerPlugin`, it seems that everything up to the actual build should work even without `docker`. So you can do this in your SBT container:
```scala
sbt Docker/stage
```
which would build a staging directory with the `Dockerfile` and all the necessary resources. You can then pass that to the next CI stage (that would have Docker but not SBT), and build/publish the actual image manually. This way you can avoid maintaining a "chimera" image.

That said, I haven't tried this yet, and I can't be sure this will still be possible in the future SNP versions.

**Comment by stefangweichinger** [comment]
> @stefangweichinger, you can do something along the lines of:
> 
> ```scala
> dockerAlias := sys.env.getOrElse("CI_REGISTRY_IMAGE", sys.error("CI_REGISTRY_IMAGE not set"))
> ```
> 
> See https://www.scala-sbt.org/sbt-native-packager/formats/docker.html for more.
> 
> @elha-da, you don't have `docker` in your build container. The way `DockerPlugin` works, you need SBT, JDK _and_ Docker in your build environment at the same time. You would have to find or make an image like this, and run your build in that.

Thanks, will try after my vacation ...

**Comment by elha-da** [comment]
@nigredo-tori  You're right. With SBT and JDK I had to add Docker to the container. It works fine.
```
  script:
    - apk add docker
    - sbt 'set version in Docker := "dev"' docker:publish
```
Thanks a lot for your help
