### ISSUE TITLE
start/stop lifecycle of application with sbt-native-packager

### ISSUE THREAD

**Issue by MChouaiar** [sbt/sbt-native-packager#1232]
## Expected behaviour

I can run my application with the start bash, this script can run myApp in foreground and when I wish to stop it I can do it by pressing ctr+c.

## Actual behaviour

To be able to start the app on the background or at least to change the start script to be able to add for example nohup to the start commande.

## Information

- sbt-native-packager version 1.3.21
- sbt version 1.2.8
-What is your target system CentOS 7

**Comment by muuki88** [comment]
Thanks for your detailed issue @MChouaiar :smiley: 

What you are looking for are called `SystemLoaders` in sbt-native-packager. This maybe `upstart`, `systemv` or `systemd`. sbt-native-packager does and will not provide lifecylce bash scripts as these are nearly impossible to maintain given the variety of linux/unix distributions.

See [SystemLoader docs](https://sbt-native-packager.readthedocs.io/en/latest/archetypes/systemloaders.html) for more information.
