### ISSUE TITLE
Swtich to OpenJDK

### ISSUE THREAD

**Issue by jiminhsieh** [sbt/sbt-native-packager#1239]
## Expected behaviour

It's better to use OpenJDK at Travis CI.

## Actual behaviour

We use Oracle JDK at Travis CI, and it causes a build failure.

## Information
> The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

https://travis-ci.org/sbt/sbt-native-packager/jobs/545737004#L166

**Comment by muuki88** [comment]
Thanks for your issue :smile: Would you like to open a pull request and change this :sunglasses:

**Comment by jiminhsieh** [comment]
Sure. I'm glad I can help. :)

**Comment by muuki88** [comment]
Awesome :heart_eyes:  Looking forward to your pull request
