### ISSUE TITLE
Assorted JlinkPlugin improvements

### ISSUE THREAD

**Issue by nigredo-tori** [sbt/sbt-native-packager#1240]
I finally got around to using `JlinkPlugin` in my work projects, and there are some things that need work. I'll probably do these myself soon-ish, so this issue is just for documentation.

1. We need more flexible constructors in `Ignore`. I'm thinking some simple string globbing.
1. Our `jlink` call should include our classpath in `--module-path`, since there might be modular JARs there, and these are caught by our `jdeps` output parser.
1. If we have no explicit `javaHome` we use `java` from `PATH`, which is not necessarily the JVM in which SBT is running. We should use `java.home` system property instead.

**Comment by muuki88** [comment]
Thanks for opening an issue for this @nigredo-tori :heart_eyes: 
I'm happy to merge any pull requests you send :smile:
