### ISSUE TITLE
AshScriptPlugin does not add process_args() to ash-template

### ISSUE THREAD

**Issue by farico** [sbt/sbt-native-packager#1254]
## Expected behaviour

After adding enablePlugins(AshScriptPlugin) to build.sbt and running `sbt stage` a startup script is generated and it supports passing JAVA_OPTS when running app from command line:
`sh app/target/universal/stage/bin/appName -Dconfig.resource=/myconfig.conf`

## Actual behaviour

After adding enablePlugins(AshScriptPlugin) to build.sbt and running `sbt stage` a startup script is generated. Startup shell script is missing `process_args ()` command which is in JavaAppPackaging and as a result when running appliction with: `sh app/target/universal/stage/bin/appName -Dconfig.resource=/myconfig.conf`  `-Dconfig.resource` is not passed to `addJava` command.

## Information

- sbt-native-packager version: 1.4.0
- sbt version: 1.2.8
- Build system: MacOS Mojave 10.14
- Target system: CentOS 7

Overriding ash-template and adding process_args() and then calling it before `java_cmd` solves the issue.

**Comment by muuki88** [comment]
Thanks @farico for you feature request. Would you like to open a pull request for this? If yes, I'm happy to help you with any question.

**Comment by farico** [comment]
Sure, I want to work on this.

**Comment by farico** [comment]
@muuki88 is there any "getting started" guide for setting up the project?

I am trying to import it, but cannot download artifacts:
` sbt
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /Users/farico/.sbt/1.0/plugins
[info] Loading settings for project sbt-native-packager-build from plugins.sbt ...
[info] Loading project definition from /Users/farico/Projects/scala/sbt-native-packager/project
[info] Updating ProjectRef(uri("file:/Users/farico/Projects/scala/sbt-native-packager/project/"), "sbt-native-packager-build")...
[error] SERVER ERROR: Bad Gateway url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.eclipse.jetty/jetty-servlet/9.2.21.v20170120/jars/jetty-servlet.jar
[error] SERVER ERROR: Bad Gateway url=https://repo.typesafe.com/typesafe/ivy-releases/org.eclipse.jetty/jetty-security/9.2.21.v20170120/ivys/ivy.xml`

**Comment by farico** [comment]
@muuki88 I created a pull request for this feature. I've taken `process_args()` from `bash-template` and removed `process_my_args`.
