### ISSUE TITLE
Tini support for Docker images

### ISSUE THREAD

**Issue by jroper** [sbt/sbt-native-packager#1257]
Running Java as PID 1 has some issues, for example, jstack and jstat don't work when the PID of the Java process is 1. The solution to this is to not run Java as PID 1, but then you need something to run as PID 1 that will forward SIGTERM and other signals to it when the process is shut down, otherwise the process will never be shutdown cleanly, and will always be killed with a SIGKILL after a timeout - bash doesn't forward SIGTERM for example.

The best solution is to use [tini](https://github.com/krallin/tini), a very small process that acts as an init process, forwarding signals and collecting zombies. sbt-native-packager could provide a flag that enables adding and using tini.

A few notes:

* The common way of using tini is to do an ADD from the URL to download tini. This means every time the image is built, tini needs to be redownloaded, so it's checksum can be checked to determine whether the layer needs to be rerun. Not the worst thing because tini is only 10KB, but it might be better to fetch tini from another image, then that image can be cached.
* The tini signature should probably be checked, or at least that should be allowed as an option. Though this does result in more layers being built. A multistage build of course can remedy this.

**Comment by muuki88** [comment]
Thanks @jroper for the detailed feature request :smiley: 

I general I have no issues with adding this feature. Usually I start with suggesting a separate archetype plugin (like the AshScriptPlugin or LauncherPlugin) that adds the required steps to the`dockerCommands`.

>  Not the worst thing because tini is only 10KB, but it might be better to fetch tini from another image, then that image can be cached.

Agreed. Either use an image that includes tiny or we ship a version of tiny in native-packager or we use the `RUN apk add --no-cache tini` command for alpine linux distributions.

**Comment by cbrunnkvist** [comment]
I don't think added it via the distributions' package is required anymore, since [Docker already bundles `tini`](https://github.com/krallin/tini#using-tini) and sets it to PID 1 when [the `--init` param](https://docs.docker.com/engine/reference/commandline/run/) is used.

**Comment by jroper** [comment]
Perhaps might make sense to add a setting to enable the flag, eg `dockerBundleInit`, that if true, adds the `--init` flag so users don't have to manually add it to `dockerBuildOptions`. I would even go as far to say that this should default to `true`, since I don't see a reason not to use it for any Java application, and I can't imagine adding it breaking anything, except for my projects, where I've hacked the the `dockerCommands` to add tini manually:

```scala
    dockerCommands := {
      val oldCommands = dockerCommands.value
      val secondFrom  = oldCommands.indexWhere(_.makeContent.startsWith("FROM"), 1)
      // Here we add tini, an init process. The advantage of this is it makes our Java process not have a PID of 1,
      // and this means that it will respond to signals like -3 to get a thread dump, and allow taking heap dumps etc.
      // because for some reason the JVM doesn't respond to those signals when it's PID is 1.
      // The reason why we insert it after the second FROM is that sbt native-packager uses a multi stage build, to
      // keep the image size down, so we need to add it in the second stage.
      oldCommands.take(secondFrom + 1) ++ Seq(
        Cmd("ADD", "https://github.com/krallin/tini/releases/download/v0.18.0/tini", "/tini"),
        Cmd("RUN", "chmod", "+x", "/tini")
      ) ++ oldCommands.drop(secondFrom + 1)
    },
    dockerEntrypoint := Seq("/tini", "--") ++ dockerEntrypoint.value,
```

But I'm ok with that breaking, since it means I can delete all the above code.

**Comment by jroper** [comment]
Actually, of course it will break users using old versions of docker, so it's probably a bit premature to default to true.

**Comment by jroper** [comment]
Added the setting in #1438.
