### ISSUE TITLE
AshScriptPlugin generates bash scripts for periferal mains

### ISSUE THREAD

**Issue by badeball** [sbt/sbt-native-packager#1272]
## Expected behaviour

I expect all generated scripts generated by `AshScriptPlugin` to contain the shebang `#!/bin/sh`.

## Actual behaviour

I am using `AshScriptPlugin` to generate non-specific shell-scripts. My application however have multiple mains, where one is main-main. The script for invoking the main-main has correct shebang (`#!/bin/sh`), while the others have `#!/usr/bin/env bash`.

## Information

```
sbt-native-packager: 1.4.1
sbt: 1.2.8
distro: Arch Linux
```

I'm not entirely sure what I should say in regards to what package we are building. We're running `sbt stage` and packaging a Docker image ourselves, but that doesn't seem relevant to this problem.

**Comment by muuki88** [comment]
Thanks for your report :+1: 

There is a lot of working going on in #1264 . I would close this issue in favor of #1264
