### ISSUE TITLE
Remove intermediate images when using docker multi-stage builds

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt-native-packager#1277]
Each time running the docker plugin with `MultiStage` as `dockerPermissionStrategy` (which is the default) an untagged image will be created (in addition to the final image). That is just [how multi-stage works](https://docs.docker.com/develop/develop-images/multistage-build/). However, this can escalate quickly and you get many many untagged images which (usually) no one ever needs. Therefore I propose to add a config (like `autoCleanupIntermediateImages`) which makes the plugin remove those images after `docker:publish...` has finished (we can even turn it on by default).
The solution is very easy, we just need to label the created intermediate image and then remove images with this label:
https://github.com/moby/moby/issues/34513#issuecomment-389467566

I propose to add two labels, one specific one for that image, so we can remove exactly that image on build cleanup and one general label, in case autocleanup is disabled, someone can later still remove all intermediate images _generated by the docker plugin_ by just filtering for that general label.

**Comment by muuki88** [comment]
Thanks for this feature request. This duplicatse #1229
