### ISSUE TITLE
1.5.0 regression in JLinkPLugin error handling 

### ISSUE THREAD

**Issue by 412b** [sbt/sbt-native-packager#1284]
## Expected behaviour

jdeps/jlink errors are propagated to sbt

## Actual behaviour

errors are neither outputed nor propogated to sbt

## Information

- What sbt-native-packager are you using 1.5.0
- What sbt version 1.3.3
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) Ubuntu
- What package are you building (e.g. docker, rpm, ...) jlink + docker
- What version has your build tool (find out with e.g. `rpm --version`) 
- What is your target system (e.g. Ubuntu 16.04, CentOS 7) Ubuntu

commit d2a2cdc04e135d7e4bc3fa02d66e30561841bbd1 broke error handling due to ignoring the exit code completely.

**Comment by 412b** [comment]
the problem there is in the introduced `java-tool-launcher`, which doesn't handle properly errors.
I can make some PRs here and there to actually fix the things, if needed, but generally it's frustrating practice of introducing new/unstable/buggy tools without tests and stuff.

**Comment by nigredo-tori** [comment]
@412b, good catch.

> generally it's frustrating practice of introducing new/unstable/buggy tools without tests and stuff.

That's a fair point. However, java-tool-launcher was introduced to solve a specific problem (command line limit overflow), and I found no stable (or even unstable) existing tool for that. There are some tests in java-tool-launcher, but I didn't check that the return code is properly handled. I'll try and fix this soon.
