### ISSUE TITLE
docker image build not honoring API version

### ISSUE THREAD

**Issue by thurstonsand** [sbt/sbt-native-packager#1294]
## Expected behaviour

When running `docker:publishLocal`, it should honor docker's API version, not version, when determining compatibility.

## Actual behaviour

`docker:publishLocal` improperly looks at version.

## Information

* sbt-native-packager version: 1.5.2
* sbt version: 1.3.5
* ubuntu 18.04
* package: docker
* target system: alpine

I am trying to use Github Actions to build my scala project's docker image. Due to [reasons](https://github.community/t5/GitHub-Actions/What-really-is-docker-3-0-6/td-p/30752), they report a wildly different version number than CE edition (at time of writing, CE reports 19.03.5, Github Actions reports 3.0.8), but correctly report a recent API version number (at time of writing, both report 1.40)

as can be [seen in this build](https://github.com/thurstonsand/scala-hello-world/commit/06b04db7fa59bb32e882e265a16f1a1743420766/checks?check_suite_id=364229480#step:4:210), sbt-native-packager fails to build the docker image because it thinks docker cannot support multi-stage builds. But [as can be seen in this later build](https://github.com/thurstonsand/scala-hello-world/runs/354166026#step:4:212), just [hard-coding a recent version in the build.sbt](https://github.com/thurstonsand/scala-hello-world/blob/7689567457870e18ff1e45b6f4a42a85a5bf044f/build.sbt#L12) causes the build to succeed.

while hard-coding the version works, it's not a very good workaround because it will require constant maintenance as API versions get updated. also, according to the github forums (linked above), Github's docker's maintainers have no plans to change their versions to match CE edition, because API version is supposed to serve as the compatibility check, so it will not be fixed upstream.

**Comment by muuki88** [comment]
Fixed in [version 1.6.0](https://github.com/sbt/sbt-native-packager/releases/tag/v1.6.0)
