### ISSUE TITLE
docker:publishlocal use results from publishlocal?

### ISSUE THREAD

**Issue by kanishka-azimi** [sbt/sbt-native-packager#1308]
Would it be possible to provide an alternative version of docker:publishlocal which relied on ivy published artifacts instead of the compile command directly?

**Comment by muuki88** [comment]
Thanks @kanishka-azimi for your feature request.

I'm afraid this is out of scope for native packager as this messes a lot with the internal dependency resolution of sbt / ivy and now coursier.

What problem are you trying to solve with this?

**Comment by kanishka-azimi** [comment]
Thanks for considering. We have a fast way to share ivy artifacts between builds on different machines currently, but don't share published docker images. So, we hoped that docker:publishLocal would reuse publishLocal output
