### ISSUE TITLE
how to hook proguard into dist

### ISSUE THREAD

**Issue by roti** [sbt/sbt-native-packager#1309]
This is not an issue per se, but rather a question / request for documentation.

I want to integate [sbt-proguard](https://github.com/sbt/sbt-proguard) into my play project. I want to have produard execute during `dist`, after the jars were created, but before the zip file has been created.

The question is, on what task should I make `proguard` depend on? If one can find out this information with sbt commands I apologise, I am not that proficient in sbt.

**Comment by muuki88** [comment]
Hi @roti 
No worries :smile: 

The task you should depend on is `universal:packageBin` (see README.md :wink: ). That creates a zip file with the application.

I'm not familiar with proguard and how it should work, but there's a well written documentation on [task graphs](https://www.scala-sbt.org/1.x/docs/Task-Graph.html), which explains how to write tasks that depend on each other.
