### ISSUE TITLE
Release of 1.6.2 failed

### ISSUE THREAD

**Issue by note** [sbt/sbt-native-packager#1313]
## Expected behaviour

I expect 1.6.2 to appear [at bintray](https://bintray.com/sbt/sbt-plugin-releases/sbt-native-packager) but it's not there even though the release of it is on github releases page: https://github.com/sbt/sbt-native-packager/releases/tag/v1.6.2

## Actual behaviour

The artifact has not been published: https://bintray.com/sbt/sbt-plugin-releases/sbt-native-packager/1.6.2

## Information

I guess it's because of some temporary networking issues that happened in this build: https://travis-ci.org/sbt/sbt-native-packager/builds/658602141

**Comment by muuki88** [comment]
Thanks @note for the issue. I fixed that. Appearantly some dependencies weren't available at the time of the build :man_shrugging:

**Comment by note** [comment]
@muuki88 Thank you!

**Comment by muuki88** [comment]
No, thank you! :hugs:
