### ISSUE TITLE
The second FROM stage should be named

### ISSUE THREAD

**Issue by jroper** [sbt/sbt-native-packager#1315]
Currently, only the first stage of the Docker build is named, ie, as `stage0`. The second should also be named. Why? Because this allows additional stages to be easily appended to the build, that may be based on completely different images based on those stages build requirements, and then you go back to native packagers stage and copy artifacts from the additional stages. Otherwise, you need to somehow inject those stages somewhere in the middle of the build which is not at all easy to do. I would suggest that this final stage be given a well known name that never changes, eg `main`.

**Comment by jroper** [comment]
Here's an example config, here I create another stage based on `alpine/git` so that I can clone some content from a github repo, and then I copy it into my image:

```
dockerCommands := dockerCommands.value.map {
  case Cmd("FROM", unnamed) => Cmd("FROM", unnamed, "as", "main")
  case other => other
} ++ Seq(
  Cmd("FROM", "alpine/git", "as", "git"),
  Cmd("WORKDIR", "/opt/docker"),
  Cmd("RUN", "git", "clone", "https://github.com/jroper/jazzyidau.git", "blogs", "--no-checkout"),
  Cmd("FROM", "main"),
  Cmd("COPY", "--from=git", "--chown=1001", "/opt/docker/blogs", "/var/blogs"),
  Cmd("ENV", "GIT_REPO", "/var/blogs"),
)
```

As you can see, I've worked around this issue by renaming the second stage to `main`.

**Comment by muuki88** [comment]
Thanks for the feature request @jroper :hugs: . Sounds reasonable to me :smile: Would you like to open a pull request for this?
