### ISSUE TITLE
Customizing Docker image fails when container environment variables are used

### ISSUE THREAD

**Issue by ioreskovic** [sbt/sbt-native-packager#1324]
I am trying to customize the image:
```scala
    dockerCommands ++= Seq(
      ExecCmd("RUN", "cp", "$JAVA_HOME/lib/security/cacerts", "$HOME/kafka.client.truststore.jks")
    )
```

## Expected behaviour

`sbt docker:publishLocal` builds an image

## Actual behaviour

```log
[info] cp: cannot stat '$JAVA_HOME/lib/security/cacerts': No such file or directory
[info] Removing intermediate container 8b958d8ea255
[error] The command 'cp $JAVA_HOME/lib/security/cacerts $HOME/kafka.client.truststore.jks' returned a non-zero code: 1
```
## Information

- What sbt-native-packager are you using
1.7.0
- What sbt version
1.3.8
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
MaxOS Catalina 10.15.4
- What package are you building (e.g. docker, rpm, ...)
docker
- What version has your build tool (find out with e.g. `rpm --version`)
Docker version 19.03.8, build afacb8b
- What is your target system (e.g. Ubuntu 16.04, CentOS 7): 
Debian

**Comment by ppiotrow** [comment]
This is not a bug but behaviour of Docker itself. `RUN` command has two forms, only one is able to interpret variables. See the explanation in this Stackoverflow [answer](https://stackoverflow.com/a/40903689/1981559).

### Workaround
```
dockerCommands ++= Seq(
        Cmd("RUN", "echo ${JAVA_HOME}")
),
```
```
[info] Step 21/21 : RUN echo ${JAVA_HOME}
[info]  ---> Running in d03391a31013
[info] /docker-java-home/jre
```
```
[info] Step 21/21 : RUN ["echo", "${JAVA_HOME}"]
[info]  ---> Running in 9437d5ff2584
[info] ${JAVA_HOME}
```
