### ISSUE TITLE
input too long for win10

### ISSUE THREAD

**Issue by robstoll** [sbt/sbt-native-packager#1327]
## Expected behaviour
Running the generated bat file should work without modifications

## Actual behaviour
We run into the problem that `set "APP_CLASSPATH=%APP_LIB_DIR%\..."` is too long for Windows 10

## Information
A quick fix is to change this line to `set "APP_CLASSPATH=%APP_LIB_DIR%\*"` I don't know why this was not done anyway (is supported since jdk 7 I think). 
I happily create a PR if I get some pointers to implement the quick fix

- What sbt-native-packager are you using: v1.7.0 - universal 
- What sbt version 1.3.8
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) ubuntu
- What package are you building (e.g. docker, rpm, ...) universal zip
- What is your target system (e.g. Ubuntu 16.04, CentOS 7) Windows 10

**Comment by nigredo-tori** [comment]
@robstoll, [here](https://sbt-native-packager.readthedocs.io/en/latest/recipes/longclasspath.html) are a few supported ways to deal with this.

**Comment by robstoll** [comment]
ah great, I guess this should help. I'll try out `scriptClasspath := Seq("*")` and give feedback

**Comment by robstoll** [comment]
yes, works, thanks for the quick response :+1:
