### ISSUE TITLE
JavaAppPackaging enables Docker packaging

### ISSUE THREAD

**Issue by enlait** [sbt/sbt-native-packager#1337]
## Expected behaviour

According to documentation:

https://www.scala-sbt.org/sbt-native-packager/formats/docker.html#required-settings
> `enablePlugins(DockerPlugin)`

I expect that enabling docker plugin explicitly is required for enabling docker-related tasks.

## Actual behaviour

`enablePlugins(JavaAppPackaging)` is enough to make `docker:publish`

## Information

- sbt-native-packager 1.7.1
- sbt version 1.3.4

- empty project (no source code except build files) with single module
- `addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.7.1")`
- `lazy val test = (project in file(".")).enablePlugins(JavaAppPackaging)`

So whats the issue: I have a large multi-module project, with several java executable modules. Some of those are published as docker images; but not all of them. I also rely heavily on build aggregation, so that I would only trigger publish on the root and have all the stuff where it should be. Enabled-by-default publishing behaviour means that modules that were not properly configured for publishing could end up published... somehow, somewhere.

I was using sbt native packager + sbt docker, and now I'm rewriting my builds to use only native packager; and this behaviour caught me by surprise.

**Comment by enlait** [comment]
My bad, this is actually intended behaviour...
https://sbt-native-packager.readthedocs.io/en/latest/archetypes/java_app/index.html

I guess I'll have to manually disable docker publishing for individual modules.

**Comment by muuki88** [comment]
Thanks for the well done issue 😊

Yes, the behaviour is intended. Users should configure as less as possible. Josh called this "batteries included"

**Comment by enlait** [comment]
Well, I still have kind of and issue: `publishArtifact := false` doesn't prevent native packager from building an image with `publishLocal` and pushing it to remote repo with `publish`

**Comment by muuki88** [comment]
This isn't implemented in native-packager AFAIK. To override the publishing for a specific format you need to do something like

```scala
Docker / publishLocal := { },
Docker / publish := {}
```

**Comment by enlait** [comment]
Thank you, that worked.
