### ISSUE TITLE
dockerLayerGrouping in Docker  := (_ => None) does not work

### ISSUE THREAD

**Issue by DieBauer** [sbt/sbt-native-packager#1341]
## Expected behaviour

```sbt
dockerLayerGrouping in Docker  := (_ => None)
```
As described in the 1.7.0 release notes, disables layering of dependencies in `1/opt` and `2/opt`. 

## Actual behaviour

Still creates layer folders. 

There is a test in https://github.com/sbt/sbt-native-packager/blob/master/src/sbt-test/docker/test-layer-groups/changes/nolayers.sbt 

That does succeed, but that is not using the advertised `dockerLayerGrouping` but `dockerGroupLayers`. Changing this in the test to the advertised statement fails the test. 

Is this a bug in the release notes, should it become `dockerGroupLayers in Docker := PartialFunction.empty`?

## Information

- What sbt-native-packager are you using
1.7.1
- What sbt version
1.3.10
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
Ubuntu and MacOS
- What package are you building (e.g. docker, rpm, ...)
docker
- What version has your build tool (find out with e.g. `rpm --version`)
RPM version 4.14.2.1
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)
CentOS8

**Comment by muuki88** [comment]
Thanks for reporting this along with providing a fix ♥️

Would you like to open a pull request and fix the docs? This has been introduced in a last pull request, which is hard to find on my phone 😅
