### ISSUE TITLE
universal:packageBin fails on Scala 2.13.2

### ISSUE THREAD

**Issue by vasily-kirichenko** [sbt/sbt-native-packager#1342]
> [debug]         <path to file in my project>
[error] java.net.URISyntaxException: Illegal character in path at index 53: https://docs.oracle.com/en/java/javase/13/docs/api/C:\Program Files\Java\jdk-13.0.1\jmods\java.base/java/lang/Class.html
[error]         at java.base/java.net.URI$Parser.fail(URI.java:2936)
[error]         at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
[error]         at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
[error]         at java.base/java.net.URI$Parser.parse(URI.java:3137)
[error]         at java.base/java.net.URI.<init>(URI.java:623)
[error]         at scala.tools.nsc.doc.html.HtmlPage.linkToHtml(HtmlPage.scala:145)
[error]         at scala.tools.nsc.doc.html.HtmlPage.toLinksIn$1(HtmlPage.scala:202)
[error]         at scala.tools.nsc.doc.html.HtmlPage.toLinksOut$1(HtmlPage.scala:194)
[error]         at scala.tools.nsc.doc.html.HtmlPage.typeToHtml(HtmlPage.scala:205)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.inside$1(Entity.scala:885)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.signature(Entity.scala:910)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.signature$(Entity.scala:799)
[error]         at scala.tools.nsc.doc.html.page.EntityPage$$anon$1.signature(Entity.scala:1033)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.memberToHtml(Entity.scala:378)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.memberToHtml$(Entity.scala:357)
[error]         at scala.tools.nsc.doc.html.page.EntityPage$$anon$1.memberToHtml(Entity.scala:1033)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.$anonfun$memsDiv$1(Entity.scala:355)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.memsDiv(Entity.scala:355)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.memsDiv$(Entity.scala:353)
[error]         at scala.tools.nsc.doc.html.page.EntityPage$$anon$1.memsDiv(Entity.scala:1033)
[error]         at scala.tools.nsc.doc.html.page.EntityPage.$init$(Entity.scala:309)
[error]         at scala.tools.nsc.doc.html.page.EntityPage$$anon$1.<init>(Entity.scala:1033)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.writeTemplate$1(HtmlFactory.scala:167)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.writeTemplate$1(HtmlFactory.scala:169)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.writeTemplate$1(HtmlFactory.scala:169)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.writeTemplate$1(HtmlFactory.scala:169)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.writeTemplate$1(HtmlFactory.scala:169)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.writeTemplates(HtmlFactory.scala:169)
[error]         at scala.tools.nsc.doc.html.HtmlFactory.generate(HtmlFactory.scala:155)
[error]         at scala.tools.nsc.doc.html.Doclet.generateImpl(Doclet.scala:30)
[error]         at scala.tools.nsc.doc.doclet.Generator.generate(Generator.scala:35)
[error]         at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:139)
[error]         at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:142)
[error]         at xsbt.Runner.run(ScaladocInterface.scala:34)
[error]         at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error]         at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error]         at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error]         at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1635)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:830)

However, it works OK on Scala 2.13.1

Windows 10 x64.

If the bug is hard to fix, I'd happily turned off the documentation compilation, but I don't know how.

**Comment by muuki88** [comment]
Thanks for the bug report. This is not really an issue, but a long standing point with sbt and the scala doc.

There are multiple ways to turn off doc compilation, which are documented publicly IIRC one was

```scala
Compile / packageBin / doc := {}
```

**Comment by vasily-kirichenko** [comment]
@muuki88 `Compile / packageBin / doc := {}` does not compile:

![image](https://user-images.githubusercontent.com/873919/82700219-7159b580-9c76-11ea-8f62-752abdc8ddf1.png)

**Comment by muuki88** [comment]
Then I remembered incorrectly 😅 but somewhere along this line it is.

**Comment by danwerner** [comment]
In case somebody finds this old issue in a Google search, like I did, this is what worked for me:
```sbt
    Compile / packageDoc / publishArtifact := false,
    Test / packageDoc / publishArtifact    := false,
```
