### ISSUE TITLE
Progress output while running native-image

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt-native-packager#1345]
## Expected behaviour

I'm using `GraalVMNativeImagePlugin` and when running `sbt graalvm-native-image:packageBin` I would like to see progress output while the native-image linker is running similar to when I run `native-image` directly from the command-line. It would be nice to see this output as soon as it appears
```
[info] [fastpass:4932]    classlist:  19,351.15 ms,  1.18 GB
[info] [fastpass:4932]        (cap):   1,183.22 ms,  1.18 GB
[info] [fastpass:4932]        setup:   2,821.39 ms,  1.18 GB
...
```

## Actual behaviour

There is no progress output from native-image while `sbt graalvm-native-image:packageBin`  is running, which can take several minutes to complete.

I looked at the implementation it uses `Process.!(streams.value)`and was surprised this does not produce the expected output. Is it maybe necessary to flush somehow?

https://github.com/sbt/sbt-native-packager/blob/7c28a1f70957a46ff9899549d1f88c1a17ef7343/src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImagePlugin.scala#L113

## Information

- What sbt-native-packager are you using: 1.7.2
- What sbt version: 1.3.10
- What is your build system: macOS
- What package are you building: native image on my computer with GraalVM 20.1.0 (https://sbt-native-packager.readthedocs.io/en/stable/formats/graalvm-native-image.html)
- What is your target system: macOS

**Comment by muuki88** [comment]
Thanks @olafurpg for the detailed report 😊

I remember that sbt-scripted had some log buffering enabled that you needed to disable. Maybe this is some similar behaviour. 🤔

What I'm trying to say is that this might be a configuration thing in sbt. However we had a similar report in the gitter channel.
