### ISSUE TITLE
Security Issue - commons-compress 1.18

### ISSUE THREAD

**Issue by saaryehudai** [sbt/sbt-native-packager#1347]
## Information
`snyk` has marked `commons-compress 1.18` as a high-security risk.
Details: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-460507

We are using an old version of `sbt-native-manager`, but I see the current version still uses the marked version.

**Comment by muuki88** [comment]
Thanks a lot for the issue report @saaryehudai 

Would you like to open a pull request for this? I don't see this as an issue for native-packager as the developer building the package has any interest in ddosing his/her own machine or the CI, but keeping dependencies up-to-date is always a good thing.
