### ISSUE TITLE
Version '1'? New SBT capability?

### ISSUE THREAD

**Issue by ScalaWilliam** [sbt/sbt-native-packager#1356]
Hi @muuki88 ,

Just noticed this in the README:

![image](https://user-images.githubusercontent.com/2464813/89100693-043e6b00-d3f1-11ea-916b-ca8880134996.png)

Surprisingly it does work but I am uncertain if this makes sense. Is there some new syntax that allows you to map from version "1" to latest "1.7.4"? If this looks wrong, I am happy to make a PR to fix that.

Original commit to do this change is here https://github.com/sbt/sbt-native-packager/commit/d38caf6ef8b2aa2b8461a9b5697785e6914ca87c

**Comment by muuki88** [comment]
Hi @ScalaWilliam 😊

Thanks for noticing. There must be something wrong in the code updating this. I'm very happy to merge a pull request 🥰
