### ISSUE TITLE
Producing Multiple Unique JARs from a Single Source Directory

### ISSUE THREAD

**Issue by mvillafuertem** [sbt/sbt-native-packager#1359]
```
- my-app-project
      - src/main/scala
          - api/controller.scala 
          - model/domain.scala
          - utils/util.scala
```

I need this result. 

```
my-app-0.1.0.jar
my-app-api-0.1.0.jar
my-app-model-0.1.0.jar
my-app-utils-0.1.0.jar
```

Is this possible? Thanks!

**Comment by muuki88** [comment]
Hi @mvillafuertem 

Thanks for your question :smiley: Can you please add a bit more information on what you already tried and what you are trying to achieve?

Native packager builds distributions and not jars. [The output formats are zip, dmg, rpm, deb or docker images](https://sbt-native-packager.readthedocs.io/en/latest/formats/index.html). If you have [multiple main classes you get multiple bash / bat scripts](https://sbt-native-packager.readthedocs.io/en/latest/archetypes/java_app/index.html#multiple-applications) to run them.

**Comment by mvillafuertem** [comment]
Ouch! 🤦🏻‍♂️ My fault sorry, Thanks for your answer. This question should be for sbt-assembly...
