### ISSUE TITLE
Reference to undefined setting: Universal / mappings from Universal / mappings (rootProject/publish.sbt)

### ISSUE THREAD

**Issue by mealbarracin10** [sbt/sbt-native-packager#1360]
## Expected behaviour

error in upgrading scala project to  2.8.0

Main Pluging.sbt file 

mappings in Universal += { file("conf/custom.sh") -> "bin/start-custom.sh" }.    

When run sbt reload 

 Reference to undefined setting: 
[error] 
[error]   Universal / mappings from Universal / RoothProject/publish.sbt)

## Information

- sbt-native-packager: 1.7.4
- Sbt Version : 1.2.8
- Operative System: macOS
- docker
- Ubuntu 16.04,

**Comment by muuki88** [comment]
Hi @mealbarracin10 

Thanks for your question. I cannot quite follow what version you are upgrading where?

Can you share the complete build sbt? It seems that there's a configuration error in your build config.
