### ISSUE TITLE
LinuxPlugin: Config files are not set as config if have execute permission

### ISSUE THREAD

**Issue by salehdeh76** [sbt/sbt-native-packager#1382]
## Expected behaviour

`sbt debian:packageBin` should set meta "config" flag (in `linuxPackageMappings`) for all config files (i.e. those under "conf" directory) so they will be put in debian conffiles (and for other usages of the flag). Obviously the permission of files should not affect this.

## Actual behaviour
`sbt debian:packageBin` will not put files under "conf" directory if they have execute permission set. So the conffiles does not contain them and this will cause problem when using that deb for upgrade purposes. This problem specially will occur when using Windows platform to generate packages (by using JDeb for example) because Windows has no notion of that permissions and by default all files are "777".

The issue is because of [this line](https://github.com/sbt/sbt-native-packager/blob/75eb8f1c1f955bb714d31a9e09a3442679255a29/src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala#L220). The files are categorized sequentially in "executable", "doc", ... . But the order is wrong. Any file under conf should not be executable.

## Information

- What sbt-native-packager are you using
  v1.8.0-RC14

- What sbt version

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
  Ubuntu and Windows (but issue is generic)

- What package are you building (e.g. docker, rpm, ...)
  debian

- What version has your build tool (find out with e.g. `rpm --version`)
  dpkg 1.17.5

- What is your target system (e.g. Ubuntu 16.04, CentOS 7)
Debian

**Comment by muuki88** [comment]
Thanks @salehdeh76 for the detailed issue :smiley: 

Filtering all conf files from the `binaries` mapping would solve this issue if I understand this right? Would you like to open a pull request for this?

**Comment by muuki88** [comment]
Thanks for the detailed issue and the PR :heart:  in #1383
