### ISSUE TITLE
Documentation not updated for makeBashScript(s)

### ISSUE THREAD

**Issue by qiujiangkun** [sbt/sbt-native-packager#1398]
Currently, the documentation at https://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/index.html (version 1.8) mentioned `makeBashScript`, but the actual command is `makeBashScripts` (version 1.7.4).

Will this be changed in sbt-native-packager 1.8?
Where can I see the documentation for 1.7?

**Comment by muuki88** [comment]
Fixed in #1396
