### ISSUE TITLE
[Question] support 2.13 ?

### ISSUE THREAD

**Issue by Poulpinounette** [sbt/sbt-native-packager#1406]
assembly supports version 2.13.x for creating fat jars? 

After testing it's impossible to get a correct jar, dependencies that screw up for no reason.

I spent a week looking for a solution, I switched back to 2.12 and it works :/

**Comment by ScalaWilliam** [comment]
Can you share a reproducible case on GitHub @Poulpinounette

**Comment by Poulpinounette** [comment]
i will try

**Comment by Poulpinounette** [comment]
by testing with the same project base, I do not have this bug, it is very disconcerting ...

**Comment by Poulpinounette** [comment]
Now, its work.

i have just re-change 2.12.12 to 2.13 and its work. but before clearly not work....
