### ISSUE TITLE
tag the publishLocal task as Disk/Network for concurrent control

### ISSUE THREAD

**Issue by ykoehler** [sbt/sbt-native-packager#1411]
https://www.scala-sbt.org/1.x/docs/Parallel-Execution.html

as explained here, task that talks to the docker deamon should be tagged a Disk or Network (or both) type of activity so that concurrency limits can be set based on the type of activity.

def myCompileTask = Def.task { ... } tag(Tags.Disk, Tags.Network)

or maybe create a new tag custom "docker"

**Comment by muuki88** [comment]
Thanks for opening this issue :smile: 

They are already tagged:

https://github.com/sbt/sbt-native-packager/blob/2268343362812bbca6e49f15e05586821a101bc7/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L256

https://github.com/sbt/sbt-native-packager/blob/2268343362812bbca6e49f15e05586821a101bc7/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L267
