### ISSUE TITLE
Cannot install / docs not up to date

### ISSUE THREAD

**Issue by cbrunnkvist** [sbt/sbt-native-packager#1428]
## Expected behaviour

`addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.9.1")` (according to [current docs])

## Actual behaviour

Plugin cannot be installed, after #1419 we needs to use a different `groupId`? Is it "io.github.sbt.sbt-native-packager"? Or "com.github.sbt" now?

[current docs]: https://www.scala-sbt.org/sbt-native-packager/gettingstarted.html#setup

**Comment by muuki88** [comment]
Thanks :heart:  Fixed

**Comment by adamthompson93** [comment]
The documentation on the [official website](https://www.scala-sbt.org/sbt-native-packager/gettingstarted.html#setup) is still incorrect.
