### ISSUE TITLE
JlinkPlugin misses jdk.unsupported

### ISSUE THREAD

**Issue by Martomate** [sbt/sbt-native-packager#1446]
## Expected behaviour

If a project uses the `jdk.unsupported` module (e.g. the `sun.misc.Unsafe` class) that module should be included in the JRE created by the JlinkPlugin.

## Actual behaviour

The `jdk.unsupported` module is not included in the JRE.

I have found that the `jdeps` command returns the `jdk.unsupported` module, but the JlinkPlugin misses it. This happens [here](https://github.com/sbt/sbt-native-packager/blob/bfc7fb67facb3f1c94c75a88b45c47c00ffe4ed5/src/main/scala/com/typesafe/sbt/packager/archetypes/jlink/JlinkPlugin.scala#L264) in `JlinkPlugin.scala`.

This is caused by the `jdeps` command returning `JDK internal API (jdk.unsupported)` but the JlinkPlugin expects only a module name. It only seems to occur in the three-column rows, and in all other places the module name is printed without any extra information. Here is an example:

```
   requires mandated java.base (@11-ea)
   requires java.desktop (@11-ea)
   requires java.xml (@11-ea)
   requires transitive javafx.base
   requires jdk.unsupported (@11-ea)
javafx.graphics -> java.base
javafx.graphics -> java.desktop
javafx.graphics -> java.xml
javafx.graphics -> javafx.base
javafx.graphics -> jdk.unsupported
```
```
   com.sun.marlin                                     -> java.util.concurrent.atomic                        java.base
   com.sun.marlin                                     -> sun.misc                                           JDK internal API (jdk.unsupported)
   com.sun.marlin.stats                               -> com.sun.marlin.stats                               javafx.graphics
```

## Information

- What sbt-native-packager are you using - 1.9.3
- What sbt version - 1.5.5
- What is your build system - Ubuntu
- What package are you building - Universal
- What is your target system - Ubuntu

**Comment by muuki88** [comment]
Thanks a lot for this very well researched bug report


I have no experience with jlink, but happy help with a pull request to fix this 😊

**Comment by 412b** [comment]
@muuki88 I've got some dusty code for that issue and general optimizations for deps processing in JLinkPlugin
I will create PR shortly
