### ISSUE TITLE
DockerPlugin doesn't work with multiple main classes by default

### ISSUE THREAD

**Issue by kubukoz** [sbt/sbt-native-packager#1491]
## Expected behaviour

`sbt Docker/publishLocal` produces a runnable image or fails at build time in the presence of multiple main classes

## Actual behaviour

The image fails startup

## Information

- What sbt-native-packager are you using: 1.9.7
- What sbt version: 1.6.1
- What is your build system: sbt
- What package are you building docker
- What version has your build tool: ???
- What is your target system: macOS, also confirmed on Linux

## Reproduction

1. Make an sbt project using NP:

```scala
val root = project
  .in(file("."))
  .enablePlugins(JavaAppPackaging)
  .enablePlugins(DockerPlugin)
```

2. Add multiple main classes

```scala
object Foo extends App
object Bar extends App
```

3. `sbt Docker/publishLocal`

4. Try to run the generated image:

```
$ docker run --rm -it sha256:46c53661a82306d95dbd9e9db28fa7e98d7f5ae4553d5c0091f0f71dfdbb8c97
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/opt/docker/bin/root": stat /opt/docker/bin/root: no such file or directory: unknown.
```

`Docker/dockerEntrypoint` points to `/opt/docker/bin/root`, and setting it to a specific binary helps. Clearly the names are set by a heuristic documented [in the docs](https://sbt-native-packager.readthedocs.io/en/stable/archetypes/java_app/index.html?highlight=multiple#multiple-start-scripts).

However, I don't think the Docker plugin's behavior is intuitive, because if you add a new main class to a working build you'll suddenly be unable to run the images.

Maybe `Docker/stage` should fail if there are many main classes and none of them is explicitly chosen (by `Docker/mainClass` or `dockerEntrypoint`, I'm not sure)?

**Comment by muuki88** [comment]
Thanks for your patience. This is hitting more and more users now. Would you like to open a PR to fix this?

The `executableScriptName` is set here initially

https://github.com/sbt/sbt-native-packager/blob/2268343362812bbca6e49f15e05586821a101bc7/src/main/scala/com/typesafe/sbt/PackagerPlugin.scala#L99

and without any scoping used here

https://github.com/sbt/sbt-native-packager/blob/2268343362812bbca6e49f15e05586821a101bc7/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L129

An option would be to keep this a docker thing. And add

```sbt
Docker / executableScriptName := normalizedName.value
dockerEntrypoint := Seq(s"${(defaultLinuxInstallLocation in Docker).value}/bin/${(Docker / executableScriptName).value}"),
```

and remove the `executableScriptName` entry here

https://github.com/sbt/sbt-native-packager/blob/2268343362812bbca6e49f15e05586821a101bc7/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L281

**Comment by kubukoz** [comment]
I'll see when I have the time to dig into it and properly test the outcome, but if someone wants to pick it up earlier feel free to do so!

**Comment by muuki88** [comment]
@kubukoz I was able to work on this :smile: Release is out

**Comment by kubukoz** [comment]
thanks, I'm not getting a lot of time with SNP these days :)

**Comment by muuki88** [comment]
me neither :sweat:
