### ISSUE TITLE
Any solutions for Shading dependencies? 

### ISSUE THREAD

**Issue by kell18** [sbt/sbt-native-packager#1511]
Hi!

Thank you for the great plugin! 

Is there any way to do Shading  similar to one that is implemented in [Sbt-assembly](https://github.com/sbt/sbt-assembly#shading)? Or maybe you know some workarounds?

**Comment by muuki88** [comment]
Hi and thanks ☺️

No, not really. Native packager puts jars separately in the classpath. This makes it rather tricky to do any sort of shading.

However you can use sbt-assembly and native packager together 😅
