### ISSUE TITLE
Update to scala-xml 2

### ISSUE THREAD

**Issue by kryptt** [sbt/sbt-native-packager#1513]
More and more sbt plugins are moving to scala-xml 2, for example now I've been blocked from upgrading sbt-scoverage

See:
https://github.com/scoverage/scalac-scoverage-plugin/pull/488
https://github.com/scoverage/sbt-scoverage/issues/439
https://github.com/fthomas/refined/pull/1098

**Comment by muuki88** [comment]
IIRC there was already an attempt made, but rolled back due to other incompatibilities.

**Comment by SethTisue** [comment]
I suggest you bite this bullet. It's nearly unheard of for the upgrade to actually cause a problem. The major version number bump frightens people, but the removed things were already deprecated and rarely used anyway.,

**Comment by SethTisue** [comment]
I don't see any previous upgrade attempt other than https://github.com/sbt/sbt-native-packager/pull/1454

**Comment by armanbilge** [comment]
Well I did the obvious thing and CI seems fine. https://github.com/sbt/sbt-native-packager/pull/1514

**Comment by muuki88** [comment]
Thanks for all the input 😄 I'll merged the PR and will release next week.

**Comment by mkurz** [comment]
IMHO next time such an major version bump from like from scala-xml 1 to 2 should not be done in a patch release... People start a lot to open issues and ask in chats about the whole scala-xml upgrade mess. 
Such changes should be coordinated better next time... Like someone should open pull requests at once in all major plugins and libraries and they all should release new versions within a couple of days....
Also, like I am asking myself, why did get scala-xml bumped to 2 but not scala-parser-combinators? It's just random. We will have the same mess soon with that library...
