### ISSUE TITLE
Option to enable Docker buildkit

### ISSUE THREAD

**Issue by jroper** [sbt/sbt-native-packager#1518]
Docker buildkit can be enabled by setting the environment variable `DOCKER_BUILDKIT` to `1`. Sometimes, someone might be using buildkit features as part of the build, and need this to always be enabled. It would be great if sbt native packager could provide an option to enabled this automatically (ie, by setting that environment variable when it runs docker).

**Comment by muuki88** [comment]
That sounds useful ☺️ happy to merge a PR 🤗
