### ISSUE TITLE
Jlink archetype does not work on windows, caused by path separator

### ISSUE THREAD

**Issue by GithubUser8080** [sbt/sbt-native-packager#1521]
## Expected behaviour

When running packageBin on windows, jlink should be called successfully

## Actual behaviour

Jlink throws an error

Illegal char <:> at index ..
This is caused by the paths being joined by ":" instead of ";" ,  when provided to --module-path, as far as i understand

## Information

sbt-native-packager version: latest
sbt version: 1.6
system: Windows

**Comment by Rojods** [comment]
I was just about to put up this issue :). Luckily I also submitted a patch to fix this problem with #1522 .
