### ISSUE TITLE
Packages are not available

### ISSUE THREAD

**Issue by KannarFr** [sbt/sbt-native-packager#1541]
Looks like the repository which stores the packages is not available. Same issue on sbt/sbt-revolver & sbt-javaagent.

https://github.com/spray/sbt-revolver/issues/112

**Comment by jeremycarroll** [comment]
Specifically for me the files link from https://index.scala-lang.org/sbt/sbt-native-packager/artifacts/sbt-native-packager/1.3.4 which I note has the old `Group ID:com.typesafe.sbt`

**Comment by muuki88** [comment]
I guess they all went away with the sunset of bintray. The old packages haven't been released as I don't have the time to do this. I recommend upgrading to 1.9.x 😊

**Comment by muuki88** [comment]
Related https://github.com/sbt/sbt/issues/7202

**Comment by bigpick** [comment]
> I guess they all went away with the sunset of bintray. The old packages haven't been released as I don't have the time to do this. I recommend upgrading to 1.9.x 😊

https://scala.jfrog.io/ui/native/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/ only has up to `1.8.1` though?
