### ISSUE TITLE
Changes Not Being Propagated to Image

### ISSUE THREAD

**Issue by AlexWeinstein92** [sbt/sbt-native-packager#1550]
## Expected behaviour

`sbt "docker / publishLocal"` should produce an image that has the changes I've made reflected in its responses.

## Actual behaviour

Although I have commented out the following in a `trait` which I am no longer even using in my only `Impl` that is created in `Main`, `EntityOne ` appears in my logs
```
//logRequestResult("EntityOne") {
//  pathPrefix("entityOne") {
//      ...
//  }
//}
```

the logs looks something like:

```
20:28:56.128 [Gateway-ActorSystem-akka.actor.default-dispatcher-12] DEBUG akka.actor.ActorSystemImpl -- EntityOne: Response for
  Request : [REDACTED}
  Response: Rejected(List())
20:28:56.128 [Gateway-ActorSystem-akka.actor.default-dispatcher-12] DEBUG akka.actor.ActorSystemImpl -- EntityTwo: Response for
  Request : [REDACTED}
  Response: Rejected(List())
```

I have also added a new `EntityThree` trait that also uses `logRequestResult`, and this one does not show up in my image's responses even though it has been added to `Main`. I have a gatling suite that is trying to hit routes on `EntityThree` but no matter what I get these rejection responses where no `EntityThree` appears in the logs.

I have rebuilt this image about 15 times in the last work day, trying different way to get it into my kubernetes (microk8s) local pod to make sure it was really the new image that was at fault. Today I also tried using `curl` directly from a Docker container of the new image to itself and got the same rejected response logs repeatedly. I have tried cleaning all target folders, and other things like that to make sure there is no caching issue, but still no luck.

## Information

- What sbt-native-packager are you using - `1.9.16`
- What sbt version - `1.9.3`
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ) - Macbook Pro 2021 (M1)
- What package are you building (e.g. docker, rpm, ...) - docker
- What version has your build tool (find out with e.g. `rpm --version`) - not sure
- What is your target system (e.g. Ubuntu 16.04, CentOS 7) -  local

**Comment by AlexWeinstein92** [comment]
This was really an error with how I was importing images. Closed.

**Comment by muuki88** [comment]
Thanks for tidying up your issue ❤️🙏
