### ISSUE TITLE
Let scala-steward visit that repo?

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt-native-packager#1568]
Any reason why scala-steward does not visit this repo?
It uses some outdated libraries, e.g.
- #1566

I can't find it in https://github.com/VirtusLab/scala-steward-repos/blob/main/repos-github.md
Should I add it?

/cc @muuki88

**Comment by muuki88** [comment]
Sure thing @mkurz 🥰

**Comment by mkurz** [comment]
Mayb you can add your thumbs up to 
- https://github.com/VirtusLab/scala-steward-repos/pull/344

because I am not an owner/admin of this repo here.
