### ISSUE TITLE
sbt-native-packager fails with dpkg-deb error

### ISSUE THREAD

**Issue by luukjansen** [sbt/sbt-native-packager#1569]
## Expected behaviour

Debian / packageBin to generate the Debian pkg file

## Actual behaviour

An error:
[info] Building debian package with native implementation
[error] dpkg-deb: error: --build takes at most two arguments
[error] Type dpkg-deb --help for help about manipulating *.deb files;
[error] Type dpkg --help for help about installing and deinstalling packages.
[error] stack trace is suppressed; run last Debian / packageBin for the full output
[error] (Debian / packageBin) Failure packaging debian file.  Exit code: 2
[error] Total time: 1 s, completed 19 Feb 2024, 16:40:37

## Information

- What sbt-native-packager are you using: 1.9.16
- What sbt version: 1.9.8
- What is your build system: MacOS
- What package are you building: deb (Debian)
- What version has your build tool: Debian 'dpkg-deb' package archive backend version 1.18.3 (darwin-amd64).
- What is your target system: Ubuntu 18.04

**Comment by dwickern** [comment]
You're using dpkg version 1.18.3 which is from 2015. Could you try with a more recent version?

**Comment by luukjansen** [comment]
I checked and there was an old version on the system, which might be used. I don't know if there is a way to check which version sbt is using. Is there an option to get more verbose information?

The only version I have now is:
Debian 'dpkg-deb' package archive backend version 1.22.4 (darwin-arm64).

I still get the same result.

**Comment by luukjansen** [comment]
I found the problem. When putting in the required information like maintainer I changed the name and put a space in (assuming it was the name as displayed). That caused a space in the build path, and hence two arguments.

**Comment by muuki88** [comment]
Thanks @luukjansen for sharing.

Awesome to see you are still around @dwickern :heart: :heart:
