### ISSUE TITLE
sbt-native-packager/formats/universal.html#filter-remove-mappings is stale

### ISSUE THREAD

**Issue by jsoref** [sbt/sbt-native-packager#1589]
## Expected behaviour

https://github.com/sbt/sbt-native-packager/blob/master/src/sphinx/formats/universal.rst#filterremove-mappings should be visible  as https://www.scala-sbt.org/sbt-native-packager/formats/universal.html#filter-remove-mappings

## Actual behaviour

Stale version of content using deprecated syntax is shown

## Information

- What sbt-native-packager are you using
- What sbt version
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
- What package are you building (e.g. docker, rpm, ...)
- What version has your build tool (find out with e.g. `rpm --version`)
- What is your target system (e.g. Ubuntu 16.04, CentOS 7)

**Comment by dwickern** [comment]
Fixed by #1619, docs should be up-to-date now
