### ISSUE TITLE
pid file creation as non-root

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#164]
I just upgrade a project from **0.7.0-M1** to **0.7.0-M3**, which means the default `appUser` is now `normalizedName`.

First of all I had to `chown -R myapp:myapp /usr/share/myapp` 
I tried to start the app with `sudo service myapp start` which fails with error

```
Exception in thread "main" java.io.FileNotFoundException: 
/var/run/myapp.pid (Permission denied)
```
### Possible solution

I looked inside the directory and found that every non-root pid file was inside a folder which is owned by the user. So creating `/var/run/myapp` as the "pid-folder" seems a already used solution.

**Comment by shijinkui** [comment]
simple question: where is the pid when using JavaAppPackaging?

**Comment by muuki88** [comment]
Simple answer: nowhere. PIDs are only generated when you use the server archetype.

The JavaAppPackaging type online provides start scripts.

**Comment by shijinkui** [comment]
@muuki88  i don't think pid is only needed by server archetype.
if JavaAppPackaging provide a stop script, that will be perfact.

**Comment by hepin1989** [comment]
I have to generate the pid myself at application runtime for the JavaAppPackaging.
as we always run application as ```nohub ./application &```
I think a RUNNINGPID and a stop script would be handy too.

**Comment by muuki88** [comment]
I think this is out of scope for the `JavaAppPackaging` archetype. If you start your application manually you with `nohub` you will have to deal with it yourself. This what the playframework does.

I recommend using the server archetype as you get all these facilities for free. You can start/stop your application with a simple `sudo service my-app start`. If your system uses `Systemd`  then you have very sophisticated  control.

**Comment by hepin1989** [comment]
@muuki88 thank you,I know that with the server archetype would be good,and the problem currently is that ,we need restart the server and then redeploy it sometime,so we just go straight with the ```JavaAppPackaging```.
the problem is that when we run multiply app on the same box,and them always kill it via ```killall java```,and then miskill some others .so I think the ```server archetype``` would be great there.

I have only one question.with the ```server archetype```,is it easily that I upgrade the app?or override it?
thanks.,and for the pid fancy,does that was provided by the underly system or by the ```sbt-native-packager```.

**Comment by shijinkui** [comment]
@hepin1989  +1

@muuki88  thanks. Indeed we need JavaAppPackaging providing pid and stopping script.
sbt-native-packager cannot force user to user server archetype.

**Comment by muuki88** [comment]
@hepin1989 
> is it easily that I upgrade the app

Yes. You just replace `JavaAppPackaging` with `JavaServerAppPackaging`. Done. Depending on your operating system you may need to tweak the system loader. See [the documentation](http://www.scala-sbt.org/sbt-native-packager/archetypes/java_server/index.html) for more details.

E.g.
```
import com.typesafe.sbt.packager.archetypes.ServerLoader.{SystemV, Upstart, Systemd}
// for Debian, Ubuntu
serverLoading in Debian := Systemd // if you have Ubuntu 15.04 for example
// for RHEL, CentOS, Fedora
serverLoading in Rpm := Systemd // if you want Fedora to use Systemd instead of SystemV
```

@shijinkui 
>  cannot force user to user server archetype

No, but the server archetype is exactly the solution to  your problem. The start script is intended to be executed by a application system that manages these applications, e.g.

- SystemV
- Upstart
- Systemd

If you don't install on the package level, then the `JavaAppPackaging` type is sufficient enough when you use for example a docker container. Or you write your own 

- Aurora start script
- Amazon AWS script
- ...

SBT Native Packager will never provide facilities to manage applications on your system, because we support such a variety of systems that it's hard enough to make things work with existing things. I highly recommend you to use onboard facilities for application life-cycle management (systemd, systemv, upstart).

**Comment by hepin1989** [comment]
@muuki88 thanks,I means is it easily for me to upgrade a app only via ```dpkg -install newVersion.deb```?.

**Comment by muuki88** [comment]
Yes :)

**Comment by shijinkui** [comment]
In our company, docker is not recommended. Most of applications are managed by tomcat or other web container.  For breaking away from tomcat, i choose scala, netty and Play. 
But the deploy mode, i need manage app for myself and don't care any os type. That's why need pid and stop script. we have ourselves' package and deploy management system.

anyway, u cant't give someone only one way or bind someone to other framework tightly.

so, pid and stop script maybe choosed by use optionally.
:100:

**Comment by muuki88** [comment]
I think there are a few points you are confusing. I try to explain things in more detail so you get a better feeling of what I mean when I say "sbt native packager will not provide an application lifecycle management".

### JavaAppPackaging and JavaServerAppPackaging

`JavaServerAppPackaging` is not something different as `JavaAppPackaging`. In Fact `JavaServerAppPackging` [depends](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala#L31) on `JavaAppPackaging` and adds the following functionality for `deb` and `rpm` packagaes

- default folders
-- `/var/run/<appname>` for PIDs
-- `/var/log//<appname>` for logs
- daemon user and group
- maintainer scripts that
-- register your app as a service with the configured SystemLoader (SystemV, Upstart, Systemd)
-- start app
-- stop app before unstinall / upgrade

You see that this features have only one purpose: _managing application lifecycle_ on a server.

> anyway, u cant't give someone only one way or bind someone to other framework tightly.

With `JavaAppPackaging` you can choose any binding, e.g. some implemented AWS Beanstalk Bindings in #632. You have a start script and build around your application lifecycle management.

`JavaServerAppPackaging` gives you three standard lifecycle managements for free: `SystemV`, `Upstart` and `Systemd`. These are three bindings, not one. And you have to do nothing in order to use them.

> i need manage app for myself and don't care any os type

You can still package `zip`, `tar` etc. files. The `JavaServerAppPackaging` won't altering. Currently native-packager only supports `deb` and `rpm` within the server archetype. 

### Implement a stop script

Furthermore, what does it mean to implement a `stop` script and `manage` your application yourself.

1. Find a OS independent place to put your PIDs. That place must be readable and writeable
2. Make sure the application isn't running yet
3. Check the status of the app

all with bash/bat foo which heavily relies on your OS you are running on. You can not "not care" about your OS you are running your stuff on. Providing a stop script means implementing an application lifecycle management. It is hard enough to keep `SystemV`, `Systemd` and `Upstart` running on all major linux distributions. Implementing your own is a) not a good idea b) not part of _packaging_ plugin.

> so, pid and stop script maybe choosed by use optionally

If you use the `JavaAppPackaging` you can implement your own application lifecycle if you think that's a good idea. SBT Native Packager will only provide hooks into existing systems. As an example we could implement a binding for `Aurora` to start applications easily on an Aurora cluster, but we would never implement anything like Aurora. That is out of scope.

I hope you get the point that `packaging` and `running` are two separate concerns. Native-packager gives you a package that any system should be able to execute. Managing your application state is (and should be) done by other systems. SBT native packager provides at most bindings ( in form of configuration files, scripts and sys calls ) to these systems as we do for `SystemV`, `Systemd` and `Upstart`.

**Comment by shijinkui** [comment]
@muuki88  Thank for your detail reply with patience. 
Stop script is not sbt-native-packager's responsibility. Maybe sbt-native-packager focus on `native` more.
Let's step back, can sbt-native-packager write the pid to the defined location file?

**Comment by muuki88** [comment]
@shijinkui you're welcome :) This is really an important topic as this about the scope of sbt-native-packager. 

> can sbt-native-packager write the pid to the defined location file

You can use `bashScriptExtraDefines` setting to do what ever you want in your start script. At this point you can apply your bash foo. See [docs for details](http://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/customize.html?highlight=bashscriptextradefines#bashscript-defines). On the [Cheatsheet page](http://www.scala-sbt.org/sbt-native-packager/archetypes/cheatsheet.html) you may find some interesting points as well.

Still. I highly recommend against a custom application life cycle management. `killall java` is _not_ a good way to manage applications. Learn more about your Server OS and use the facilities provided.

**Comment by hepin1989** [comment]
@shijinkui you could use scala at taobao?I don't think so .

**Comment by muuki88** [comment]
@hepin1989 Yeah, play creates it's own PID which makes things a little tricky sometimes. If you use play you are already using the server archetype. Play enables it by default. However you have [to configure the PID location](http://www.scala-sbt.org/sbt-native-packager/topics/play.html#build-configuration)

**Comment by shijinkui** [comment]
@hepin1989 My last scala project use play framework with the pid. Current working have no need to use it again.  Play also have to much dependencies, and depend on special netty version. I work in aliyun.

@muuki88 i tried that tricky way. Thanks.  If plugin can generate pid by default, it will be more clean for developer.  :+1:   
That' all.

**Comment by hepin1989** [comment]
@shijinkui hem,you could using scala:).would you mind join our akka group(257534530) and play group(128259394) at qq?

I think you could package the stop script to the package just as Play does.

**Comment by muuki88** [comment]
@shijinkui you need a PID if need to manage the application lifecycle (start-stop-status-restart). See [my last comment](https://github.com/sbt/sbt-native-packager/issues/164#issuecomment-141643656) above how to add these stuff in `bashScriptExtraDefines`. What I forgot: You also need to add a folder in the `linuxPackageMappings` where the executing user has write access. I will close the discussion here as

1. SBT Native Packager will not provide any application lifecycle management
2. The solutions to build a homegrown application lifecycle management are in this and [my last comment](https://github.com/sbt/sbt-native-packager/issues/164#issuecomment-1416436562)
