### ISSUE TITLE
Let's rename master branch to main

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-native-packager#1645]
I'm now used to seeing main for git repos, master feels anachronistic.

**Comment by muuki88** [comment]
Yes, please :smile:  If you have the time, I'm happy to merge and you probably have access to all the settings, right?

**Comment by eed3si9n** [comment]
Done. GitHub says to run this locally to follow along:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by muuki88** [comment]
Works for me :+1: :heart:
