### ISSUE TITLE
Don't pass MaxPermSize to Java 8+

### ISSUE THREAD

**Issue by jroper** [sbt/sbt-native-packager#203]
Java 8+ does not support -XX:MaxPermSize, and outputs a big ugly error message if you supply it:

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
```

The script generated by SBT native packager should not pass a MaxPermSize argument to Java 8 JVMs.

**Comment by TshepoMokgoatjane** [comment]
Hi guy, I am facing this issue and this is how my STS.ini file looks like:

===============================

-vm
C:/Program Files/Java/jdk1.8.0_60/bin
-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.300.v20150602-1417
-product
org.springsource.sts.ide
--launcher.defaultAction
openFile
--launcher.XXMaxPermSize
512M
-vmargs
-Dosgi.requiredJavaVersion=1.7
-Xms40m
-XX:MaxPermSize=512m
-Xverify:none
-Dorg.eclipse.swt.browser.IEVersion=10001
-Xmx1200m

=====================================

The message I get is : 

======================================

Nov 12, 2015 12:07:02 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1011 ms
Nov 12, 2015 12:07:02 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 702 ms
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

===================================

I'm running Windows 8.
Spring Tool Suite 

Version: 3.7.1.RELEASE
Build Id: 201510041213
Platform: Eclipse Mars.1 (4.5.1)

Copyright (c) 2007 - 2015 Pivotal Software, Inc.
All rights reserved. Visit http://spring.io/tools/sts

This product includes software developed by the
Apache Software Foundation http://www.apache.org

What am I missing?

**Comment by muuki88** [comment]
I think you are on the wrong issue-list here. This sbt-native-packager not eclipse ;)
