### ISSUE TITLE
Feature request: createHomeDirectory

### ISSUE THREAD

**Issue by paddymahoney** [sbt/sbt-native-packager#238]
I was looking to create a home directory for the daemonUser.

I tried to modify some of the debian templates in the following way: 

 b/module/src/templates/postinst-useradd

``` bash
@@ -0,0 +1,5 @@
\# Adding ${{user}}
if ! id -u ${{user}} > /dev/null 2>&1; then
    echo "Creating user ${{user}} in group ${{group}}"
    useradd --system --create-home --gid ${{group}} --shell /bin/false ${{user}}
fi
```

b/module/src/DEBIAN/postrm-purge

``` bash
\# Deleting user: ${{user}} and group: ${{group}}
case "$1" in
   remove|failed-upgrade|abort-upgrade|abort-install|disappear)
   ;;
   purge)        
        deluser --quiet --remove-home --system ${{user}} > /dev/null || true
        delgroup --quiet --system ${{group}} > /dev/null || true
   ;;
   upgrade)
   ;;
   *)
      echo "postinst called with unknown argument \`\$1'" >&2
   ;;
esac
```

Alternately, I would use a 'createHomeDirectory in Debian' settingKey.

**Comment by francisdb** [comment]
@muuki88 most of this stuff is outdated, I was wondering what today would be the best way to have this home directory created

**Comment by muuki88** [comment]
@francisdb thanks for sharing. I like the idea of creating a home directory explicitly. I wonder if this would be a nice idea for a small archetype, e.g. `CreateHomeDirectoryPlugin`, which adds this piece of code to `rpm` and `debian`. Or if we just put it in the docs.

**Comment by francisdb** [comment]
@muuki88  I'm more fan of having an option for `--create-home` on the useradd command as that probably uses an os-specific template for the home directory instead of an empty folder
