### ISSUE TITLE
Version 0.7.1 and onwards does not build RPMs on Mac OSX Host

### ISSUE THREAD

**Issue by adatoo** [sbt/sbt-native-packager#266]
Version 0.7.0 successfully builds RPMs on Mac OSX Host. Version 0.7.1 does not. Please see my example Play project [linux-deploy-sample](https://github.com/adatoo/linux-deploy-sample) for an example.

**Comment by EugenCepoi** [comment]
Is there a fix for this issue? I have the same problem when building with rpm 5. First *"Package has no %description"* and when tweaking things I got the other one *"fg: no job control"*.
The same build works fine with rpm 4 on a debian.

Thanks

**Comment by muuki88** [comment]
I think this is out of scope of native packager. If you want to package rpms our main goal is to support it on the native platform. Sorry :'(

**Comment by EugenCepoi** [comment]
Ah sad :( Was thinking that this plugin had similar goals as jdeb. But perhaps deb packaging is more stable than rpm...

Might be of interest for others: actually when using `rpmBrpJavaRepackJars := true` and defining rpmGroup and rpmDescription, the rpm is being built. Even if we  encounter that other error `--rpm-requires: invalid option` like explained in issue #327.

**Comment by muuki88** [comment]
> Ah sad :( Was thinking that this plugin had similar goals as jdeb. But perhaps deb packaging is more stable than rpm...

Nope. We are using jdeb in fact to provide platformwide Debian packaging. Jdeb is a java-based Debian spec implementetion. I think there are no stable ones for rpm out there, because rpm does a lot more then Debian. Like compiling, optimzing etc.

> Might be of interest for others: actually when using

Always is :)
