### ISSUE TITLE
allow archive targets to eliminate top-level directory

### ISSUE THREAD

**Issue by easel** [sbt/sbt-native-packager#276]
See http://stackoverflow.com/questions/20133164/why-does-sbt-native-packager-generate-a-hardcoded-top-level-parent-directory-in for more details.

One use case. Trying to use the output from packageBin to deploy a docker file to elastic beanstalk fails because elastic beanstalk expects to find the Dockerfile in the root of the .zip file.

**Comment by jdeastwood** [comment]
@muuki88 Ha, I was just starting to look at implementing your suggestion above for packaging a [samza job](http://samza.apache.org/learn/documentation/0.7.0/jobs/packaging.html), only to find you've committed a fix! Thanks!

@prascuna doubtless you are more observant than I, but I was struggling to get @easel's solution working as well before I noticed he overwrote the top-level packageBin, not universal:packageBin as you did.

**Comment by muuki88** [comment]
I'll just add some docs and then I'll pull off a release hopefully this weekend :)
