### ISSUE TITLE
Permission denied to execute entry point in Docker

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-native-packager#331]
Building a Docker image for https://github.com/hseeberger/echo-httpd works like a charm, but running a Docker container from it fails:

```
docker$ docker run echo-httpd:1.0.0
bash: bin/echo-httpd: Permission denied
```

**Comment by leozilla** [comment]
I just ran into the same problem, as I am no Dockerfile expert, could somebody show me how to fix/work around this pls
