### ISSUE TITLE
Execute flag missing from bin/prog with sbt task universal:packageBin when zipped and unzipped in OS X

### ISSUE THREAD

**Issue by akauppi** [sbt/sbt-native-packager#334]
Hi,

thanks a Million for sbt-native-packager. Have found one minor bug I'd like to report - unfortunately don't have time to do more on this. Occurs on both 0.7.1 and 0.7.5-RC1.

If I do `sbt stage` task, the `bin/myapp` file has execution attribute, as expected.
If I do `universal:packageBin` (i.e. allowing sbt to zip the package for me), it doesn't.

I'm using OS X 10.9.4 and Java 1.8.0_11-b12 if that matters (though I'm not 100% sure which JDK gets kicked in for the zipping).

**Comment by muuki88** [comment]
Bad news. NIO doesn't fix this either :(
