### ISSUE TITLE
separation of 3rd party and application libs

### ISSUE THREAD

**Issue by ahjohannessen** [sbt/sbt-native-packager#365]
Would it be an idea to separate 3rd party libs from application libraries *and* change the docker build to account for two ADDs such that uploads to remote repo can be trimmed? I reckon that the frequency of changes is higher for application libs than 3rd party.

**Comment by muuki88** [comment]
This ticket now duplicates #723

**Comment by ahjohannessen** [comment]
@muuki88 Will #723 solve this problem?

**Comment by ahjohannessen** [comment]
Btw, is changing ownership still creating an additional layer with docker? I.e. double up size of layers?

**Comment by muuki88** [comment]
@ahjohannessen , yes `chown` still creates a second layer and I hope #723 will provide the base line for fixing this
