### ISSUE TITLE
Stale PID file prevents service from starting with Upstart

### ISSUE THREAD

**Issue by artempyanykh** [sbt/sbt-native-packager#377]
I'm trying to package my Play 2 App as a .deb package, and have certain difficulties on the way.

Don't know if doing something wrong, but the story is:
1. I package my app with `debian:packageBin` task.
2. Then I install the package with `sudo dpkg -i target/the_app.deb`. At this point my application starts and writes its PID to `/usr/share/the_app/RUNNING_PID` (assume the PID is 1415).
3. Then I restart a server. If I look at the contents of `/usr/share/the_app/RUNNING_PID` it is still 1415 (dead process from step 2.) and app is not running (I expected it should autostart because of `start on runlevel [2345]` in init config).
4. Next if I try `sudo service the_app start` I get a flapping service and a stream of

```
Play server process ID is 5886
This application is already running (Or delete /usr/share/odin/RUNNING_PID file).
```

in `/var/log/upstart/the_app.log`.

I'm using Play 2.3.4, Scala 2.11.1. 
All the experiments were made on a clean Ubuntu 12.04. 
I don't use any custom packaging configuration, except required minimum (maintainer, summary, description, daemonUser and daemonGroup).

**Comment by ludwigm** [comment]
I also had this problem now and it took my a long time to figure out. I think this could be documented a little better in that section.

**Comment by francisdb** [comment]
Do I understand this correctly that if the JVM dies (oom, ...) the PID file sticks around, on restart play finds it but has no way to check if the process is still alive so it bails out.

**Comment by dandeezy** [comment]
I'm running into this issue and did not understand exactly how to fix it. I do not have a src folder but an app folder. In play 2.5, should I add a src/templates/etc-default for this purpose only?

**Comment by muuki88** [comment]
The best solution is to let play *not* handle the pid file. Simply add this to your start configuration

```
-Dpidfile.path=/dev/null
```
e.g. in yourr `build.sbt`

```scala
javaOptions in Universal += "--Dpidfile.path=/dev/null"
```

or in your `application.conf`

```
pidfile.path = "/dev/null"
```

**Comment by gvalenncia** [comment]
Hi @all:

I am trying to run my play application as standalone (as explained here https://www.playframework.com/documentation/2.5.x/Deploying). I've already created a binary distribution using sbt assembly plugin, but every time i try to start the app, I got the following error and I do not know what is happening 

`com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'play.application'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:198)
        at com.typesafe.config.impl.SimpleConfig.getIsNull(SimpleConfig.java:208)
        at play.api.ConfigLoader$$anon$4.load(Configuration.scala:1078)
        at play.api.ConfigLoader$$anon$4.load(Configuration.scala:1076)
        at play.api.PlayConfig.get(Configuration.scala:918)
        at play.utils.Reflect$.configuredClass(Reflect.scala:112)
        at play.api.ApplicationLoader$.apply(ApplicationLoader.scala:56)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:46)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
`
It seems, the key 'play.application' key has not been configured in the application.conf file, but I haven't found any document explaining how to configure this key. If someone here has run into the same issue, I appreciate any advice. Currently I am using play framework 2.5

thanks

**Comment by muuki88** [comment]
Hi,

Thanks for your question. This is unfortunately the wrong place as you have an issue with sbt-assembly, play and typesafe config, not with sbt-native-packager. Also this issue here is unrelated.

Use Stackoverflow for this kind of question. Issues are for bug reports and feature requests. 

Also include your build configuration and how you start your application, so people can help you.
