### ISSUE TITLE
packageName in Docker not found

### ISSUE THREAD

**Issue by treyhyde** [sbt/sbt-native-packager#413]
The documentation here (http://www.scala-sbt.org/sbt-native-packager/DetailedTopics/docker.html) mentions packageName which doesn't appear to exist in 1.0.0-M1 or M2.

build.sbt:51: error: not found: value packageName
packageName in Docker := organization.value + "/" + name.value
^
[error] Type error in expression

**Comment by nafg** [comment]
I guess now it compiles, but it isn't used
