### ISSUE TITLE
Optionally inherit docker entrypoint, and cmd

### ISSUE THREAD

**Issue by tonylotts** [sbt/sbt-native-packager#433]
The entrypoint can be set explicitly with dockerEntrypoint, but there is no way to unset the ENTRYPOINT so that it inherits from the base image.  Similarly, CMD is always set to 'CMD []', and should (optionally) inherit from the base image

**Comment by huntc** [comment]
Further to this, there is no way to presently declare a `CMD`, right? I can tackle this if you want...

**Comment by muuki88** [comment]
I summarized the current tickets in #453 At this point we should start refactoring and
make a decision for the future implementation strategy (at least for the `1.0.0` release)
