### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by sslavic** [sbt/sbt-native-packager#443]
Documentation is outdated - references old plugin version, old sbt version, deprecated settings and ways of use.

E.g. http://www.scala-sbt.org/sbt-native-packager/GettingStartedApplications/MyFirstProject.html

references sbt 0.13.1, sbt-native-packager 0.8.0-M2, instead of deprecated "packageArchetype.java_application" usage should have "enablePlugins(JavaAppPackaging)"

Also, publishing generated packages as artifacts (deployment) is not covered in docs (see related SO question: http://stackoverflow.com/q/21558398/381140 )

**Comment by ches** [comment]
Just had the chance to look and that is looking much better already! If I have the chance I'll try to pitch in with archetype docs or at least review work-in-progress. Happy New Year :grin:
