### ISSUE TITLE
dockerUpdateLatest does not work with Docker 1.4.1

### ISSUE THREAD

**Issue by leonardschneider** [sbt/sbt-native-packager#456]
Got message using dockerPublishLocal
time="2015-01-08T00:09:13+08:00" level="fatal" msg="Error response from daemon: Conflict: Tag latest is already set to image f2713071c080fe4d0599b8c1f71659ac5d6f906a1ee7fb9cb32b2438cbf2963c, if you want to replace it, please use -f option"

**Comment by muuki88** [comment]
Fixed with #452
