### ISSUE TITLE
Dockerfile creates two large layers

### ISSUE THREAD

**Issue by DougC** [sbt/sbt-native-packager#465]
The generated dockerfile is inefficient in the layers it creates. The ADD command comes first and generates a layer with all the application files. For a Play framework application this amounts to at least 39M of libraries. The chown command that is run two lines down then modifies all of those files resulting in a second layer of the same size. (Docker sees a change of ownership as a change to the whole file).

One solution might be to map a volume outside the copy-on-write filesystem where the project files can be added, change their permissions there and then move them into place. This would create a single layer for them.

We're pushing to a repo over a relatively slow internet connection, which really highlights this problem for us.

**Comment by muuki88** [comment]
This is a long outstanding issue which has been discussed in

- #365 separated 3rd party libraries
- #368 creating cachable intermediate docker images
- #453 big docker refactoring

When I have time I will translate my code from #368 into an
additional AutoPlugin, which activates the separation for docker.
However #453 has to be completed before.

**Comment by muuki88** [comment]
https://github.com/sbt/sbt-native-packager/issues/723
