### ISSUE TITLE
0.8.0: JDebPackaging doesn't take into account daemonUser setting

### ISSUE THREAD

**Issue by aparamonov** [sbt/sbt-native-packager#468]
I have following settings in build.sbt

```
name := "guide-menu-web"

packageArchetype.java_server

packageBin in Debian <<= debianJDebPackaging in Debian

serverLoading in Debian := ServerLoader.Upstart

daemonUser in Debian := "guide-menu"
```

But 'sbt debian:packageBin' command generates deb-scripts with 'guide-menu-web' user.
For example, \target\universal\tmp\bin\debianpostinst contains following script: https://gist.github.com/aparamonov/95f520720b5adcee7312

**Comment by muuki88** [comment]
Try 

```scala
daemonUser in Linux := "guide-menu"
```

there are still some gaps between the `Linux` and `Rpm`/`Debian` configurations

**Comment by aparamonov** [comment]
That's working, thanks!
