### ISSUE TITLE
[doc] "Generating files for the package" examples not rendered

### ISSUE THREAD

**Issue by sslavic** [sbt/sbt-native-packager#469]
["Generating files for the package"](http://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/generating-files.html) text references sbt/scala examples (e.g. "Add the following to build.sbt"), but these are not being rendered (tried in FF, Chrome, Safari).

**Comment by sslavic** [comment]
Examples code blocks are in the documentation sources https://raw.githubusercontent.com/sbt/sbt-native-packager/master/src/sphinx/archetypes/java_app/generating-files.rst

So maybe there is a syntax error or doc source processing/publishing issue.

**Comment by muuki88** [comment]
Thanks for reporting :) 

Sphinx didn't warn about that :/
