### ISSUE TITLE
"/etc/default/<package-name>" should be shell script setting envars

### ISSUE THREAD

**Issue by dhardy92** [sbt/sbt-native-packager#472]
Current format is java option only append to java command line.
This is not standards and not very flexible and expendable.
Shell let us include other source and split config in several files and responsibilities using ```source```
Moreover, envars usage is a 12-factors app recommendation.

**Comment by kardapoltsev** [comment]
From [Debian Policy Manual ](https://www.debian.org/doc/debian-policy/ch-opersys.html)

>>Often there are some variables in the init.d scripts whose values control the behavior of the scripts, and which a system administrator is likely to want to change. As the scripts themselves are frequently conffiles, modifying them requires that the administrator merge in their changes each time the package is upgraded and the conffile changes. To ease the burden on the system administrator, such configurable values should not be placed directly in the script. Instead, they should be placed in a file in /etc/default, which typically will have the same base name as the init.d script. This extra file should be sourced by the script when the script runs. It must contain only variable settings and comments in SUSv3 sh format. It may either be a conffile or a configuration file maintained by the package maintainer scripts.

**Comment by kardapoltsev** [comment]
Current format accepts any vars that you want to change in init script.

**Comment by kardapoltsev** [comment]
Hmm.. Seems that during refactoring we missed this. We should source /etc/default/app_name in init script.

**Comment by kardapoltsev** [comment]
@dhardy92,  PR is welcome!

**Comment by knshiro** [comment]
Hello everyone, why was this reverted?
I had to modify my `build.sbt` to add lines to the bash script to be able to use environment variables and was happy to see that was put in the plugin...

**Comment by kardapoltsev** [comment]
See #491

**Comment by jasonmartens** [comment]
This bug should be re-opened, since the /etc/default/<package-name> script is still not getting sourced.

**Comment by muuki88** [comment]
@jasonmartens can you open a new issue with a small sample project demonstrating the case?
