### ISSUE TITLE
sbt-release with docker plugin step

### ISSUE THREAD

**Issue by mhamrah** [sbt/sbt-native-packager#475]
I'm trying to add a ReleaseStep using [sbt-release](https://github.com/sbt/sbt-release) that publishes a docker image. I've overwritten the current release process like so:

```
ReleaseKeys.releaseProcess := Seq[ReleaseStep](
  releaseTask(publishLocal in Docker)
)
```
but nothing happens when I run release (I've tried reloading sbt). When running

```
docker:publishLocal
```

everything works fine, I thought this translated to a TaskKey of publishLocal in Docker for sbt-release. I figure I'm missing something obvious. I glanced at this code, and it appears that docker.Keys.publishLocal is set to sbt.publishLocal, and I can't figure out how the docker setting for publish local maps to a task.

Thanks,

Mike

FYI sbt-native-packager 0.8.0.

**Comment by muuki88** [comment]
I'll try to reproduce this with a small example. IMHO it sounds like some interaction problem with sbt-release, however I haven't tried it with sbt-np yet.

**Comment by mhamrah** [comment]
@muuki88 I hacked around with it, and stumbled upon a solution but I don't know why it works. I had to add "in ref" to the release step:

```
lazy val dockerRelease: ReleaseStep = { st: State =>
  val extracted = Project.extract(st)
  val ref = extracted.get(thisProjectRef)
  extracted.runAggregated(publish in Docker in ref, st)
}
```

I copied code from sbt-release which had something similar.

**Comment by muuki88** [comment]
Thanks for sharing @mhamrah If you have time it would be awesome to provide a small example for this in the docs (with a minimal `build.sbt`) showing this. There is an _advanced topics_ section in `src/sphinx/topics` where this would fit perfectly. 

@jsuereth you have any clue why @mhamrah 's solution works?

**Comment by mhamrah** [comment]
@muuki88 I'm always happy to add documentation!

**Comment by muuki88** [comment]
That's awesome to hear :) Looking forward to your pull request

**Comment by chrissom** [comment]
Here is more elegant way with ```releaseStepTask```:

```
releaseProcess := Seq(
  checkSnapshotDependencies,
  inquireVersions,
  runTest,
  ReleaseStep(releaseStepTask(publish in Docker)))
```

**Comment by muuki88** [comment]
tHANKS FOR SHARING @chrissom

**Comment by nemo83** [comment]
did this end up in any documentation? Am working on something similar

**Comment by muuki88** [comment]
relates to #974
