### ISSUE TITLE
Using the -jvm-debug flag should pass the -agentlib jvm flag instead of -Xrunjdwp flag

### ISSUE THREAD

**Issue by jateenjoshi** [sbt/sbt-native-packager#476]
It looks like the jvm debugger options passed into the java application are of the type:

```bash
-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=12345  
```

which is the outdated JDK 1.4 way of doing things.

Shouldn't it be using these args instead:

```bash
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=12345
```

I couldn't get remote debugging with IntelliJ working with my application which uses JDK 7 with the args that the native packager uses for `-jvm-debug`, but could get it working with the latter set of args

**Comment by muuki88** [comment]
Thanks for reporting. The `-jvm-debug` is a convenience setting, so you can always choose (as you did) to do it manually. 

However I think updating this would be a good idea as I have no report of any jdk 1.4 user. Would you like to provide a pull request for this? [This is the place](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template#L150-L153) to change.
