### ISSUE TITLE
multi module project is packaged into multiple docker images

### ISSUE THREAD

**Issue by lkt** [sbt/sbt-native-packager#480]
I have a multi module project. When doing docker:publishLocal or docker:publish it produces a separate docker image for each module. I would like to have it only publish the root project which contains all the submodules as jars anyway.

**Comment by lkt** [comment]
ok I could solve it the following way:

    lazy val root = Project(
      id = "some-project",
      base = file("."))
      .enablePlugins(PlayScala)
      .dependsOn(a, b, c)
      .aggregate(a, b, c)
      .settings(aggregate in Docker := false)

**Comment by abbi-gaurav** [comment]
Helpful!!!
