### ISSUE TITLE
javaagent is not recognized in jvmopts

### ISSUE THREAD

**Issue by behrad** [sbt/sbt-native-packager#481]
I should add aspectj weaver and jolokia JVM agents to my JVM, and this is my jvmopts:

```
-Djava.library.path=/usr/share/sigar
-javaagent:/media/data/workspace/adp-endpoint-pardis/target/universal/adp-pardis-1.0/lib/org.jolokia.jolokia-jvm-1.2.2-agent.jar=port=8182
-javaagent:/media/data/workspace/adp-endpoint-pardis/target/universal/adp-pardis-1.0/lib/org.aspectj.aspectjweaver-1.8.2.jar
```

when running universal run script  via `-d` I found that `-javaagent` is placed after $mainclass so it is collected by  `app_commands` or  `residual_args`

```
  # run sbt
  execRunner "$java_cmd" \
    $(get_mem_opts $app_mem) \
    ${java_opts[@]} \
    "${java_args[@]}" \
    -cp "$(fix_classpath "$app_classpath")" \
    $mainclass \
    "${app_commands[@]}" \
    "${residual_args[@]}"
```

**Comment by behrad** [comment]
by reading source I found converting -J-javaagent solved the above, however how can I use some app_path parameter in `jvmopts` so that I avoid using absolute path of lib jars :( 
`-J-javaagent:???/lib/xyz.jar`

Is the same issue happening with `etc-default` in non universal packages?

**Comment by muuki88** [comment]
There was a pull request for this (#265). I think there was a pull request for adding a separator between java and application args. If I recall correctly it was `--`. Maybe this helps.

**Comment by muuki88** [comment]
From gitter chat room (with version `1.0.0`)

```
javaOptions in Universal ++= Seq(
    "-J-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9000"
)
```
