### ISSUE TITLE
bashScriptConfigLocation in rpm:packageBin via 1.0.0-M4

### ISSUE THREAD

**Issue by behrad** [sbt/sbt-native-packager#482]
`bashScriptConfigLocation := Some("${app_home}/../conf/jvmopts")`
which is working in 0.8.0 causes this error in 1.0.0-M4:

```
java.lang.RuntimeException: Could not create directory /media/data/workspace/adp-endpoint-pardis/target/rpm/tmp-buildroot/${app_home}/../conf
```

**Comment by muuki88** [comment]
Can you provide some more context? 

- build system (mac, windows, linux distribution?)
- sbt command (`packageBin:universal` ?)
- sample to reproduce this

**Comment by muuki88** [comment]
Nevermind. I found the error. Will fix this in the next RC
