### ISSUE TITLE
Installing generated rpm on a clean centos (6.6 and 7.0)

### ISSUE THREAD

**Issue by behrad** [sbt/sbt-native-packager#484]
I tested rpm:packageBin on both cent 6.6 and 7.0 and got the following installation error:

```
[root@myServer ~]# rpm -ivh adp-pardis-1.0-1.x86_64.rpm 
error: Failed dependencies:
	libc.so.6 is needed by adp-pardis-1.0-1.x86_64
	libc.so.6(GLIBC_2.0) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6(GLIBC_2.1) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6(GLIBC_2.1.2) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6(GLIBC_2.1.3) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6(GLIBC_2.2) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6(GLIBC_2.2)(64bit) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6(GLIBC_2.3) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6.1()(64bit) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6.1(GLIBC_2.2)(64bit) is needed by adp-pardis-1.0-1.x86_64
	libc.so.6.1(GLIBC_2.3)(64bit) is needed by adp-pardis-1.0-1.x86_64
	libkstat.so.1 is needed by adp-pardis-1.0-1.x86_64
	libkstat.so.1()(64bit) is needed by adp-pardis-1.0-1.x86_64
	libkstat.so.1(SUNW_0.7) is needed by adp-pardis-1.0-1.x86_64
	libkstat.so.1(SUNW_0.7)(64bit) is needed by adp-pardis-1.0-1.x86_64
	libkvm.so.2 is needed by adp-pardis-1.0-1.x86_64
	libkvm.so.3 is needed by adp-pardis-1.0-1.x86_64
	libkvm.so.3()(64bit) is needed by adp-pardis-1.0-1.x86_64
	libnm.so is needed by adp-pardis-1.0-1.x86_64
	libnsl.so.1 is needed by adp-pardis-1.0-1.x86_64
```

I couldn't find any documentation about which packages should be already installed by hand on deployment :(

**Comment by muuki88** [comment]
This doesn't look like a sbt-native-packager problem, as the rpm by default has no requirements. You have to define them explicitly. Can you post a `build.sbt` (or a small project) to reproduce this.

**Comment by behrad** [comment]
@muuki88 these look like dev tools packages, shall I install development tools group on the fresh centOS?

**Comment by muuki88** [comment]
I don't know. What are you packaging? By default the `rpmPrerequisites` and `rpmRequierements` are empty, so the installation doesn't check for anything. Your rpm seems to require `adp-pardis-1.0-1.x86_64` for some reason. So a small example project to reproduce this or to see the config would be very helpful. 

You are building it for a  certain architecture as well (`x86_64`), so you include native libraries, right?

**Comment by muuki88** [comment]
@behrad any updates on this?

**Comment by behrad** [comment]
actually haven't time to test this yet... will let you know...
