### ISSUE TITLE
Default value for `jdkPackagerTool` is computed incorrectly on Windows.

### ISSUE THREAD

**Issue by metasim** [sbt/sbt-native-packager#495]
The `locateJDKPackagerTool()` did work on windows, I had to set the setting with:

```scala
jdkPackagerTool := Some(file("C:\\Program Files\\Java\\jdk1.8.0_31\\bin\\javapackager.exe"))
```

**Comment by metasim** [comment]
I plan on working on this one.

**Comment by metasim** [comment]
Issue appears to be that under windows, a separate JRE is installed with the JDK, and the JRE `java` is in the PATH before the JDK `java`. Therefore, when SBT runs, by default, it runs under the JRE and not the JDK. Looking into way of either a) getting the JDK path from some other SBT setting, or b) figuring out the path to the JDK from the JRE with minimal hackishness.

**Comment by metasim** [comment]
Also forgot about Windows executables having the (hidden) ".exe" extension.

**Comment by metasim** [comment]
Pull request submitted.

**Comment by muuki88** [comment]
@metasim , if you include `FIX #issuenumber` in the commit the issue gets  closed automatically if the pr is merged :)

**Comment by metasim** [comment]
@muuki88 Thanks for the tip. Was my mistake that "Fix" wasn't all caps?

**Comment by muuki88** [comment]
I think that should matter. The pr just hasn't been merged yet :)
