### ISSUE TITLE
Clean image after publishing

### ISSUE THREAD

**Issue by kanuku** [sbt/sbt-native-packager#501]
We are using a CI system to push our images to the registry, after every build.
After pushing an image to the registry, the image is left in the local registry.
It would be great if we could have an extra target to push an image and remove the image locally afterwards.
Something like:
 `activator clean docker:publishClean`

**Comment by muuki88** [comment]
@kanuku did you solve this issue? If you like to do a pull request I would help you.

**Comment by LappleApple** [comment]
@muuki88 I've asked our team to see if we can do this -- @kanuku and I are colleagues
