### ISSUE TITLE
Failing Windows Tests

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#502]
On AppVeyor the following tests fail for strange reasons

- `scripted jar/*`
- `scripted windows/test-bat-template`

[More Details](https://ci.appveyor.com/project/muuki88/sbt-native-packager/build/6)

cc @nazoking @bjuric , if you have any ideas :)

**Comment by nazoking** [comment]
wmm.. 

this error cause is _JAVA_OPTS. 

> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2g; support was removed in 8.0

it set here.

https://ci.appveyor.com/project/muuki88/sbt-native-packager/build/6#L15

can you remove this `MaxPermSize` option ?

**Comment by muuki88** [comment]
Thanks for the fast response :+1:  
I remove the whole `JAVA_OPTS` line, with the same result.

https://ci.appveyor.com/project/muuki88/sbt-native-packager/build/12

**Comment by nazoking** [comment]
Merge miss occured. on https://github.com/sbt/sbt-native-packager/commit/3577a556869a0e0bc15b918a183d6009db53c263#diff-0893ecb3791881c87ff523facf8b1880R140

This 2 lines removed on https://github.com/sbt/sbt-native-packager/commit/b5a259d92e84625e5a4d224f323cc3fe215bdc21

**Comment by nazoking** [comment]
And maybe java change ProcessBuilder cmd escape algorithm .. surely  https://blogs.oracle.com/thejavatutorials/entry/changes_to_runtime_exec_problems ...

**Comment by muuki88** [comment]
Did you test this on java 6? Maybe I should try this as well :/

**Comment by nazoking** [comment]
i create #507. it success on jdk1.7.0_25, jdk1.8.0_20

**Comment by nazoking** [comment]
I tried on jdk1.6.0_27, but it has compile error. jdk6 dont have java.nio.file
