### ISSUE TITLE
defaultLinuxInstallationLocation should read defaultLinuxInstallLocation

### ISSUE THREAD

**Issue by tsfto** [sbt/sbt-native-packager#504]
In http://www.scala-sbt.org/sbt-native-packager/archetypes/cheatsheet.html, the line for the 
defaultLinuxInstall<b>ation</b>Location setting should read defaultLinuxInstallLocation

**Comment by muuki88** [comment]
Thanks for pointing out :) Pull Request welcome

**Comment by tsfto** [comment]
Will do...
