### ISSUE TITLE
Changing the default installation directory

### ISSUE THREAD

**Issue by tsfto** [sbt/sbt-native-packager#506]
Anyone done this successfully before? 

In my build.sdb, I've got ("foo" substituted for the real name): 

defaultLinuxInstallLocation in Linux := "/foo/"

but while some of the control files have the correct path (with /foo), the contents of data.tar.gz are still  ./usr, not ./foo, so my installation fails (our standard is to install into /foo

Any ideas anyone?

I'm using 1.0.0-M5

**Comment by muuki88** [comment]
Are you packaging `deb` or `rpm` packages?

**Comment by muuki88** [comment]
You don't need to scope the `defaultLinuxInstallLocation`.

```scala
defaultLinuxInstallLocation := "/foo/"
```

is enough.
