### ISSUE TITLE
None of the plugins are available in build.sbt, so I can't use enablePlugins() on them there

### ISSUE THREAD

**Issue by 2rs2ts** [sbt/sbt-native-packager#516]
I've been upgrading one of my projects from 0.8 to 1.0, but when I try to enable any of the native packager plugins, I always get `error: not found: value <whatever plugin>`. I was able to successfully enable the plugins in `Build.scala` but not in `build.sbt`. I am using sbt 0.13.7 which I downloaded from homebrew, and version 1.0.0-RC1 of this plugin.

Example `build.sbt`:

```scala
scalacOptions ++= Seq("-deprecation", "-unchecked", "-feature")

enablePlugins(RpmPlugin) // this didn't work
```

My `plugins.sbt`:

```
addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.2")

addSbtPlugin("com.github.retronym" % "sbt-onejar" % "0.8")

addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.7.4")

addSbtPlugin("com.github.sdb" % "xsbt-filter" % "0.4")

addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.6.0")

addSbtPlugin("de.johoop" % "jacoco4sbt" % "2.1.5")

addSbtPlugin("com.paypal" % "horizon" % "0.1.4" exclude("org.scala-sbt", "sbt"))

addSbtPlugin("io.spray" % "sbt-revolver" % "0.7.2")

addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.0.0-RC1")
```

I was able to enable the plugins by doing something like this in my `Build.scala`:

```scala
import com.typesafe.sbt.packager.rpm.RpmPlugin
// lots of stuff in between there and here
lazy val myproject = Project(
  "myproject", file("myproject"),
  settings = mySettings ++ Seq(name := "myproject", ...)
).enablePlugins(RpmPlugin)
```

[The docs](http://www.scala-sbt.org/sbt-native-packager/formats/rpm.html#or-higher) said to just add the line in `build.sbt`. Is this a documentation error?

**Comment by kardapoltsev** [comment]
`plugins.sbt` and `build.sbt`
>The sbt-native-packager is a plugin. To use it, first create a `project/plugins.sbt` file with the following content.
...
>If you use sbt 0.13.5 or greater you can enable sbt native packager by enabling it in your `build.sbt`

[The docs](http://www.scala-sbt.org/sbt-native-packager/gettingstarted.html)

**Comment by muuki88** [comment]
Nope. This should work out of the box. Can you provide a minimal example reproducing this?

**Comment by 2rs2ts** [comment]
@muuki88 I will be glad to do so when I have some time or when we open source this project, whichever comes first.

**Comment by muuki88** [comment]
`AutoPlugins` don't work with `Build.scala`
