### ISSUE TITLE
proguard support

### ISSUE THREAD

**Issue by joprice** [sbt/sbt-native-packager#518]
Any tips on integration with sbt-proguard?

**Comment by muuki88** [comment]
Haven't used it yet, but if you have a working example, I am interested.

**Comment by muuki88** [comment]
Any progress @joprice ?

**Comment by mikebridge** [comment]
@muuki88 I was able to create a Raspbian .deb file for a scala service with sbt-native-packager but it's huge.  Is there any way to get proguard to process the jar before it is packaged?  Would it require a separate Proguard AutoPlugin implementation inside sbt-native-packager?

**Comment by muuki88** [comment]
To work with native-packager proguard needs to support multiple jars as input and stripping out the class files in each of them. IMHO the best way would be to use native packager [together with sbt-assembly](http://www.scala-sbt.org/sbt-native-packager/topics/custom.html#sbt-assembly) and use proguard on the assembly jar. 

Also: https://github.com/sbt/sbt-proguard

**Comment by mikebridge** [comment]
@muuki88 Thanks---I am doing this in a multiple-project setup, and my `build.sbt` now contains something like this:

```scala
lazy val  mysubproject = project.in(file("mysubproject")).
  enablePlugins(JavaAppPackaging).
  settings(proguardSettings: _*).
  settings(assemblySettings: _*).
  settings(
    name := "mysubproject",

    version := "0.0.1",

    serverLoading in Debian := ServerLoader.SystemV,

    debianPackageDependencies in Debian := Seq("mosquitto"),

    jarName in assembly := "mysubproject.jar",

    mappings in Universal := {
      val universalMappings = (mappings in Universal).value
      val fatJar = (assembly in Compile).value
      val filtered = universalMappings filter {
        case (file, name) =>  ! name.endsWith(".jar")
      }
      filtered :+ (fatJar -> ("lib/" + fatJar.getName))
    },

    ProguardKeys.options in Proguard ++= Seq("-dontnote", "-dontwarn", "-ignorewarnings"),

    ProguardKeys.options in Proguard += ProguardOptions.keepMain("com.example.Main"),

    ProguardKeys.proguardVersion in Proguard := "5.2",

    scriptClasspath := Seq( (jarName in assembly).value ),
    
    // ... etc.
))
```

Running `myproject/universal:package-zip-tarball` will now create and package the fat jar (nice!), and `myproject/proguard:proguard` will create a jar and run proguard on it, but I'm at a loss at this point about what to do next to integrate them together....

**Comment by muuki88** [comment]
The code above is almost correctly. You are adding the `assembly ` task result to the mappings ( which is the jar file). Instead you should use the `proguard:proguard` result ( which should be a file ) .

Something like

```scala
// before: val fatJar = (assembly in Compile).value
val proguardJar = (proguard in proguard).value
```

**Comment by mikebridge** [comment]
@muuki88 Thanks!  Based on your suggestions I got it working with something similar to this:

```scala
lazy val  mysubproject = project.in(file("mysubproject")).
  enablePlugins(JavaAppPackaging).
  settings(proguardSettings: _*).
  settings(

    name := "mysubproject",

    version := "0.0.1",

    serverLoading in Debian := ServerLoader.SystemV,

    debianPackageDependencies in Debian := Seq("mosquitto"),

    ProguardKeys.options in Proguard ++= Seq("-dontnote", "-dontwarn", "-ignorewarnings"),

    ProguardKeys.options in Proguard += ProguardOptions.keepMain("com.example.Main"),

    ProguardKeys.proguardVersion in Proguard := "5.2",

    mappings in Universal := (ProguardKeys.proguard in Proguard).value.map(jar => jar -> ("lib/" +jar.getName)),

    scriptClasspath := (ProguardKeys.proguard in Proguard).value.map(x => x.getName),
   
    // etc.
  )

```

Then...

```bash
> mysubproject/universal:package-zip-tarball

> mysubproject/debian:package-zip-tarfile

```

The proguard command-line parameters need some adjustment, but that's the basic idea.  Very cool!

**Comment by muuki88** [comment]
Nice! If you like you could open a small pull request enhancing the docs with your example in the same section where the assembly example is.

**Comment by mikebridge** [comment]
Ok, there we go.  The actual proguard config for a simple raspberry pi project is massive, but I'll save that for a blog post. :)

**Comment by joprice** [comment]
I didn't have time to follow up on this. Thanks @mikebridge!
