### ISSUE TITLE
Multiple instances of Play application

### ISSUE THREAD

**Issue by mfields106** [sbt/sbt-native-packager#520]
How best to install multiple instances of the same Play application on the same server?

How to specify different port configurations and generate multiple services?

**Comment by muuki88** [comment]
With "normal" upstart/SystemV services this is tricky. If you can start them manually, then it's just changing CLI parameters. See [Playframework production configuration] (https://www.playframework.com/documentation/2.3.x/ProductionConfiguration).

I can recommend trying docker. You can start the same image with different port bindings.
