### ISSUE TITLE
Akka archetype bat script needs major rework

### ISSUE THREAD

**Issue by jroper** [sbt/sbt-native-packager#521]
See

https://github.com/sbt/sbt-native-packager/blob/0b3516496467f316660bcedf4463c5308fb83af4/src/main/resources/com/typesafe/sbt/packager/archetypes/akka-bat-template

* `JAVA_OPTS` is hard coded, with no possibility to override it with custom memory or JVM arguments.
* The main bat script contains a lot of very useful functionality, such as logic for locating the right Java version, logic for configuring using environment variables, etc, which is missing from this template.

The bash script suffers from similar problems, but at least it doesn't hard code `JAVA_OPTS` with no possibility to override.

**Comment by muuki88** [comment]
Could  we customize the existing bash/bat scripts in a way suitable for Akka kernel apps? So we only have to maintain one start script. WDYT?

**Comment by jroper** [comment]
I think that would be a great way to do it.

**Comment by patriknw** [comment]
We (Akka Team) would like to remove the `AkkaAppPackaging` and instead document a migration path to `JavaServerAppPackaging` in the Akka documentation. Something like https://github.com/akka/akka/issues/17065.

Next step would be to document a clean usage of `JavaServerAppPackaging` and an ordinary main class for packaging and running an Akka application. Nothing special as far as I can see.

WDYT about removing `AkkaAppPackaging`?

**Comment by muuki88** [comment]
> There's no flexible code as no code

So I'm all about removing if we have to maintain less bash/scala/sbt code without losing any functionality.

**Comment by muuki88** [comment]
We deprecated `AkkaPackaging` and will remove it.

**Comment by kardapoltsev** [comment]
@muuki88, could you remind relevant discussion? I recently tried to find it and failed..

**Comment by patriknw** [comment]
Thanks! We have updated the Akka documentation to recommend the JavaServerAppPackaging.
http://doc.akka.io/docs/akka/snapshot/intro/deployment-scenarios.html

**Comment by muuki88** [comment]
Awesome, thanks @patriknw 

@kardapoltsev No, everything came a bit abruptly. However this is the better way to go.
