### ISSUE TITLE
Docker - Passing production.conf

### ISSUE THREAD

**Issue by mfields106** [sbt/sbt-native-packager#522]
How can I accomplish as described on this site without staging and manually changing:

http://www.ronaldcirka.com/blog/2014/12/06/deploying-play-framework-to-elastic-beanstalk-in-docker/

I would like to add parameter "-Dconfig.resource=${configFile}"

FROM dockerfile/java
MAINTAINER John Doe <john.doe@gmail.com>
ADD files /
WORKDIR /opt/docker
RUN ["chown", "-R", "daemon", "."]
USER daemon
ENTRYPOINT ["bin/myapp", "-Dconfig.resource=${configFile}"]
CMD []
EXPOSE 9000

**Comment by muuki88** [comment]
You have several options.

- [customize bashscript](http://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/customize.html)
- after #510 is merged via `build.sbt`
- using docker env variables
- [cudstomize dockerfile](http://www.scala-sbt.org/sbt-native-packager/formats/docker.html#custom-dockerfile)
