### ISSUE TITLE
Build.scala instructions not working

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-native-packager#527]
first off, `java_packaging` is deprecated, secondly,  `JavaAppPackaging` is not imported by the documented imports. I'm a bit lost because github search isn't finding where `JavaAppPackaging` is defined.

**Comment by fommil** [comment]
```
import com.typesafe.sbt.packager.archetypes._
```

**Comment by muuki88** [comment]
Actually `JavaAppPackaging` should be imported automatically as this is
an autoplugin. However I'm not sure about  `Build.scala`. Duplicated with #516 

Deprecation is intended as you should use autoplugins.
