### ISSUE TITLE
Docker - Setting Daemon user fails - not in right order

### ISSUE THREAD

**Issue by nightwolfzor** [sbt/sbt-native-packager#530]
I'm trying to create a Docker image, I have a simple build.sbt file;

```
enablePlugins(JavaAppPackaging)

enablePlugins(DockerPlugin)

maintainer in Docker := "Blah <blah@blah.com>"

daemonUser in Docker := "chotbi"

dockerExposedPorts := Seq(4800)

dockerExposedVolumes := Seq("/opt/docker/logs")
```
However the docker build fails (using docker v1.5, sbt 0.13.8, packager 1.0.0-RC1) with 
```
[info] Step 4 : RUN chown -R chotbi:chotbi .
[info]  ---> Running in 663be3a5e5f3
[info] chown: invalid user: 'chotbi:chotbi'
```

Its not to hard to see why looking at the resulting docker file;
```
FROM dockerfile/java:latest
MAINTAINER Blah <blah@blah.com>
WORKDIR /opt/docker
ADD opt /opt
RUN ["chown", "-R", "chotbi:chotbi", "."]
EXPOSE 4800
RUN ["mkdir", "-p", "/opt/docker/logs"]
RUN ["chown", "-R", "chotbi:chotbi", "/opt/docker/logs"]
VOLUME ["/opt/docker/logs"]
USER chotbi
ENTRYPOINT ["bin/report-server"]
CMD []
```

**Comment by muuki88** [comment]
Hm. Problem is you can't chown something if you aren't `root`. The user has to be created, that's what is missing.

**Comment by muuki88** [comment]
We default to the `daemon` user, which should be present on most (all?) linux systems. We may need to add this to the docs.

Why do you want to change the user running inside docker?

**Comment by nightwolfzor** [comment]
The user ID and user name are needed for underlying authentication with the host os for some services with volume mounts. So we need to be able to create a custom user. It seems weird to have `daemonUser in Docker := ...` only support preexisting accounts.

**Comment by muuki88** [comment]
I'm not sure what the best practice in this case is. Options coming in mind for me are

- Create the user on the machine you are building the docker image
- Create the user within the dockerfile. ([you can extend the](http://www.scala-sbt.org/sbt-native-packager/formats/docker.html#add-commands) `dockerCommands` setting)

cc @fiadliel
