### ISSUE TITLE
dockerEntrypoint not being set in 1.0.0-M1 and 1.0.0-M2

### ISSUE THREAD

**Issue by davidmweber** [sbt/sbt-native-packager#536]
It appears that the [ENTRYPOINT] statement in the staged  Dockerfile is not being set to the value specified using dockerEntrypoint.  It worked in 1.0.0-M4 but not in RC1 or RC2. The exact command used (build.sbt) is:
```
dockerEntrypoint in Docker := Seq("sh", "-c", "/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1 }'` bin/executable $*")
```

In 1.0.0-M1/M2, it is set to "/bin/executable"

**Comment by muuki88** [comment]
We removed the `Docker` scope from `dockerEntrypoint` has the scope is already visible in the settings name. 

```scala
dockerEntrypoint := Seq("sh", "-c", "/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1 }'` bin/executable $*")
```

should be enough.

**Comment by davidmweber** [comment]
Sweet. Much appreciated.

**Comment by davidmweber** [comment]
FYI, this solves the problem.
