### ISSUE TITLE
Scope of daemon user

### ISSUE THREAD

**Issue by kardapoltsev** [sbt/sbt-native-packager#551]
I'm thinking about ability to specify different users in `Debian` and `Rpm` for example.

``` scala
daemonUser in Debian := "my-deb-user",
daemonUser in Rpm := "my-rpm-user"
```

WDYT?

**Comment by muuki88** [comment]
sounds reasonable. Shouldn't be too hard. You think this is required?

**Comment by kardapoltsev** [comment]
I need this feature for one of my project. I'll do PR if you agree.

**Comment by muuki88** [comment]
Yeah, sure :) This doesn't hurt. The Linux scope stuff should however continue to work :)

**Comment by kardapoltsev** [comment]
Sure (:
