### ISSUE TITLE
Wrong debian systemv init script exit codes

### ISSUE THREAD

**Issue by mahe-ymc** [sbt/sbt-native-packager#552]
This affects sbt-native-packager in version 0.7.4

The init script when run with argument 'status' always returns an exit code 0, no matter in what state the program is in. This is bad, as a caller (e.g. puppet) cannot determine the state of the application. One should change this to exit codes specified by LSB (http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html).

Fixing this can easily be done by remembering the status code of "start-stop-daemon --status" and by exiting using the value of that status code and not by the one resulted from "echo". Unfortunately "$?" is not referential transparent :(

I can do a pull request for this by myself if you like. 
Thanks, Matthias

**Comment by muuki88** [comment]
Thanks for pointing out. Is this not the case for the current `1.0.0` version?
If you do a pr for `0.7.4.` I'll shape a release, otherwise we will only keep this
issue open if this is an issue for `1.0.0` as well. PR always welcome :)

**Comment by huntc** [comment]
Just received from a customer: 

> start script returns 0 even if application failed to start

**Comment by huntc** [comment]
...that's using 1.0.0

**Comment by muuki88** [comment]
@mahe-ymc so pull request on any branch are welcome :)
