### ISSUE TITLE
Unable to build debian package with JDeb in a Play Project

### ISSUE THREAD

**Issue by magnusart** [sbt/sbt-native-packager#553]
Hi

When using OSX we cannot force the debian build to use JDeb when having a play project. When we build it prints:

`Building debian package with native implementation` if we remove the Play plugin dependency we instead get `Building debian package with java based implementation 'jdeb'`.

To avoid using the play version of sbt-native-packager I evicted it from the plugin, but it did not make any difference: `addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.7" exclude("com.typesafe.sbt", "sbt-native-packager"))`

It is easy to reproduce:

### Using test-project-play-rpm
1. In `build.sbt` change from RPM to `enablePlugins(JDebPackaging)`
1. In activator run `debian:packageBin` and you should see the output `Building debian package with native implementation`
1. In `build.sbt` comment out the line `enablePlugins(PlayScala)`
1. In activator run `debian:packageBin` again and you will now see the output `Building debian package with java based implementation 'jdeb'` (not much gets build however).

**Comment by muuki88** [comment]
Duplicate with #407 #499
