### ISSUE TITLE
Error in Docker Plugin Force Latest Parameter Sequence?

### ISSUE THREAD

**Issue by AshleyAitken** [sbt/sbt-native-packager#555]
Howdy All,

I'm pretty much a beginner at all of this so please understand if this is incorrect.
I am trying to force the "latest" tag in docker native packager and it seems to fail all the time.

I believe this line in `DockerPlugin.scala` [Line 288](https://github.com/sbt/sbt-native-packager/blob/f60e1a43ef44473b5e34f18cdf76162b88113ab9/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L288)

```scala
val latestCmd = Seq("docker", "tag", "-f", tag, name)
```
should be
```scala
val latestCmd = Seq("docker", "tag", "-f", name, tag)
```
i.e. sequence of name and tag is incorrect.
If this is an error is it possible to fix please (or do I need to submit a pull request etc).
Thanks,
Ashley.

**Comment by muuki88** [comment]
`docker tag --help` says (and [docs](https://docs.docker.com/reference/commandline/cli/#tag))

```bash
Usage: docker tag [OPTIONS] IMAGE[:TAG] [REGISTRYHOST/][USERNAME/]NAME[:TAG]
```

[Examples](http://docs.docker.com/userguide/dockerimages/#setting-tags-on-an-image) show that `id` comes first and then the tag:

```bash
$ sudo docker tag 5db5f8471261 ouruser/sinatra:devel
```

So I think this should work as we have [tests](https://github.com/sbt/sbt-native-packager/tree/master/src/sbt-test/docker/update-latest) for this as well.

**Comment by AshleyAitken** [comment]
Sorry @muuki88  I was confused by that, you are right.

**Comment by muuki88** [comment]
No problem :)
