### ISSUE TITLE
Evaluate Spotify DockerClient

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#558]
The [Spotify Docker Client](https://github.com/spotify/docker-client) seems to be
written purely in java and could hopefully be used without docker installed locally.

**Comment by gbougeard** [comment]
Did you abandon this idea or maybe you did not have the time to try it?

**Comment by muuki88** [comment]
Hadn't had the time yet!

**Comment by gbougeard** [comment]
I'm trying right now. Looks good so far
Le 29 août 2015 12:16 AM, "Nepomuk Seiler" <notifications@github.com> a
écrit :

**Comment by muuki88** [comment]
Awesome! Looking forward :)
