### ISSUE TITLE
[sbt-native-packager 1.0.0] [play 2.3.8] Debian package installation uses wrong user to start

### ISSUE THREAD

**Issue by MeiSign** [sbt/sbt-native-packager#560]
I am creating a debian package of my Scala Play 2.3.8 application with the sbt native packager (`"com.typesafe.sbt" % "sbt-native-packager" % "1.0.0"`). The SystemV startscripts that are being generated use a custom user to start and stop the app which is exactly as intended.
The problem is, that the installation with `dpkg -i package.deb` seems to start the app directly after the installation as root user. The `/var/run/neeedo-app/running.pid` is then owned by the root user and all further stop or start attempts fail because this file cant be overwritten by the daemon user.

This is my build.sbt:

    import com.typesafe.sbt.SbtNativePackager._
    import NativePackagerKeys._
    import com.typesafe.sbt.packager.archetypes.ServerLoader.SystemV

    name := """neeedo-api"""

    version := "1.0-SNAPSHOT"

    scalaVersion := "2.11.1"

    maintainer in Debian := "neeedo-team <neeedo@neeedo.com>"

    packageSummary in Debian := "neeedo api application"

    serverLoading in Debian := SystemV

    packageDescription := "neeedo api application"

    daemonUser in Linux := neeedo-api

    daemonGroup in Linux := neeedo-api

I am running the dpkg install command also with the neeedo-app user. I don't understand why the running.pid file is created by the root user after installation. If I delete the file manually with sudo and use the start/stop script afterswords everything works fine.

Is this an issue with the deb package building process or is something wrong with my server environment? I can't figure it out. Help appreciated.

**Comment by muuki88** [comment]
That's very interesting as the `postinst` script uses the same facilities to start the service:

- [postinst for systemV](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/debian/postinst-template)
- [loader functions for systemv](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/loader-functions)

What OS are you running on?

**Comment by MeiSign** [comment]
Ubuntu 14.04.2 LTS

**Comment by muuki88** [comment]
And you start the service with 
`sudo service neeedo start` ?

**Comment by MeiSign** [comment]
Actually I start the application with /etc/init.d/neeedo-api start
When i use sudo service neeedo start the pid file gets created with the root user. That might explain this issue but its still not clear to me. Since I am using SystemV I should use the /etc/init.d/ script right?

**Comment by muuki88** [comment]
Hm. With `systemv` you are supposed to use the `service` command. Running the `/etc/init.d` script shouldn't be the way to go. I'll try this when I get time.

Can you use the default `upstart` systemloader?

**Comment by kardapoltsev** [comment]
Actually it shouldn't be a problem since `/var/run/app_name` is owned by daemon user and this user is able to delete running.pid inside this directory.
Your program actually not started as root. Owner of `running.pid` and `daemon-user` isn't the same.
When you run `sudo service app_name start` or `sudo /etc/init.d/app_name start` then script will be executed as root, `start-stop-daemon` create running.pid also as root but start your program as `daemon-user`.
Could you please show what exactly errors you have?

**Comment by MeiSign** [comment]
I will try to create a smaller example project today. And I will also try to use upstart systemloader. Thanks for your help today.

**Comment by MeiSign** [comment]
Ok I think I understand the issue now. The problem why the files are created by the root user is probably because I have to run dpkg with sudo and all further scripts invoked by this installation are then also run as root user. This explains why the running.pid file is then owned by root.

**Comment by MeiSign** [comment]
I finally found the solution to my problem the issue can be closed. Sorry for the inconvenience the native packager is working correctly.

My application is using environment variables in its config and when you run the start script with sudo as root user you have different environment variables. This led to the fact the the app couldn't start and unfortunately no error reporting was visible (I have to investigate further to see why because normally this should be reported).

Thanks for your help...

**Comment by muuki88** [comment]
thanks for sharing :)
