### ISSUE TITLE
Rkt container support

### ISSUE THREAD

**Issue by magnusart** [sbt/sbt-native-packager#561]
CoreOS guys are creating an [open container format (ACI)](https://github.com/appc/spec/blob/master/SPEC.md) in several ways similar to Docker but also with key differences in their security model etc.

Their own [runtime implementation is caller Rkt](https://github.com/coreos/rkt), while it is still young it would be very cool if sbt-native-packager got support for it in the future.

There is more information around Rkt at [CoreOS docs site](https://coreos.com/docs/) (scroll down and look at the left side).

Introduction video (might be a bit outdated): https://www.youtube.com/watch?v=E9WVjxaRkKU

**Comment by muuki88** [comment]
duplicate with #557
