### ISSUE TITLE
Akka application packaging with logger

### ISSUE THREAD

**Issue by salex89** [sbt/sbt-native-packager#565]
Sbt-native-packager version: 0.8.0-M2
sbt version: 0.13.5
Akka version: 2.3.9
I'm having issues configuring the logging with the akka_application packaging. In my IDE everything works fine, and when the application is run with `activator run`. But when packaged, the logger configuration is ignored and everything is set to DEBUG, and used some other format, different from what I specified. Also, I see messages about multiple slf4j bindings present. I'm using akka-slf4j and logback (logback.xml is set in the classpath). 

To be clear, I first run the `sbt stage` task, and then run the generated bash script.

Some configuration missing?

Maybe not the right place to ask, but is there any pro/con between using akka_application packaging or just `activator run` in production?

From applicaiton.conf:

    akka {
       loggers = ["akka.event.slf4j.Slf4jLogger"]
       loglevel = "DEBUG"
       logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
    }

logback.xml

<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="warn">
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>

build.sbt:

    packageArchetype.akka_application
    libraryDependencies += "com.typesafe.akka" %% "akka-slf4j" % "2.3.9" % "compile"

    libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.0.13"

    //Other dependencies
    libraryDependencies ~= {
      _.map(_.exclude("org.slf4j", "slf4j-log4j12"))
    }   

    //~~ SBT native packager settings ~~//
    mainClass in Compile := Some("com.nissatech.mca.worker.Launcher")

**Comment by salex89** [comment]
Update: This could be close, if there is no interest. I solved it by using the native packager 1.0.0 and the JavaApp Archetype.

**Comment by muuki88** [comment]
Sweet. I would have suggested using `1.0.0` and if not possible `0.8.0`.
