### ISSUE TITLE
default mainClass not picked up

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt-native-packager#568]
My module has multiple classes containing a main method. The documentation mentions this:
`This archetype will use the mainClass setting of sbt (automatically discovers your main class) `

So I tried all kinds of things like:
```
    mainClass in (Compile, run) := Some("foo.bar.Main"),
    mainClass in (Compile, packageBin) := Some("foo.bar.Main"),
    mainClass in Universal := Some("foo.bar.Main")
```

The first one works for `run` and `re-start` but the packager is not picking up the default main class. The binaries are missing and I always get this logged:

` Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list`

(I'm using a multi-module build, this module is has `enablePlugins(JavaAppPackaging)`)

**Comment by muuki88** [comment]
Setting the mainClass like this?

```scala
mainClass in Compile := Some("foo.bar.Main"),
```

If this doesn't help, can you provide a small example project demonstrating the issue?

**Comment by francisdb** [comment]
Ok, now I feel stupid. Just tried this and it works. Maybe something to add to the docs?

**Comment by muuki88** [comment]
no problem ;) actually you used the most specific configuration possible. SBT beginners normally don't know this. Configuring on Configuration and Task axis. 

What are you trying to achieve? Normally you should have one entry point in your application. If you have different application, splitting them up in submodules is usually the best way as sbt configures most of the stuff itself.

However a small section on [Advanced Topics](http://www.scala-sbt.org/sbt-native-packager/topics/index.html) wouldn't hurt. Do you have time for a small pull request on the topic?

**Comment by francisdb** [comment]
In fact the second main class in my application was inherited from some library. I do have multiple modules with each it's own java app / server and if I remember correctly I had a problem with the sbt-revolver plugin in the past and as a solution for that I added the (Compile, run)

Anyway it all works perfectly now. I'll submit a small patch for the docs. No need for a advanced topic?

**Comment by muuki88** [comment]
awesome :)

**Comment by francisdb** [comment]
oops, there's a typo, produces instead of produced
