### ISSUE TITLE
sbt-native-packager docs

### ISSUE THREAD

**Issue by bkeyoumarsi** [sbt/sbt-native-packager#574]
Hi,

Great tool! 

One discrepancy in the docs here: http://www.scala-sbt.org/sbt-native-packager/formats/rpm.html#scriptlet-changes

To replace the scriptlets the names are actually: (preinst, postint, preun, postun) according to the source code.

Thanks

**Comment by bkeyoumarsi** [comment]
Also it would great to add support to add more RPM sctiptlets to the SPEC like pretrans

**Comment by muuki88** [comment]
Thanks. Would you mind writing a pull request for the docs?

**Comment by muuki88** [comment]
If you need other scriptles feel free to provide pull requests. Supporting those different build tools is very maintenance heavy, so we are happy to accept any new feature if it's needed by users :)
