### ISSUE TITLE
scriptlets in rpm .spec file are duplicated

### ISSUE THREAD

**Issue by bkeyoumarsi** [sbt/sbt-native-packager#575]
After you run rpm:packageBin, if you take a look at the target/rpm/SPECS/${{app_name}}.spec file you can see that all sciptlets including %pre %post, etc. are duplicated. 

What I mean is that for example, the %pre script is printed twice in the .spec file.

I would appreciate it if you could take a look at this and issue a fix if possible.

Thanks

**Comment by muuki88** [comment]
Can you provide a sample project for this? The `test-project-simple` produces a valid output.
