### ISSUE TITLE
Using custom postinst script with JavaServerAppPackaging overrides maintainer one

### ISSUE THREAD

**Issue by Tolsi** [sbt/sbt-native-packager#576]
[Here in docs](http://www.scala-sbt.org/sbt-native-packager/formats/debian.html#id7) written: `If you use the packageArchetype.java_server there are predefined postinst and preinst files, which start/stop the application on install/remove calls. Existing maintainer scripts will be extended not overridden.`

`packageArchetype.java_server` is deprecated, i use `enablePlugins(JavaServerAppPackaging)`, but my `src/debian/DEBIAN/postinst` overrides exists maintainer `postinst ` script.

How I can extend the maintainer `postinst`?

**Comment by muuki88** [comment]
sorry for the late reply. We are planning to align rpm/debian so both use a simple api where you can extend/override existing scripts in the same fashion. For now you have to to a bit sbt-foo.

```scala
// extending the postinst script
debianMakePostinstScript := {
  // you can actually place it anywhere
  val tmp = (target in Universal).value / "tmp" / "bin"
 
  // get the preexisting one or create a new
  val postinst = debianMakePostinstScript.value.getOrElse(tmp / "postinst")

  // write stuff
  IO.write(postinst, """echo "nice one!"""", append = true)
  Some(postinst)
}
```

I have not tested this, but should work.
