### ISSUE TITLE
Binary broken when run in path with spaces

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt-native-packager#577]
Built a zip built with `universal:packageBin` on a sbt project with

```
.enablePlugins(JavaAppPackaging)
.enablePlugins(LauncherJarPlugin)
```

I extracted the resulting zip into `/Users/me/My Downloads/myapp`.
When starting the binary in OS X I get the following error:

```
Error: Invalid or corrupt jarfile /Users/me/My
```

(other ways of packaging and other operating systems might also have this issue

**Comment by muuki88** [comment]
This is interesting. We have tests for this, so this could be a configuration or system issue. Can you share a sample project?

cc @jroper

**Comment by francisdb** [comment]
I think the bug is here when adding `-jar ...`:
https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/jar/LauncherJarPlugin.scala#L45

**Comment by muuki88** [comment]
Is jar name wrong?

**Comment by francisdb** [comment]
no but probably need quotes as `$lib_dir` might contain spaces

**Comment by muuki88** [comment]
Can you provide a pr with a regression test for this?

**Comment by francisdb** [comment]
can you point me to the tests that already test this folder with spaces stuff?

**Comment by muuki88** [comment]
Sure :)

https://github.com/sbt/sbt-native-packager/tree/master/src/sbt-test/jar/launcher-jar

There's a wiki page explaining how to run the tests. Basically it's 
`sbt "scripted jar/*" `

**Comment by francisdb** [comment]
Ok, tried to reproduce this and force the test scripts to use a target/stage folder containing spaces but did not get there. Asserts were still expecting default target/stage folders.

The only solution I found to reproduce the issue is renaming
`src/sbt-test/jar/launcher-jar/`
to
`src/sbt-test/jar/launcher jar/`

but so far no luck on fixing the bash script, quotes don't help as then I get this:

```
error: Unable to access jarfile "/Users/me/My
```

**Comment by muuki88** [comment]
So there needs to be a more sophisticated way of dealing with whitespaces on
windows? For testing you can do the following steps

- go to `test-project-simple` ( in the root folder of sbt-native-packager project)
- add all the settings from `sbt-test/jar/launcher-jar/` you need
- make the build fail in this test project
- change the windows plugin and test with the `test-project-simple` (if you keep the sbt console open you may have to type reload before testing)
- if everything works, create a new test next to `launcher-jar`, e.g. `launcher-jar-whitespaces` and add the settings from the `simple-test-project`
- see if the tests work
- check in everything, but the simple-test-project

**Comment by francisdb** [comment]
It's not on windows but macosx / linux I have this problem and I have a way to break the test by copying `launcher-jar` to `launcher jar`. I currently have not found a solution for providing a path with spaces to `java -jar ...` in the sh file.
I don't have a windows machine at hand to test this but might have similar problem.

**Comment by muuki88** [comment]
> It's not on windows but macosx / linux
Ah sorry, confused it with another issue. However you can test it on windows as well (only if you have time). 

>  I currently have not found a solution for providing a path with spaces
there are no solutions for  this on the internet? If this is really not possible, then we should add docs for it.

**Comment by francisdb** [comment]
Just give me some time :-p

**Comment by muuki88** [comment]
You have all in the world ;)

**Comment by francisdb** [comment]
patch on it's way, just upped my bash skills and know how to fix this :-)

**Comment by francisdb** [comment]
@muuki88 just to confirm that the bat file is also broken on windows, looking into it

**Comment by metasim** [comment]
@muuki88 I see you closed it, but can't figure out how it was fixed. I'm having this problem on windows with a Play app.

**Comment by muuki88** [comment]
That's weird. There is a fix with passing test. Either it's a regression, a different bug or the tests where not exhaustive.

**Comment by metasim** [comment]
I ended up enabling `LauncherJarPlugin` and things worked. When I have a moment, do you want me to go back and log the error when that plugin *isn't* enabled?
