### ISSUE TITLE
DebianDeployPlugin publishes only changes

### ISSUE THREAD

**Issue by jastice** [sbt/sbt-native-packager#587]
I have a project with DebianPlugin, JavaServerAppPackaging, DebianDeployPlugin.
When running `debian:PublishLocal`, it will correctly build a deb, but only the changes are published to the local repo.

When I manually add the settings via `SettingsHelper.makeDeploymentSettings(Debian, packageBin in Debian, "deb")`, it will publish the deb, but not the changes. It appears that the settings for `deb` and `changes` overwrite each other.

In my case, this is a multi-module project and the plugins are applied only to one of the modules. If I have time, I will also make a minimal project to reproduce.

**Comment by oddietaco** [comment]
I am experiencing this issue as well. Is there any update on it, or a known workaround?

**Comment by muuki88** [comment]
Could you try `JDebPackaging`? You can also inspect the `debian:mappings` with both settings and see if there's a difference. Sorry that it took me so long to answer :(

**Comment by oddietaco** [comment]
I am using JDebPackaging currently. I will inspect the debian:mappings and
post my discoveries.

On Fri, Jan 22, 2016 at 10:31 AM, Nepomuk Seiler <notifications@github.com>
wrote:

> Could you try JDebPackaging? You can also inspect the debian:mappings
> with both settings and see if there's a difference. Sorry that it took me
> so long to answer :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbt/sbt-native-packager/issues/587#issuecomment-173951385>
> .
>



-- 
Benedictus qui venit in nomine Domine

**Comment by eed3si9n** [comment]
I just hit this with sbt 0.13.15 - https://github.com/sbt/sbt/issues/3096.

DebianDeployPlugin wipes out the Artifact for "deb" when it adds "changes". That's the problem.
The workaround is to add:

```
mport com.typesafe.sbt.packager.SettingsHelper._
addPackage(Debian, packageBin in Debian, "deb")
```
