### ISSUE TITLE
Windows doc page has many RPM / Linux references

### ISSUE THREAD

**Issue by akauppi** [sbt/sbt-native-packager#590]
http://www.scala-sbt.org/sbt-native-packager/formats/windows.html

It looks like valid documentation, but then there's "A rpm package needs.." and it gets confusing.

Since I'm in the need of the documentation myself, I'm unable to fix this. If the docs are half-baked it's way better to just say so. Remove the RPM copy-paste remnants.

After 'Settings' it gets back to Windows, again. Strange.

**Comment by muuki88** [comment]
Thanks for pointing this out :)
