### ISSUE TITLE
documentation for Build.scala files

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-native-packager#593]
In the docs http://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/index.html  `enablePlugins(JavaAppPackaging)` is recommended. But this only works for `build.sbt` style projects. what is the correct magic for `Build.scala` style projects?

**Comment by muuki88** [comment]
AFAIK `AutoPlugins` only work with `build.sbt` files together. There is no way I know to get around this (yet). I know this is a pain when migrating from `Build.scala` builds to `*.sbt` builds :(

cc @jsuereth

**Comment by fommil** [comment]
So support for `.scala` style projects is deprecated?

**Comment by fommil** [comment]
by fiddling around, I've worked out that adding this at the top

```scala
import com.typesafe.sbt.packager.archetypes.JavaAppPackaging
import JavaAppPackaging.autoImport._
```

and this to a module

```scala
  enablePlugins (
    JavaAppPackaging
  )
```

seems to allow me to type `stage`. And the keys seem to be available (but I cannot confirm if they work).

**Comment by kardapoltsev** [comment]
You could take a look here [example of Build.scala](https://github.com/kardapoltsev/web-gallery/blob/master/project/Build.scala) with autoplugins and some additional configuration

**Comment by muuki88** [comment]
I'm not sure if `*.scala` is deprecated (though it gets more and more discouraged).

**Comment by muuki88** [comment]
@fommil I would close this as at this point we have no way to solve this?

**Comment by fommil** [comment]
This is just an RFE for better documentation, I'm sure that **can** be fixed... although whether it **will** be fixed is another question.

**Comment by muuki88** [comment]
Actually I'm pretty happy, when `Build.scala` will go away. As a beginner I was really confused, when to use what and why. Still I can understand the issue, when a project is heavily relying on this and all of a sudden you will have to change anything.

**Comment by fommil** [comment]
I will kick up a massive fuss if they try to remove `Build.scala`. It's the only thing that makes sense to me... the `.sbt` files are total voodoo and completely useless if you want to do anything non-standard.

**Comment by muuki88** [comment]
I will close this ticket for now as "how to use Build.scala with AutoPlugins" is as an SBT concern and not sbt-native-packager. Feel free to provide a PR, when there are docs available.
