### ISSUE TITLE
javaOptions should not come after mainclass 

### ISSUE THREAD

**Issue by woshilaiceshide** [sbt/sbt-native-packager#598]
to reproduce the bug with sbt-native-packager(1.0.2) in a give sbt project, 
1. in project/plugins.sbt: 
addSbtPlugin("com.typesafe.sbt" % "sbt-aspectj" % "0.10.2")
2. in build.sbt: 
javaOptions in Universal ++= (AspectjKeys.weaverOptions in Aspectj).value
3. type "dist"
4. in the target/universal/xxx-xxx.zip/bin/xxx, we will find that "-javaagent:.../aspectjweaver-1.8.5.jar" is fed to mainclass as the application's argument, which is not expected.

I use the following statement in build.sbt as a workaround:
bashScriptExtraDefines += s"""addJava "${(AspectjKeys.weaverOptions in Aspectj).value.mkString(" ")}""""

**Comment by woshilaiceshide** [comment]
the workaround mentioned in the previous is wrong, use the following: 
bashScriptExtraDefines ++= (AspectjKeys.weaverOptions in Aspectj).value.map("addJava " + _)

**Comment by muuki88** [comment]
Sorry, this was a point of missing documentation. Prefixing arguments with `-J` makes the start script recognize these as jvm arguments. So in your case

```scala
javaOptions in Universal ++= (AspectjKeys.weaverOptions in Aspectj).value.map { prop =>
   "-J" + prop
}
```

I know this is counter-intuitive to what `javaOptions` means. However it's better than the
`bashScriptExtraDefines` IMHO.

**Comment by woshilaiceshide** [comment]
why not make javaOptions goes before mainClass automatically?
"javaOptions" implies "java's options, not app's options".

**Comment by muuki88** [comment]
I agree that this is a bit confusing. We kept it this way as the configuration files worked the same way before. So you don't have to change anything.

An additional setting `appOptions` would be appropriate. If you want to do a pull request? However I'm not sure how much this feature is used and how big the impact would be.

**Comment by woshilaiceshide** [comment]
I WILL make a pull request, in which the javaOptions will be "java's options", and "appOptions" will be "app's options".
This will be happen after this busy week.

**Comment by muuki88** [comment]
Awesome @woshilaiceshide :)

It would be really awesome if previous `javaOptions in Universal` configurations would still work.
The easiest way would be to alter (prefixing with `-J`, beside some exceptions, see bashscript) the settings before they get written to the `application.ini` file. 

A new `appOptions` setting would then be written unchanged. I hope we can keep things backwards compatible and don't have to touch the bashscript *and* avoid using the `bashScriptExtraDefines`

**Comment by woshilaiceshide** [comment]
I am very sorry for the above promise.
If you do not mind, should I delay my pull request for some weeks. 
My busy days make my time fly recently.
Your reply is expected.

**Comment by muuki88** [comment]
That's no problem. Just ping when you need any help after you started :)

**Comment by kayvank** [comment]
I had a similar issue and using the suggesion above resolved it.
javaOptions in Universal ++= (AspectjKeys.weaverOptions in Aspectj).value.map { prop =>
  "-J" + prop
}

**Comment by muuki88** [comment]
Thanks for sharing :)
