### ISSUE TITLE
application.ini doesn't get replacements such as ${{app_name}}

### ISSUE THREAD

**Issue by knshiro** [sbt/sbt-native-packager#599]
Unlike specified in these pages,
http://www.scala-sbt.org/sbt-native-packager/archetypes/java_server/customize
https://github.com/sbt/sbt-native-packager/blob/master/src/sphinx/topics/play.rst
`application.ini` doesn't get anything replaced (with and without play)
To try just create a basic project with what is suggested in https://github.com/sbt/sbt-native-packager/blob/master/src/sphinx/topics/play.rst

**Comment by muuki88** [comment]
Hi @knshiro . Yeah, that's true and a miss documentation. We will remove this from the docs and see if we should add this. We recommend using the `build.sbt` approach, e.g.

```scala
javaOptions in Universal ++= Seq {
 "-Dhttp.port=8080",
 "-Dapp.user=user",
 s"-D.app.version=${version.value}"
}
```

This approach is a lot more flexible as you no longer depend on magic string-replacements, but use your variables directly as they are.
