### ISSUE TITLE
Play pid is a big caveat for people starting using sbt-native-packager.

### ISSUE THREAD

**Issue by knshiro** [sbt/sbt-native-packager#602]
This line is everywhere in the documentation:
`-Dpidfile.path=/var/run/${{app_name}}/play.pid`
And usually is said to be added to `src/universal/conf/application.ini` whereas play actually uses `dist/conf/application.ini` and the `${{app_name}}` is also not replaced.
So I was actually thinking about making a pull request to `play-sbt-plugin` but I realise you don't want a 

```
bashScriptExtraDefines += s"""addJava -Dpidfile.path=/var/run/${app_name}/play.pid"""
```

there by default because `/var/run` doesn't always exists.

I think this could be solved by having a new folder in `app_home` called `run` with the right permission that could be linked to `/var/run/app_name` for the right packagers. Then `play-sbt-plugin` could add

```
bashScriptExtraDefines += s"""addJava -Dpidfile.path=${app_home}/../run/play.pid"""
```

**Comment by muuki88** [comment]
> This line is everywhere in the documentation

That's true. And a big issue for everybody deploying play the first time.

> I think this could be solved by having a new folder in `app_home`

This solution would definitely work. The big question here is, where to put this.

### sbt-play-plugin

Putting the `links`, `templateFolders` and `bashScriptExtraDefines` inside the play plugin.
This means a tighter coupling of both plugins and fixes have to be made on the play side.

### sbt-native-packager

We could create a specific plugin like `LocalPidPluging` that adds the suggested settings for different kind of packaging formats. However we would need an additional setting for the _pid app parameter_ name, e.g. `pidParameter := "-Dpidfile.path`.

WDYT?

**Comment by knshiro** [comment]
For me it feels like other folders are treated the same way by adding a folder in the `/usr/share/<app_name>`  and a link to the different folders of the system except the `run` folder. I think it should be treated the same way. This way there wouldn't be a need for a specific `LocalPidPlugin` and the adaptation of the `sbt-play-plugin` would just be a one liner `bashScriptExtraDefines`

**Comment by muuki88** [comment]
You are right. I was thinking too complicated. This should work smoothly. The challenge will be to make all bash scripts work smoothly:

- [debian systemv](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-debian-template#L21)
- [debian systemv creating folder](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-debian-template#L21). This is because on debian `/var/run` is a tmpfs

**Comment by francisdb** [comment]
see also https://github.com/sbt/sbt-native-packager/issues/607

**Comment by muuki88** [comment]
Closing this as play as extensive documentation on the deployment configuration

- https://www.playframework.com/documentation/2.6.x/ProductionConfiguration#Changing-the-path-of-RUNNING_PID
- https://www.playframework.com/documentation/2.6.x/Deploying#Play-PID-Configuration
