### ISSUE TITLE
How to force RPM v3 signature?

### ISSUE THREAD

**Issue by 2rs2ts** [sbt/sbt-native-packager#616]
I used the rpm plugin to generate an RPM on my Mac, but usually I do it in a CentOS 5 VM. When I went to install the rpm in the CentOS 5 VM I got this error: 

```
error: myapp-latest.noarch.rpm: Header V4 RSA/SHA1 signature: BAD, key ID 44ea73ae
error: myapp-latest.noarch.rpm cannot be installed
```

I found [this guide](http://adminotes.blogspot.fr/2011/12/centos-6-rpm-sign-problem-v4-signatures.html) which is supposed to force v3 signatures but I'd rather not rely on modifying the local environment if there's a way to do it via the rpm plugin. So... is there a way?

P.S. the guide I found is all about gpg but I didn't realize that the rpm plugin signed the rpms.

**Comment by muuki88** [comment]
The RPM Plugin doesn't sign the rpms (even though we prepared everything to do so).
If you set your sbt logging to debug, you can take a look at the rpm command that is used
to build the package. Then you can try to execute it manually and see what may fix this issue.

**Comment by 2rs2ts** [comment]
The command it is using is

```
rpmbuild -bb --target noarch-PayPal-Linux --buildroot /Users/2rs2ts/src/my-app/my-app/target/rpm/buildroot --define _topdir /Users/2rs2ts/src/my-app/my-app/target/rpm --define _tmppath /var/folders/gp/l9gt6r791p1bdcgtf2b2dppw392tbp/T/sbt_8f0f0597 myapp.spec
```

No `--sign` there, which aligns with what you said. I guess this boils down to something about my rpm installation. Thanks.

**Comment by muuki88** [comment]
We are testing only on _rpm v4_, so I really can't say anything about v3. However we have random issues with rpm. Mostly on MacOSX because different scriptlet settings.

**Comment by 2rs2ts** [comment]
Thanks. For what it's worth, I am pursuing help on StackOverflow about this. The result of my endeavors may help others, so I'll include [the link](http://stackoverflow.com/questions/24376547/rpm-installation-error-header-v4-rsa-sha1-signature-bad-key-id).
