### ISSUE TITLE
Extend docs for sbt-aether and sbt-native-packager

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#617]
See [Stackoverflow question](http://stackoverflow.com/questions/23147029/using-sbt-aether-deploy-with-sbt-native-packager)

**Comment by shuklara** [comment]
Not able find the proper way to handle this where are the docs ?

**Comment by muuki88** [comment]
There aren't. I closed this ticket as it was inactive and there are still some suggestions on SO how to handle this. If you find an appropriate solution, I'm happy to merge a pull request.
