### ISSUE TITLE
relocatable RPMs?

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-native-packager#618]
I couldn't find any information about this at http://www.scala-sbt.org/sbt-native-packager/formats/rpm.html

It would be really great if the output RPM could support relocatable RPMs, e.g. so that end users could install servers in /opt

Is this something that could be supported?

**Comment by fommil** [comment]
doh! I'm blind. It's there. I must have been searching from after the mention.

**Comment by muuki88** [comment]
Always glad to help Sam ;)
