### ISSUE TITLE
hardcoded RPM log directory

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-native-packager#619]
In

https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemv/start-rpm-template#L43

```
RUN_CMD="$exec >> /var/log/${{app_name}}/daemon.log 2>&1 &"
```

but the packager may have provided a custom log directory, which should be preferred.

**Comment by fommil** [comment]
uugh, I was going to send you a quick PR on this but it's more involved than I thought. The logs directory needs to be available in the default replacements list and changing that looks like a big faff.

Workaround is to use a custom script, of course.

**Comment by muuki88** [comment]
Currently I'm working on a major refactoring of the `maintainerScripts`. After that, it should be a lot easier.

**Comment by giampaolotrapasso** [comment]
Any forecast about the resolution of this?

**Comment by muuki88** [comment]
Unfortunately not. #625 is almost done, but needs some clean up. And then lets see if there is a good way fixing this.

**Comment by louisq** [comment]
I was not aware that a issue was opened for this, but the #675 pull request addresses the custom log directory

**Comment by muuki88** [comment]
ah, thanks :)
