### ISSUE TITLE
RPM install fails on RHEL 5

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-native-packager#621]
I tried installing an RPM from this plugin and got this error

```
Creating system user: mdes in mdes with mdes user-daemon and shell /bin/false
useradd: unknown group mdes
Error in PREIN scriptlet in rpm package mdes-1.0.0_SNAPSHOT-1.noarch
error: %pre(mdes-1.0.0_SNAPSHOT-1.noarch) scriptlet failed, exit status 6
error:   install: %pre scriptlet failed (2), skipping mdes-1.0.0_SNAPSHOT-1
Installed products updated.
```

It looks like the `mdes` group is not being created before attempting to create the user `mdes`.

Actually I'm happy with `root`... but please tell me you don't try to delete the user/group on uninstall!

**Comment by muuki88** [comment]
[preinst-template](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/rpm/preinst-template) has the correct order

**Comment by fommil** [comment]
```
Creating system group: mdes
groupadd: unrecognised option `--system'
Usage: groupadd [options] group

Options:
  -f, --force			force exit with success status if the specified
				group already exists
  -r,                       create system account
  -g, --gid GID			use GID for the new group
  -h, --help			display this help message and exit
  -K, --key KEY=VALUE		overrides /etc/login.defs defaults
  -o, --non-unique		allow create group with duplicate
				(non-unique) GID

Creating system user: mdes in mdes with mdes user-daemon and shell /bin/false
useradd: unknown group mdes
Error in PREIN scriptlet in rpm package mdes-1.0.0_SNAPSHOT-1.noarch
error: %pre(mdes-1.0.0_SNAPSHOT-1.noarch) scriptlet failed, exit status 6
error:   install: %pre scriptlet failed (2), skipping mdes-1.0.0_SNAPSHOT-1
Warning: scriptlet or other non-fatal errors occurred during transaction.
```

**Comment by fommil** [comment]
this is on RHEL 5 so maybe the `groupadd` interface has changed?

**Comment by muuki88** [comment]
Wow, indeed. That is actually pretty nasty.

**Comment by fommil** [comment]
I'm guessing the `--system` flag did a bunch of useful stuff that you're relying on.

**Comment by muuki88** [comment]
AFAIK this only affects the UID range being used. Systemusers are defined in a different range. Besides that, nothing I know about.

**Comment by fommil** [comment]
ok, I'll try out tomorrow with `--system` removed and let you know. If you're looking at this in a docker of RHEL5 (or old fedora/arch) or something, that would be awesome please let me know.

**Comment by fommil** [comment]
I have tried working around this by creating overrides in `src/debian/DEBIAN/control-functions` and `src/rpm/scriptlets/preinst-template` but they are not being picked up. Am I using the correct directory and filename?

**Comment by fommil** [comment]
`control-functions` is a replacement, not a template, so after trying to work out the correct file to put into `src/rpm` the only workaround I could come up with was

```scala
    linuxScriptReplacements := {
      val orig = linuxScriptReplacements.value.toMap
      orig ++ Seq(
      // WORKAROUND https://github.com/sbt/sbt-native-packager/issues/621
      ("control-functions", orig("control-functions").replace(" --system", ""))
    )}.toSeq,
```

if I need to customise that `control-functions` value any further I'm going to have to have my own template and load it from disk at this point.

**Comment by fommil** [comment]
```
--no-create-home
```
also not supported on RHEL 5
