### ISSUE TITLE
bin access to script replacements

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-native-packager#622]
in the universal `bin` folder, it would be great to have access to the script replacements, e.g. classpath and a few other bits and bobs.

http://www.scala-sbt.org/sbt-native-packager/formats/universal.html

As a workaround, one can call out to `find` and source the `/etc/defaults` file

**Comment by muuki88** [comment]
The current way to do this is using [bashScriptExtraDefines](http://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/customize.html?highlight=bashscriptextradefines#bashscript-defines). You can add arbitrary bash stuff there.

However what you want to do is, create a complete new bashscript and have access to the replacements, right?

**Comment by fommil** [comment]
yes, that's right. Solid example: I have a service that I'm deploying and the run book looks like this:

1. install the software
2. run the database evolution script
3. start the service
4. (wait for some log message)
5. run the migration script

both scripts are separate, but would benefit greatly from having access to the classpath and other variables. As it is, I hack it by adding this:

```bash
cd "`dirname $0`/../"

[ -e /etc/default/NAME ] && . /etc/default/NAME
[ -e /etc/sysconfig/NAME ] && . /etc/sysconfig/NAME

CLASSPATH=`find lib -mindepth 1 -maxdepth 1 -type f -name "*.jar" | tr '\n' ':'`
```

to my scripts.
