### ISSUE TITLE
groupadd: unrecognized option `--system'

### ISSUE THREAD

**Issue by kardapoltsev** [sbt/sbt-native-packager#630]
I've got this error on `CentOS release 5.10 (Final)`. 
Should this option be removed from rpm preinstall or I need to create custom preinstall script?

**Comment by kardapoltsev** [comment]
CentOS:
` -r This flag instructs groupadd to add a system account.  The first available gid lower than GID_MIN will be automatically selected unless the -g option is
          also given on the command line. This is an option added by Red Hat.`
Debian:
`-r, --system
Create a system group. The numeric identifiers of new system groups are chosen in the SYS_GID_MIN-SYS_GID_MAX range, defined in login.defs, instead of GID_MIN-GID_MAX.`

May be replace long option (`--system`) with short one (`-r`)?

**Comment by muuki88** [comment]
Agreed. Can you make a pr?

**Comment by muuki88** [comment]
Duplicate with #621

**Comment by kardapoltsev** [comment]
Yes, I'll make PR.
