### ISSUE TITLE
Presense of several main classes breaks docker:publishLocal

### ISSUE THREAD

**Issue by cppexpert** [sbt/sbt-native-packager#636]
There are several subtle bugs in docker packager. I'll start with this issue first.

Presense of several main classes breaks `docker:publishLocal`.

Output directory `/target/docker/stage/opt` doesn't have `bin` directory with execution script. Example `build.scala` is here: https://github.com/cppexpert/sbt-docker-example/blob/eaf729a352a667c4637fb800fd6a90725b773235/project/build.scala

**Comment by cppexpert** [comment]
So... after 2 hours of debugging I came to solution that specifying main class in Compile package fixes the issue

```
      mainClass in Compile := Some("AnotherMain"),
```

It would be nice to `sbt-native-packager` to either prompt to choose main class or to fail with error instead of producing non-working docker image.

Thanks !

**Comment by muuki88** [comment]
This is a general thing with SBT. If there are multiple main classes then the 'mainClass in Compile` is `None` because there is no way to determine the "right" main class. 

However a warning would be a nice addition. I keep this issue as a feature request.

**Comment by cppexpert** [comment]
I think missing "bin" folder in produced docker image is a bug. It should not produce it at all if it cannot determine main class.

**Comment by cppexpert** [comment]
Also there is another odd side effect. If one of the projects of multiproject configuration has more than one main class plugin produces `.jar` with javadoc instead of `.class` files.

**Comment by cppexpert** [comment]
Is it fixed ?

**Comment by muuki88** [comment]
Nope, there isn't a warning yet. But there is another ticket where this issue fits in nicely: #633
