### ISSUE TITLE
Overriden `artifactName` produces image with .jar with wrong content

### ISSUE THREAD

**Issue by unoexperto** [sbt/sbt-native-packager#638]
It's probably not plugin's problem per se but nevertheless it took me few hours to understand root cause.

I have overridden `artifactName` in my sbt config. Because of it in certain conditions (couldn't figure out combination of circumstances) `docker:publishLocal` produces image in which `.jar` with classes is overwritten by `.jar` with scaladoc thus causing `ClassNotFound` exception in runtime.

``` scala
      artifactName := { (sv: ScalaVersion, module: ModuleID, artifact: Artifact) =>
        artifact.name + "." + artifact.extension
      },
```

It would be nice to output warning or error in `publishLocal` task.

**Comment by muuki88** [comment]
You are the first with this issue. A small scenario reproducing this would be very helpful.

**Comment by marius-carp** [comment]
@unoexperto did you find a fix for this? It happens to me sometimes and it's annoying. 
I spent a few hours just to reproduce it but I could't.
