### ISSUE TITLE
Ability to specify additional files to JDKNativePackager

### ISSUE THREAD

**Issue by DaveDeCaprio** [sbt/sbt-native-packager#642]
I have additional files (native executables) that I want to include in the installer.  I am currently doing this by adding an additional <fx:fileset> into the generated build.xml, but it would be nice if I could get this in the generated one directly.

**Comment by metasim** [comment]
@DaveDeCaprio Have you tried the `mappings in Universal` setting?

**Comment by DaveDeCaprio** [comment]
Sorry, I didn't see that before.  The default universal mappings are working fine for me.
