### ISSUE TITLE
Issue with file associations in JDKNativePackager

### ISSUE THREAD

**Issue by DaveDeCaprio** [sbt/sbt-native-packager#643]
When I ran the test-project-jdkpackager on windows with JDK 1.8.0_25, it gave me an error that fx:association elements can't be inside an fx:info.  At least according to this page: https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#BCGICFDB it seems that fx:assocation needs to be a top level element.

**Comment by metasim** [comment]
@DaveDeCaprio Would it be possible for you to try this with 1.8.0_40? There were significant improvements/changes with that release. We may need to add a check for the build number in the plugin (I wish Oracle had numbered it 1.8.1).

**Comment by DaveDeCaprio** [comment]
Will test with that later tonight.

**Comment by DaveDeCaprio** [comment]
Just tested with 1.8.0_51 and it worked fine.  That's good enough for me.  I'll close this since there is an easy enough workaround.

**Comment by metasim** [comment]
@DaveDeCaprio Thanks for giving it a try. My memory is that the file associations stuff was added with Build 40.
