### ISSUE TITLE
With JDKNativePackager, src/deploy is not on the classpath in the build.xml

### ISSUE THREAD

**Issue by DaveDeCaprio** [sbt/sbt-native-packager#644]
I am using the JDKNativePackager - it works quite well by the way.  The issues I am posting are minor and are really just about automating the process.  In general, it works great.

By defaults, the src/deploy directory from the project is not included in the build.xml file.  The application icon file works, but if you try to put other things in there they aren't included in the build.

Specifically, I was using the Inno Setup on windows and wanted to include license file and separate bmp for the setup program.  If I manually edit the generated buil.xml to include src/deploy in the classpath it all works.

**Comment by metasim** [comment]
@muuki88  I labeled this as a bug, as I thought it was doing that. 

Hope to work on this soon.

**Comment by muuki88** [comment]
@metasim sure! Looking forward to your pr :)

**Comment by metasim** [comment]
@DaveDeCaprio Before I submit the pull request, would you be open to giving the fix a spin? It's on my fork, on branch `issue/644`:

https://github.com/metasim/sbt-native-packager/tree/issue/644

(Let me know if you need pointers on the trick to use a plugin via a Git repo URI.)

**Comment by DaveDeCaprio** [comment]
Be happy to try it, but yes I need pointers on how to use a plugin from a repo url.

 

Dave

**Comment by metasim** [comment]
@DaveDeCaprio In your `project/plugins.sbt` file, Instead of:

    addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.0.3")

use this:

    lazy val root = Project("plugins", file(".")) dependsOn (packager)

    lazy val packager = uri("git://github.com/metasim/sbt-native-packager#issue/644")

SBT will check out the repo in a temp directory, compile it, and load it as a plugin. It's a pretty sweet feature.

**Comment by metasim** [comment]
@DaveDeCaprio @muuki88 Also note I added a new key `antExtraClasspath` so users can add other paths if there were some reason to do so.

**Comment by DaveDeCaprio** [comment]
That syntax isn't working for me.  I get error:
[error] Nonzero exit code (128): git clone git://github.com/metasim/sbt-native-packager C:\Users\Dave\.sbt\0.13\staging\7aa5c7fbd40da9e0f3b3\sbt-native-packager

I'm on windows (testing a windows installer).

I'm trying to just build manually and use the plugin that way

**Comment by DaveDeCaprio** [comment]
This is working for me great with this version.  Go ahead and issue the pull request.

**Comment by metasim** [comment]
@DaveDeCaprio Very much appreciate you testing it for us.!

**Comment by metasim** [comment]
PR merged via #645.
