### ISSUE TITLE
Unable to correctly name binary

### ISSUE THREAD

**Issue by ehartsuyker** [sbt/sbt-native-packager#649]
I have a project that looks like so as part of a larger build.

```scala
val `my-project` = (project in file("some/dir/my-project")
  .enablePlugins(LinuxPlugin, DebianPlugin, JavaServerAppPackaging)
  .settings(
    name := "my-project",
    organization := "foo.bar",
    version := "1.2.3",
    name in Linux := s"somecompany-${normalizedName.value}",
    packager.Keys.packageName := (name in Linux).value,
    packager.Keys.packageDescription in Linux := "stuff",
    packager.Keys.packageSummary in Linux := "stuff",
    maintainer in Linux := "foo@bar.com",
    mainClass in Compile := Some("some.Class"),
    debianPackageDependencies += "java8-jdk",
    daemonUser in Linux := (name in Linux).value,
    daemonGroup in Linux := (daemonUser in Linux).value,
    bashScriptExtraDefines ++= Seq("stuff", "more", "lol"),
    serverLoading in Linux := Upstart
  )
```
This builds the deb package with `.deb` being named correctly according to the above parameters. The meta data is correct so that if I do an `apt-get install somecompany-my-project`, the correct package is installed on my server. However, the binary is still named `my-project`.

How can I override the name of my binary?

And as a note, whatever I'm doing right now breaks on `apt-get install`.
```
start: Unknown job: somecompany-my-project
somecompany-my-project could not be registered or started
```
I have also tried removing the `LinuxPlugin` and having everything be `key in Debian`, but that fixes nothing.

SBT v0.13.8
Packager 1.0.0

**Comment by muuki88** [comment]
What you are looking for is the `executableScriptName`. There is small [CheatSheet](http://www.scala-sbt.org/sbt-native-packager/archetypes/cheatsheet.html?highlight=executableScriptName) in the docs which lists these things that are commonly customized.

The `LinuxPlugin, DebianPlugin` is acutally redundant. `JavaServerAppPackaging` enables this by default. The `packager.Keys` can be removed as well.

> start: Unknown job: somecompany-my-project
> somecompany-my-project could not be registered or started

For upstart there should be a `/etc/init/somecompany-my-project.conf`. All under `DEBIAN/*` should contain the correct upstart script conf name `somecompany-my-project`. You can check this by looking into the builded deb package. If not, this is a bug.

**Comment by ehartsuyker** [comment]
The above fixes the naming for the binary, but through renaming the keys like above, I was able to generate a script that couldn't be run. `apt-get install somecompany-my-project` and `service somecompany-my-project start` would cause the above error. This is probably a separate ticket.
