### ISSUE TITLE
dockerhub private repo authentication

### ISSUE THREAD

**Issue by mayacr86** [sbt/sbt-native-packager#654]
Is there a way to set the authentication for a private repository on dockerhub?

<code>dockerRepository := Some("myRepo")</code>

<code>dockerRepositoryAuth := Some("myAuthToken")</code> ???

If not, what would be a work around? I want to automate the process of <code>docker:publish</code> with TeamCity.

**Comment by muuki88** [comment]
I'm afraid you have to configure your docker daemon. This is from our gitter chat:

> Because there didn’t seem to be a way to inject auth information without altering the environment, the plugin punts on the issue, and requires you to have run docker login as the build user, for any repositories requiring authentication.
Your local repository won’t need any authentication anyway (at least, I’ve never seen it), so it doesn’t matter until you run sbt docker:publish

and

> It just assumes thedocker command works. It’s a thin wrapper around docker build and docker push, so you can always run those commands manually.

cc @fiadliel

**Comment by fiadliel** [comment]
Yes, the problem was that you can't provide authentication on a once-off basis for pushing, without it being added to `~/.docker/config.json`. A permanent change to the environment is not what somebody might expect (and could even be a security issue), so this feature was left out.

You can manually run the command to log into a Docker server, if you have the ability to run particular commands in the environment:

```
$ docker login -h

Usage: docker login [OPTIONS] [SERVER]

Register or log in to a Docker registry server, if no server is
specified "https://index.docker.io/v1/" is the default.

  -e, --email=       Email
  --help=false       Print usage
  -p, --password=    Password
  -u, --username=    Username
```

**Comment by mayacr86** [comment]
Thanks for the quick response :)

Well, it does make sense that a plugin shouldn't change to the environment... I was just hoping for an easier way to do it :p

Right now, I'm using the following command as one of the *Build Steps* on my TeamCity deployment process:

<code> $ docker login -e [userEmail] -p [userPass] -u [userName]</code>

After that step, I do the <code>docker:publish</code> and it does the trick!

Thanks anyway!

**Comment by muuki88** [comment]
There is small section in the [documentation](http://www.scala-sbt.org/sbt-native-packager/formats/docker.html#id2). 

I leave this issue open to extend the docs there.

**Comment by nhooey** [comment]
It would be nice if the word "password" was near the text:

> It is currently not possible to provide authentication for Docker repositories from within the build.

So when someone is searching the page, they can find it.

**Comment by mkurz** [comment]
> It would be nice if the word "password" was near the text

Would have saved me some time as well...

**Comment by muuki88** [comment]
@mkurz would you like to add a small section in the docs?

**Comment by mkurz** [comment]
> @mkurz would you like to add a small section in the docs?

@muuki88 Done, see #1275

**Comment by muuki88** [comment]
Awesome :heart:
