### ISSUE TITLE
Duplicate mappings for scala-library-2.10.3.jar with sbt-native-packager 0.7+, Play 2.2.6 and Scala 2.10

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt-native-packager#657]
I'm stuck with Play 2.2.6 and Scala 2.10 for a project. `sbt-native-packager` 0.6.4 is compatible, but has a bug I can't live with (passing a relative path to `scriptClasspath` throws `java.lang.IllegalArgumentException: character to be escaped is missing`). I see this got fixed in `sbt-native-packager` 0.7.0. 

Unfortunately, when I try the `sbt stage` task using `sbt-native-packager` 0.7.0 or later I get:

```
java.lang.RuntimeException: Duplicate mappings:
/work/myProject/target/universal/stage/lib/org.scala-lang.scala-library-2.10.3.jar
from
/opt/play-2.2.6/repository/local/org.scala-lang/scala-library/2.10.3/jars/scala-library.jar
/home/mslinn/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.3.jar
```

Suggestions?

**Comment by muuki88** [comment]
Sorry for the late reply. This bug seems a bit deeper in sbt. Currently I have no idea what causes this :(

**Comment by mslinn** [comment]
This bug is causing us a lot of grief. I reached out to @jsuereth a few weeks ago regarding this issue but got no reply.

**Comment by muuki88** [comment]
I imagine it does, but this is an open source project and we have as much resources as our community provides. If you need any help on debugging this, you can seek guidance, we are happy to help.

@ahjohannessen provided a [repo to reproduce the bug](https://github.com/ahjohannessen/sbt-native-packager-bug) (see [chat log here](https://gitter.im/sbt/sbt-native-packager?at=55e59e6956211cd86f86e9f4)

**Comment by mslinn** [comment]
I took a shortcut and patched the 0.6 branch so I could fix the error there. Here is the [forked GitHub project](https://github.com/mslinn/sbt-native-packager/tree/0.6), complete with instructions on how to install it.

**Comment by muuki88** [comment]
I took a look where these bindings come from. With the repo mentioned above, I found that `spray` jars are added as `bundle` and `jar`. Adding this to the `build.sbt` reveales:

```scala
val showMappings = taskKey[Unit]("showMappings") 

showMappings := {
  (mappings in Universal).value
  .filter(_._2 contains "spray")
  .foreach {
    case (file, path) => println(file + " -> " + path)
  }
}
```

```
sbt universal:showMappings
..io.spray/spray-json_2.11/jars/spray-json_2.11-1.3.1-sources.jar -> lib/io.spray.spray-json_2.11-1.3.1-sources.jar
..io.spray/spray-json_2.11/jars/spray-json_2.11-1.3.1.jar -> lib/io.spray.spray-json_2.11-1.3.1.jar
..io.spray/spray-client_2.11/jars/spray-client_2.11-1.3.2-sources.jar -> lib/io.spray.spray-client_2.11-1.3.2-sources.jar
..io.spray/spray-client_2.11/jars/spray-client_2.11-1.3.2.jar -> lib/io.spray.spray-client_2.11-1.3.2.jar
..io.spray/spray-can_2.11/bundles/spray-can_2.11-1.3.2.jar -> lib/io.spray.spray-can_2.11-1.3.2.jar
..io.spray/spray-io_2.11/bundles/spray-io_2.11-1.3.2.jar -> lib/io.spray.spray-io_2.11-1.3.2.jar
..io.spray/spray-util_2.11/bundles/spray-util_2.11-1.3.2.jar -> lib/io.spray.spray-util_2.11-1.3.2.jar
..io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.2.jar -> lib/io.spray.spray-http_2.11-1.3.2.jar
..io.spray/spray-httpx_2.11/bundles/spray-httpx_2.11-1.3.2.jar -> lib/io.spray.spray-httpx_2.11-1.3.2.jar
```

Question is. Why are `jars` and `bundles` in these mappings. I guess this in the same issue for the `scala` library.

**Comment by yfyf** [comment]
Perhaps obvious, but disabling cached resolution seems to resolve this at least for me. YMMV.

**Comment by peter-fu** [comment]
Same here, enabled cached resolution today with sbt 0.13.12 and the error "Duplicate mappings" occurred for `activator stage`.

Play 2.3.10
sbt 0.13.2
sbt-native-packager 1.1.4

Workaround, same as @yfyf, disable cached resolution before `activator stage`.
