### ISSUE TITLE
rpm scriptlets are not read from default rpm script directory

### ISSUE THREAD

**Issue by captify-msladkiy** [sbt/sbt-native-packager#660]
Hello,

I use native packager to build rpms with scriptlets created from files located in the src/rpm/scriptlets folder. But this feature seems not working, at least for me. I had found tests for [it](https://github.com/sbt/sbt-native-packager/blob/master/src/sbt-test/rpm/scriptlets-override-rpm/build.sbt) and recreated them with build.scala (see [nprpmtest.tar.gz](https://mega.nz/#!Xpcx1IDL!aAPjp55Btl6myizY4lI37WKxq8EikHBFpandm6Rf1Kg) – dummy test project)

> System:
> Ubuntu 14.04.3 LTS
> scala 2.10.5
> sbt 0.13.5
> native-packager 1.0.3

to run
> $ sbt unzipAndCheck
or
> $ sbt check-spec-file

Thanks

**Comment by muuki88** [comment]
Works only with `JavaServerAppPackaging`
