### ISSUE TITLE
tar is expected to have --force-local option

### ISSUE THREAD

**Issue by mackler** [sbt/sbt-native-packager#662]
I am wanting to use `sbt-native-packager` on FreeBSD (10.2).  The base-installation of `tar` in this version of FreeBSD [lacks the `--force-local` option](https://www.freebsd.org/cgi/man.cgi?query=tar&apropos=0&sektion=0&manpath=FreeBSD+10.2-RELEASE&arch=default&format=html).  I have gnu's _tar_, which has the `--force-local` option, installed on the machine, but it is named `gtar` rather than `tar`.

[It seems](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala#L182) that both the name of the _tar_ executable and the `--force-local` option are hard-coded in the `sbt-native-packager` source code.  On my FreeBSD machine, invoking the `universal:packageZipTarball` task fails with a complaint about the `--force-local` option.

Is there any simple work-around of this issue that does not involve renaming the commands on my operating system?  If not, is the ability to tell `sbt-native-packager` to refrain from including the `--force-local` option when invoking tar, or changing the name of the _tar_ executable a feature that might eventually find its way into this project?

**Comment by muuki88** [comment]
At this point there's no easy way to change the commands in sbt-native-packager. If you want to change this behaviour in sbt-native-packager you will have to override the task. I recommend aliasing your gtar command to tar. If this is not acceptable for you, please provide a pull request. If you need any help, just ask.
