### ISSUE TITLE
JavaAppPackaging can provide pid and stop script

### ISSUE THREAD

**Issue by shijinkui** [sbt/sbt-native-packager#670]
Mostly we need a pid and a stop script(bash and bat) when using JavaAppPackaging style.
Pid can configured in `javaOptions`, like  `"-Dpidfile.path=/opt/agent_server/server.pid"`.

pid is needed in java and server archetypes. i want to know why java app archetypes have not it.
cc @muuki88 @hepin1989

**Comment by muuki88** [comment]
Use the the server-archetype for this. If you need the `JavaServerAppPackaging` to work with windows see #329.

Also [see last  comment](https://github.com/sbt/sbt-native-packager/issues/164#issuecomment-141011282)
