### ISSUE TITLE
Auto plugins are required to declare their project configurations

### ISSUE THREAD

**Issue by huntc** [sbt/sbt-native-packager#676]
Auto plugins are required to register any configurations that they may introduce in order to allow a user to declare any addition configurations of their own. For example, given some other configuration named `Backend`:

```scala
lazy val root = (project in file("."))
  .enablePlugins(JavaAppPackaging)
  .configs(Backend)
```

...a `bundle:dist` will subsequently fail as the plugin's configurations are effectively zapped. 

Each new auto plugin that introduces a configuration should declare the configurations that it provides so that they may be prepended to declarations such as the one above. The method to override for each auto plugin is `projectConfigurations`. Here's an example from sbt-bundle (pending a PR):

```scala
  override def projectConfigurations: Seq[Configuration] =
    Seq(
      Bundle,
      BundleConfiguration
    )
```

**Comment by muuki88** [comment]
So for example our `DockerPlugin` should have an additional line

```scala
  object autoImport extends DockerKeys {
    val Docker = config("docker") extend Universal
  }
  import autoImport._

override def projectConfigurations: Seq[Configuration] = Docker :: Nil
```

Does this have any effect on existing behaviour?

**Comment by huntc** [comment]
I understand that adding it is benign.

**Comment by huntc** [comment]
I took a look at the sbt source and the auto plugin config sequence is prepended to any user supplied config via this override. 

Perhaps @eed3si9n can confirm the effect of overriding the method as the right thing to do though.

**Comment by huntc** [comment]
Nice work!

**Comment by muuki88** [comment]
Thanks :)
