### ISSUE TITLE
Include examples

### ISSUE THREAD

**Issue by Steiny69** [sbt/sbt-native-packager#678]
For the past couple of days I was trying to work out how to get a multi project build working with the SBT Native Packager. I eventually stumbled across the examples repository by muuki88 (https://github.com/muuki88/sbt-native-packager-examples). These are awesome and should at least be linked to from the SBT repository and/or docs if not included in that repository as well.

**Comment by muuki88** [comment]
It somewhere in the docs. Maybe we put in the readme.
