### ISSUE TITLE
[bug] wrong systemd script file path in debian

### ISSUE THREAD

**Issue by ptonelli** [sbt/sbt-native-packager#679]
The systemd path for the service script for debian in JavaServerApp is 
`/usr/lib/systemd/system`

Following the Debian packaging [documentation](https://wiki.debian.org/Teams/pkg-systemd/Packaging)

It should be:
`/lib/systemd/system`

The first path seems to be correct for RedHat based distributions ([doc](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/chap-Managing_Services_with_systemd.html))

**Comment by muuki88** [comment]
Which system fails for you? On Ubuntu `15.10` this seems to work. 
A fix would be rather easy ( if you like to open a pull request):

- [Debian startscript mapping](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala#L100)
- [Get Startscript Location](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerApplication.scala#L230-L236)

**Comment by ptonelli** [comment]
I am under debian jessie (8.2)

the official path in ubuntu seems to be the same as in debian ([doc](https://wiki.ubuntu.com/systemd)).

You are right, it works even with the `/usr/lib/systemd/system` path even in debian.

**Comment by muuki88** [comment]
No Problem :) Thanks for the detailed reporting anyway.
