### ISSUE TITLE
Java Options with space in them cannot be added

### ISSUE THREAD

**Issue by theomega** [sbt/sbt-native-packager#681]
I want to add the following Java-Option to the launcher:

```
  -XX:OnOutOfMemoryError="kill -9 %p"
```

I tried the following in the build.sbt:

```
javaOptions in Universal ++= Seq(
 "-J-XX:OnOutOfMemoryError=\"kill -9 %p\""
)
```

But this lead into the following command being executed:

```
  java -Xmx64m -Xms64m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=12345 '-XX:OnOutOfMemoryError="kill' -cp [Classpath] ExampleApp -9 '%p"'
```

This means that the java option was split on the first space and the rest of the command was inserted at this point which makes the part after the space appear as parameters to the application

I used sbt-native-package version 1.0.3

**Comment by theomega** [comment]
Ok, I had some luck with doing the following after removing the `javaOptions` again:

  bashScriptExtraDefines ++= Seq(
    "addJava \"-XX:OnOutOfMemoryError='kill -9 %p'\""
  )

This does the correct thing. If this is the intended behaviour, please close the ticket. Perhaps the documentation should be updated.

**Comment by muuki88** [comment]
The parsing is done by the bash-script, which can be really tricky to fix or debug. You second solution is definitely correct and a way to go. Still the first option should work as well. 

If you can [spot the error in this line](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template#L198) I'm happy to merge a pull request :)

**Comment by theomega** [comment]
Thanks for your answer. My overservation is that the thing already breaks in the `loadConfigFile` method in the bash script: It screws up the spaces already there, so it is already to late in the line you mention....

**Comment by theomega** [comment]
Actually, I was wrong, the command posted by me doesn't work correctly due to quoting. This here might work better:

    bashScriptExtraDefines ++= Seq(
      "addJava -XX:OnOutOfMemoryError='kill -9 %p'"
    )

So removing on level of quotes
