### ISSUE TITLE
can't start with root 

### ISSUE THREAD

**Issue by shijinkui** [sbt/sbt-native-packager#682]
> As a side note Fedora/RHEL/Centos family of linux specifies Default requiretty in its /etc/sudoers file. This prevents the default Upstart script from working correctly as it uses sudo to run the application as the daemonUser . Simply disable requiretty to use Upstart or modify the Upstart template.   http://www.scala-sbt.org/sbt-native-packager/archetypes/java_server/customize.html

```
serverLoading in Rpm := ServerLoader.Upstart
daemonUser in Linux := "root"
daemonGroup in Linux := (daemonUser in Linux).value
```
After install rmp package, i use root to run `service start xxx` fail, the `/etc/init.d/` have no my app. 
Is it register the app to the init by default?
who can help..

> Linux  2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shijinkui** [comment]
```

rpm -ivh agent-1.0.28-2.noarch.rpm
warning: agent-1.0.28-2.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID ddfeef76: NOKEY
Preparing...                ########################################### [100%]
error: %pre(emr-agent-1.0.28-2.noarch) scriptlet failed, exit status 1
error:   install: %pre scriptlet failed (2), skipping emr-agent-1.0.28-2

```

**Comment by shijinkui** [comment]
hi, @muuki88, am i use in wrong style?

**Comment by muuki88** [comment]
`upstart` uses the `/etc/init/` folder. I'm not sure what the console output is all about.
You sbt configuration looks good ( besides the fact that you're running stuff as root ;) )
