### ISSUE TITLE
PID must be play.pid

### ISSUE THREAD

**Issue by andyczerwonka** [sbt/sbt-native-packager#683]
I'm not sure if this should land here or with the Play framework project.

I was following [these instructions](http://www.scala-sbt.org/sbt-native-packager/topics/play.html), trying to get my application running for a couple of days. I couldn't figure out what was wrong but once I changed the name the the `pid` to `play.pid` it worked. Seems strange that it's hardcoded.

https://github.com/andyczerwonka/tyrion/commit/6d2821d2d12e44c1ae01dbe4d7228bbc9f608314

Ubuntu 14,04 LTS

**Comment by muuki88** [comment]
cc @jroper
