### ISSUE TITLE
Relative path in DEBIAN/conffiles

### ISSUE THREAD

**Issue by gerdriesselmann** [sbt/sbt-native-packager#684]
When placing a file in either 

```
src/linux/usr/share/[name]/conf/[file]
```

or 
```
src/linux/etc/[path]/[file]
```

it gets correctly packaged, and inserted into DEBIAN/conffiles.

However the entries are missing a leading slash.

Got:
```
usr/share/[name]/conf/[file]
etc/[path]/[file]
```

Expected:
```
/usr/share/[name]/conf/[file]
/etc/[path]/[file]
```

**Comment by muuki88** [comment]
Thanks for the report. The behavior is [actually intended](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala#L106). We map the content into the `installationDirectory`.

In your case this means you put your files in

``` 
src/linux/conf/[file]
```

If you use the `JavaServerAppPackaging` archetype a symlink from `/etc/<packageName>` to `/usr/share/<packageName>/conf` gets created, so no need to copy these files.

If you want to add files outside the installation folder, use the `mappings` or `linuxPackageMappings` (if you need special permissions).

See [linux plugin docs](http://www.scala-sbt.org/sbt-native-packager/formats/linux.html#modifying-mappings-in-general) and the [Mappings Helper docs](http://www.scala-sbt.org/sbt-native-packager/formats/universal.html#mappingshelper) / [scala docs](http://www.scala-sbt.org/sbt-native-packager/latest/api/#com.typesafe.sbt.packager.MappingsHelper$)

**Comment by gerdriesselmann** [comment]
Thanks for the reply!

I tried, and actually I had to place the file at

```
src/universal/conf/[file]
```

[See code](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/linux/LinuxPlugin.scala#L218)

Everything inside src/linux got copied to / inside the package.
