### ISSUE TITLE
Universal java options ignored on Windows - cannot set javaOptions

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt-native-packager#688]
I have added an option for max heap space:

```
javaOptions in Universal += "-J-Xmx1024m"
```

This goes into `conf/application.ini` when packaging and is properly parsed on Linux and Mac from the bash script. On Windows, the `.bat` file is broken, though. Instead of trying to read this file, it looks for `./<APP-NAME>_config.txt` which does not exist, resulting in an application launch with wrong heap settings.

It also seems that the format of the `.ini` file is not compatible. If I copy the `application.ini` file to `<APP-NAME>_config.txt`, the `.bat` file has this error:

```
Unrecognized option: -J-Xmx1024m
```

**Comment by muuki88** [comment]
I fear this is not implemented yet. Pull requests welcome :)
