### ISSUE TITLE
folder mappings

### ISSUE THREAD

**Issue by stanch** [sbt/sbt-native-packager#69]
Hi,

What would be the easiest way to add a folder with all files (or better—pattern-filtered) to this?

``` scala
mappings in Universal += {
  file("my/local/conffile") -> "conf/my.conf"
}
```

**Comment by wsargent** [comment]
FYI, the 0.13 version of `(confDir.*** --- confDir) x relativeTo(confDir)` is 

```
(confDir.allPaths --- confDir) x Path.relativeTo(confDir)
```

**Comment by muuki88** [comment]
Thanks for sharing 😍
