### ISSUE TITLE
sbt packager ( esp. Debian plugin) does not package scalajs-files and webjars

### ISSUE THREAD

**Issue by antonkulaga** [sbt/sbt-native-packager#699]
My application (preview root project of https://github.com/antonkulaga/scala-js-binding ) works fine when I 
```
sbt re-start
```
it and then open it at localhost:5553. But When I package it with
```
sbt debian:package-bin
```
and open localhost:5553 I see that most of webjars as well as scalajs files are not loaded at all. With other packager plugins I had the same problem =( I have the same problem with Universal packaging.

**Comment by antonkulaga** [comment]
I think I have found the solution:
changing
```scala
    (fullClasspath in Runtime) += (packageBin in previewJVM in Assets).value,
```
to
```scala
    (managedClasspath in Runtime) += (packageBin in previewJVM in Assets).value,
```
made it work. The problem is that I have no clue why=) I used fullClasspath because IntellijIDEA guys adviced me to do so (as with managedClasspath idea tried to compile whole project when importing it and failed if there is at least one error in the project itself)

**Comment by muuki88** [comment]
This is interesting, indeed :/
