### ISSUE TITLE
javaOptions in Universal ignored by AshScriptPlugin

### ISSUE THREAD

**Issue by pawelkaczor** [sbt/sbt-native-packager#702]
Tested with sbt-native-packager 1.0.5

**Comment by muuki88** [comment]
This is currently not implemented. Take a look at [JavaAppAshScript](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaAppAshScript.scala) and [AshScriptPlugin](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/AshScriptPlugin.scala) which provide the implementation. Happy to merge a pull request :)
