### ISSUE TITLE
application does not receive SIGINT signal when using ash.

### ISSUE THREAD

**Issue by yanns** [sbt/sbt-native-packager#707]
When using `bash`, a kill of one application sends the SIGINT to it, triggering the shutdown hooks.
When using `ash` with `enablePlugins(AshScriptPlugin)`, the application does not receive the SIGINT. It has no way to cleanly shutdown. Only the SIGTERM kills the application, without triggering the shutdown hooks.

Docker for example send the SIGINT signal, waits 10 s, and then sends the SIGTERM signal. Packaging the application with `enablePlugins(AshScriptPlugin)` makes each shutdown waiting 10s.

**Comment by muuki88** [comment]
I'm not familiar with `ash`. Feel free to provide a PR to fix this :)

**Comment by NeQuissimus** [comment]
I am going to send a PR for this, I actually worked around this for our images (we need the SIGINT for Kubernetes). I will try to wrap it into a proper fix.

**Comment by NeQuissimus** [comment]
Actually, this is already fixed in > 1.1.5.

The issue was that the ash script somehow had its `exec` stripped from the bottom of the file.
With `1.2.0-M8` that issue no longer exists.

For reference, I previously worked around this by providing my custom script as suggested in the Scaladoc for `AshScriptPlugin`.

**Comment by muuki88** [comment]
Thanks @NeQuissimus 😃

**Comment by NeQuissimus** [comment]
@muuki88 Just going through the docker-labelled tickets to see what could bite me in the future since my company is using `sbt-native-packager` for Docker now :D

**Comment by muuki88** [comment]
Smart move 😎
