### ISSUE TITLE
Boot scripts are not generated when using mainClass in (Compile, run) instead of only Compile

### ISSUE THREAD

**Issue by bjoern-jacobs** [sbt/sbt-native-packager#710]
In Build.scala when I change
`mainClass in Compile := Some("my.app.class")` to `mainClass in (Compile, run) := Some("my.app.class")`, after calling `stage` there are no boot scripts in /bin anymore. If I change it back, they get generated again.

**Comment by muuki88** [comment]
This is intended behavior.

`mainClass in Compile` sets the main class for the compile step.
`mainClass in (Compile, run) sets the main class during the `run` task inside the `Compile` scope. So this main class is only used, when you call `run` (which is `compile:run`).

**Comment by bjoern-jacobs** [comment]
Thanks for this clarification.
