### ISSUE TITLE
option to exclude scala-library explicitly 

### ISSUE THREAD

**Issue by scalame** [sbt/sbt-native-packager#716]
I have a multi-module project and one of the module depends on scala-library. I have tried putting ExclusionRules on both the root's build.sbt and the module's build.sbt to avoid pulling the scala-library artifacts in 'sbt stage'. The exclusionRule works for other artifacts (i.e. an exclusion rule with just organization = "org.scala" would exclude every other scala library except scala-library.jar) but just can't get rid of scald-library.jar!!

**Comment by muuki88** [comment]
Can you post a minimal setup to reproduce this?

**Comment by scalame** [comment]
Hi, 

Here is a minimal project setup. This includes a root project and submodule in lib/core (sbt project as well). I have added some dependencies to mimic the issue. I know we can exclude scala libraries by setting the 'autoScalaLibrary' to false in the build.sbt but then each scala library jar will need to be included in each submodule's dependency as 'test'.

Unzip the file.. cd into the directory and run `sbt stage` and you will see that the scala library dependencies are in `target/universal/stage/lib`

I was hoping that we can exclude the scala library dependencies with another option in one place (at the root project)

Hope this helps, let me know if I can provide any more info

Thanks!

[sbtnativepackager.zip](https://github.com/sbt/sbt-native-packager/files/68780/sbtnativepackager.zip)

**Comment by AceHack** [comment]
What was the resolution, I'm trying to do the same?

**Comment by muuki88** [comment]
You can always filter the mappings, e.g.

```scala
Universal / mappings := (Universal / mappings).value.filter {
   case (_, path) => !path.contains("org.scala")
}
```
