### ISSUE TITLE
Create symbolic links before starting the service.

### ISSUE THREAD

**Issue by Steiny69** [sbt/sbt-native-packager#718]
I'd like to be able to create the symbolic links before starting the service.

I'm overriding the start script with the one for Tanuki Wrapper. This script has configuration with relative paths within the application installation directory and it also sets the working directory to the directory of the script. So the script itself needs to be located within the application installation directory (without having to modify the scripts working directory which is not recommended). Then we create a link from the system loader directory to the actual script.

The problem here is that when the `post%` scriptlet is created via the `com.typesafe.sbt.packager.rpm.RpmScripts.postContent(buildSymlinkScript: Option[String])` function, it puts the `postinst-template` first and then the build symlink script.

**Comment by muuki88** [comment]
So you want to create a symbolic link _after the installation_, right? The `post-install` scriptlet is the correct position.

With `1.1.0-M1` we introduced a new setting `maintainerScripts` to make it easier customizing these parts. Check out [the docs](http://www.scala-sbt.org/sbt-native-packager/formats/rpm.html#scriptlet-changes) on how to configure your post-inst scriptlet.
