### ISSUE TITLE
docker,package name should not support upper case?

### ISSUE THREAD

**Issue by hepin1989** [sbt/sbt-native-packager#725]
if I use `gateServer` then,it comes 
```
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
```
but `gateserver` works.
```
packageName in Docker := "gateServer"
```

**Comment by mbarison** [comment]
Have a look at the regular expression mentioned in the error:

`repository name component must match "[a-z] ...`

It's [a-z]. which means lowercase only. Uppercase is NOT supported,

**Comment by muuki88** [comment]
[AFAIK](https://github.com/docker/compose/issues/1416) docker still doesn't support uppercase letters. So we validate your package name upfront for you.
