### ISSUE TITLE
systemd service customization (open files)

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt-native-packager#728]
Would be nice to have a way to customise the systemd service file the same way as we can do with the bat/bash files. More specifically we would need to add the open files limit option:

http://www.freedesktop.org/software/systemd/man/systemd.exec.html

Eg: 
When using systemd you might need to set LimitNOFILE=10500 in the service file.
Manual way to do this:

```
sudo pico /usr/lib/systemd/system/myapp.service
# in the service section add:
# LimitNOFILE=10500
sudo systemctl daemon-reload
sudo systemctl restart myapp.service
```

For the bash file this can be done like this (when not using systemd)

```
bashScriptExtraDefines += """ulimit -n 10500"""
```

Might even be interesting to have a unified way to set up open file limits...

In case you want to see the applied limits to your service

``` bash
cat /proc/$(cat /var/run/myapp/play.pid)/limits
```

**Comment by muuki88** [comment]
At the moment you have the following options

### Override the complete script

This is documented [here](http://www.scala-sbt.org/sbt-native-packager/archetypes/java_server/customize.html#override-start-script). You have to configure everything your self.

We should add that to the [archetype cheatsheet](http://www.scala-sbt.org/sbt-native-packager/archetypes/cheatsheet.html)

### Hack it into predefined settings

There are currently four settings

- `startRunlevels`
- `stopRunlevels`
- `requiredStartFacilities`
- `requiredStopFacilities`

which are essentially strings. You could add your settings in there, but this is rather bad.

## Solution

I like the idea of a generic data structure where you can append things which will be added to the start script. Most of the heavy lifting is done in [JavaServerBashScript](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/JavaServerBashScript.scala), which reads the templates and substitutes the placeholders.

However the system-loaders are so different, it's hard to provide a generic setting that fits for all. For `SystemD` and `Upstart` the scripts are actually  that simple, you can copy n paste them and mark your adjustments there.

@francisdb if you have a good idea how to make things work for all systemloaders in an easy way?

**Comment by francisdb** [comment]
Overriding the script is always a solution but not preferable as you might forget to update your copy when the source is updated (bug fixes, refactorings, ...)

Even appending might not fit all as some systems. I fear it will be quite hard to come up with a solution for all loaders/supported packagings.

I guess this will have to be a case-by-case solution or the override solution

**Comment by muuki88** [comment]
Now that Systemloaders are separate AutoPlugins ([SystemdPlugin](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemdPlugin.scala) we can tackle this issue. There is another issue were some ideas have been discussed. Closing this in favor of #937
