### ISSUE TITLE
exec bin/*** no such file

### ISSUE THREAD

**Issue by IntelligyScience** [sbt/sbt-native-packager#730]
Hi,

I have a problem.

I set up a playframework project. In build.sbt I passed following things:

packageName in Docker := "mars"
version in Docker := version.value
dockerBaseImage := "ipricegroup/ubuntu-oracle-java-8"
dockerExposedPorts := Seq(9000)
dockerExposedVolumes := Seq("/opt/docker/logs")
dockerCommands += ExecCmd("RUN","chmod","+x","bin/mars")

I build it in Idea with sbt console and the command: docker:stage

I uploaded the folder opt with Dockerfile in the folder stage. On my server (Ubuntu) I have a few docker containers running. With the same build.sbt and the same way. (the name in sbt is different).

I run the container and get always:

exec: "bin/mars": stat bin/mars: no such file or directory

Where is my error?

Thanks for help

**Comment by IntelligyScience** [comment]
I had the line
javaOptions += "-Dconfig.file=/opt/production.conf"
too

**Comment by IntelligyScience** [comment]
exactly error:
FATA[0000] Error response from daemon: Cannot start container d1559ca6af4ac5eaaed94f6bf90c4f313e186f4d245627e952724bd5f969856a: [8] System error: exec: "bin/mars": stat bin/mars: no such file or directory

**Comment by IntelligyScience** [comment]
Ahh 
if i run this:
docker run -v /opt/shop:/opt -p 9012:9000 --name wilde7 -d andre/mars:1.0.0

I get this error!

**Comment by IntelligyScience** [comment]
And I found the solution. :/opt is wrong :)

**Comment by esthom** [comment]
@IntelligyScience could you write what was wrong with :/opt ?

**Comment by hajjijo** [comment]
@IntelligyScience you are good to ask question . But could you write what was wrong! as good as your question?
