### ISSUE TITLE
Add option to totally remove RUNNING_PID management

### ISSUE THREAD

**Issue by valdo404** [sbt/sbt-native-packager#736]
Hi,

as we are using supervisord to manage our play application, we would like to tell the native packager we do not want to use PID management.
How can we do that ?

Best.

**Comment by muuki88** [comment]
I need a bit more information

- `supervisord`, does this mean you are running a docker image?
- If you aren't using docker, which packaging format are you using?
- have you tried the play config setting `-Dconfig.pidfile=/dev/null`?

**Comment by valdo404** [comment]
Hi,

- we only mean that the process is managed by supervisord, without pid management.
- We are using zip packaging format
- We didn't try /dev/null, but it looks like a hack ;) thanks for the tip.

Regards,

**Comment by muuki88** [comment]
If you use the zip packaging format, then the solution you are looking for is the `/dev/null` setting. 
It's documented in the playframework docs, so you can see it as an official hack ;)

Native packager doesn't provide any kind of system-loader or pid-management. We only provide configurations for existing systems like systemd, systemv and upstart.
