### ISSUE TITLE
Link to non-existing page `np-plugin.html`

### ISSUE THREAD

**Issue by ProgVal** [sbt/sbt-native-packager#740]
Commit 370a0e83e97eaed869932b869de2dd0f9f2169dc (on `gh-pages`) introduces two links to a page named `np-plugin.html`, but this page does not exist.

**Comment by muuki88** [comment]
Hm. What was my intention back then. I'll try to fix this. Thanks :)

**Comment by muuki88** [comment]
Closed with #755
