### ISSUE TITLE
Adding a Code of Conduct

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#744]
This community has been IMHO a very open, helpful and respectful one. In order to manifest this positive culture I suggest to add a code of conduct to this project. I found to major code of conducts that would match my expectations:
- [Open Code of Conduct](http://todogroup.org/opencodeofconduct/)
- [Code Covenant](http://contributor-covenant.org/)

We should also agree on contact person that would take action if there are any complaints.

cc: @metasim , @kardapoltsev , @fiadliel

**Comment by muuki88** [comment]
A nice discussion and summary from my colleagues project: https://github.com/flycheck/flycheck/issues/819#issuecomment-164123216

**Comment by metasim** [comment]
I like that Code Covenant has gone through a few iterations and seems to have some pretty big projects adopting it. I like that Open Code of Conduct has more text around definitions and context (feels more user friendly), but I'd go for broader usage over "Look and Feel".

**Comment by SethTisue** [comment]
+1 to either one
