### ISSUE TITLE
Customize for configuration

### ISSUE THREAD

**Issue by DGolubets** [sbt/sbt-native-packager#752]
Hi,
I can't find any example of how to do a simple customization based on a configuration.

I want something like this:
```
lazy val Prod = config("prod") extend Universal
lazy val Dev = config("dev") extend Universal

javaOptions in Dev += "-J-Xmx4G"
javaOptions in Prod += "-J-Xmx8G"
```

Ofc this doesn't work..

**Comment by muuki88** [comment]
Nope, there is no example. And this is not the recommended way to go.
See a full explanation here #746 

Maybe we put something in the docs how to do it instead.
