### ISSUE TITLE
Upstart script does not use killTimeout

### ISSUE THREAD

**Issue by elm-** [sbt/sbt-native-packager#754]
We are using upstart on ubuntu and the default kill timeout of 5 seconds is not overwritten by setting of LinuxKeys.killTimeout in the settings. I checked the template and it does not contain the relevant placeholder. is there a reason or can this be added?

**Comment by muuki88** [comment]
Thanks for your feature request @elm- 

There is no reason for that, it wasn't simply implemented. If you could create a small PR adding this, would be awesome :)

**Comment by elm-** [comment]
@muuki88 thanks a lot, sorry I actually missed your comment to provide a pull request, I would have done that otherwise.

**Comment by muuki88** [comment]
No problem. We made some bigger changes to the systemloader feature, which makes a a lot easier now to integrate such specific changes.

There will always be a next time for a pull request :) For instance #770 ;)
