### ISSUE TITLE
Native Packager Logo

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#762]
I tried fiverr.com for the first time (aweful experience) and asked for a native packager logo.

This is what came out:

![fiverr](https://cloud.githubusercontent.com/assets/647727/14155179/e65b5114-f6c0-11e5-9b06-5fef605bc451.jpg)

WDYT?

cc @metasim @fiadliel @kardapoltsev 
@SethTisue are there any restrictions from lightbend?

**Comment by SethTisue** [comment]
no idea. not even sure who I would ask. maybe @eed3si9n knows

**Comment by metasim** [comment]
I think it needs to have the word "sbt" somewhere in there. Otherwise, it just looks like a generic packaging tool.

**Comment by muuki88** [comment]
> I think it needs to have the word "sbt" somewhere in there

@metasim yes. This can easily be extended. The icon and font is what I would like to get feedback on. Still very unsure :/

**Comment by eed3si9n** [comment]
As sbt community admin: sbt-native-packager is now a community-owned plugin, so I don't think there will be restriction from Lightbend's side unless you do something really shady.

*Following are my personal ideas.* Overall it's looks ok, but currently typography, logo, and the color looks gentle. You could pick of the three and do something more fun. For instance, picking a font that looks like you wrote it using Sharpie or [Comic Neue](http://comicneue.com/).

The logo might look better if the box looks more like a "package".
Like a cardboard box with top flapping open
<img src="https://openclipart.org/image/2400px/svg_to_png/226172/Open-Cardboard-Box.png" width="200">

 or shipping parcel like:
<img src="http://thumbs.dreamstime.com/x/shipping-package-sent-mail-9811564.jpg" width="200">

Is that too cliché? Another idea could be to put the word "Packager" inside some packaging like the above box idea.

As per including "sbt-" or not I think is up to you. A lot of times, I call it "native packager" colloquially, and that could be your project or brand identity. Similar example might be scalariform vs sbt-scalariform.

**Comment by muuki88** [comment]
Thanks @eed3si9n for your input. I can beat your cliché with the first idea a friend of mine made for native packager :D

![native-packager](https://cloud.githubusercontent.com/assets/647727/14260233/d507e3e4-faaa-11e5-9695-5de3bdfb9274.jpg)

Things with boxes always look like Dropbox other similar services. I will try to get some other examples (also not too serious).

**Comment by SethTisue** [comment]
or sbt-nap with a sleeping kitten :-)

**Comment by metasim** [comment]
I wouldn't have ".exe" anywhere in the logo. If this were a "launch4j" plugin, then it would make sense, but SNP is way more than that.

Still stand by my thinking that "sbt" needs to be included.

**Comment by muuki88** [comment]
Third round. I got help from our designer in our team and he made a huge load of logo proposal. Feel free to comment :)

![native_packer_logo_tent](https://cloud.githubusercontent.com/assets/647727/14777685/fa7bb662-0ace-11e6-82c0-f8044a0c0bc0.jpg)

![native_packer_logo_mockups](https://cloud.githubusercontent.com/assets/647727/14777692/ffd83c20-0ace-11e6-8b82-30d035c28c11.jpg)

**Comment by metasim** [comment]
My 2¢.

1) I really like these three:

![screen shot 2016-04-25 at 8 55 52 am](https://cloud.githubusercontent.com/assets/131013/14784403/89e3cbfc-0ac3-11e6-96d1-428aaa19fbad.png)

![screen shot 2016-04-25 at 8 55 09 am](https://cloud.githubusercontent.com/assets/131013/14784388/720b3466-0ac3-11e6-9d56-9898fd79916a.png)

2) I'd stay away from anything with an ethnic overtone, although the one at the bottom with the "A" as a teepee is pretty cool. I like that font too.
3) Really think the word/acronym "sbt" need to be in the logo. Is there a push from some constituency not to have that?

**Comment by metasim** [comment]
PS: I still think there's a lot to like with the first box:

![screen shot 2016-04-25 at 9 02 35 am](https://cloud.githubusercontent.com/assets/131013/14784622/8377f0d0-0ac4-11e6-82c0-84b6480d43ac.png)

Of the two with rounded corners, I actually think I like this better:
![screen shot 2016-04-25 at 9 03 05 am](https://cloud.githubusercontent.com/assets/131013/14784641/9bb0431e-0ac4-11e6-8d01-125266229fee.png)

**Comment by muuki88** [comment]
Thanks for your feedback.

> Really think the word/acronym "sbt" need to be in the logo. Is there a push from some constituency not to have that?

:D actually no. "Native packager" ist just a little shorter. But I think adding _sbt_ in front should not be a problem. The icon is the main goal here.

> although the one at the bottom with the "A" as a teepee is pretty cool. I like that font too.

Totally agree. The big logo has the same font. Integrating the icon feels good. Currently I'm feeling quite comfortable with this one.

> Of the two with rounded corners, I actually think I like this better

They kind a remind me about amazon. I don't know why ;)

I will give this feedback to my colleague. He will iterate over a few of those then. I'll keep you updated.

**Comment by fiadliel** [comment]
Naive packager ;-)
But I like that one, with the spelling fixed, and SBT added in front (yes, we need SBT somewhere).

**Comment by eed3si9n** [comment]
> 2) I'd stay away from anything with an ethnic overtone

As a person who lives in the US, even the teepee feels like a form of [cultural appropriation][1] tbh.

  [1]: https://en.wikipedia.org/wiki/Cultural_appropriation

**Comment by muuki88** [comment]
@eed3si9n, @metasim I agree with you. The "native" part in sbt-native-packager should not be reflected with any icons/symbols of specific ethnic groups.

I would ask Sascha to work on these a bit more:

![native-packager01](https://cloud.githubusercontent.com/assets/131013/14784622/8377f0d0-0ac4-11e6-82c0-84b6480d43ac.png)

![native-packager02](https://cloud.githubusercontent.com/assets/131013/14784641/9bb0431e-0ac4-11e6-8d01-125266229fee.png)

**Comment by metasim** [comment]
The cool thing about the top one is that you could tile it nicely.

![image](https://cloud.githubusercontent.com/assets/131013/14798387/61253f6a-0b05-11e6-8017-de03f1f0ccfc.png)

**Comment by muuki88** [comment]
Wow. I like that. Multiple formats, multiple boxes.

**Comment by muuki88** [comment]
Even more boxy suggestions from my colleague

![native_packager_08_720](https://cloud.githubusercontent.com/assets/647727/14845381/1811a462-0c5e-11e6-8458-df20af396076.png)

**Comment by metasim** [comment]
What's the significance/relevance of the `</>` symbol? Looks like XML to me.... 

If there's interest in using some symbol, `=>` or `⇒` would seem more relevant. As in:

![image](https://cloud.githubusercontent.com/assets/131013/14851901/eaa339b2-0c50-11e6-984a-aea2c0f317ae.png)

...but I'm not really advocating for this. Ultimately too busy, I think.

**Comment by muuki88** [comment]
So, here are once more a few suggestions. Actually I really like the top-left one as a logo.
It has boxes, boxes in boxes and different colors ( different formats ).

![native_packager_15](https://cloud.githubusercontent.com/assets/647727/15099201/89274a18-154f-11e6-8c0e-0a78649ce845.png)

**Comment by metasim** [comment]
Agreed (+1) on the  upper left. Bottom middle is compelling was well. What would  a B&W/greyscale version of the upper left look like? Do we even need to be concerned about having a B&W version these days?

Actually, the bottom middle is quite mesmerizing. Can't stop looking at it... :-)

**Comment by muuki88** [comment]
> What would a B&W/greyscale version of the upper left look like

Glad you ask xD My colleague said that B&W was very important for sending fax messages. Well that's definitely out of scope for us.

**Comment by muuki88** [comment]
@SethTisue @eed3si9n @fiadliel  WDYT? I'm very happy with this design as it's

- colorful ( plays nice with the different formats supported )
- box and box-in-box shape, which fits nice to packaging

If you all give your OK, I would use this logo and give it the finish touch
and update the project.

![native_packager_logo](https://cloud.githubusercontent.com/assets/647727/15391588/3506a750-1dc2-11e6-92bc-72fb94281f79.png)

**Comment by eed3si9n** [comment]
LGTM. I actually like all of the new series.

**Comment by muuki88** [comment]
Great. I will talk to Sascha and we will make this "production ready" :+1:
