### ISSUE TITLE
Bat-Template expects @APP_ENV_NAME@@_config.txt rather than application.ini

### ISSUE THREAD

**Issue by wofr** [sbt/sbt-native-packager#768]
Like discribed in the documentation (http://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/customize.html ) I'd like to use the application.ini to set jvm options, unfortunatly it doesn't work.  In the bat-template I found that seetings being epected to be defined here @APP_ENV_NAME@@_config.txt .   

When I set the values there its working.

**Comment by muuki88** [comment]
Hi,

Thank you for your issue report. The windows documentation is not very sophisticated. It would be awesome if you could provide small pull request with the describe findings above :)

thanks,
Muki

**Comment by wofr** [comment]
Hi!

I added a hint for Windows users.
https://github.com/sbt/sbt-native-packager/pull/774
