### ISSUE TITLE
Handle SIGTERM in service archetypes

### ISSUE THREAD

**Issue by wsargent** [sbt/sbt-native-packager#770]
From https://github.com/playframework/playframework/issues/5933

> When stopping a play app using the systemd init system, systemd sends a SIGTERM to the process, the jvm then exits with the 143 code which, since it's nonzero, is treated as a failure by systemd.

> I think play should handle this itself and exit cleanly. As it is, we have to add SuccessExitStatus=143 to the service file (for a similar discussion see https://tickets.puppetlabs.com/si/jira.issueviews:issue-html/SERVER-70/SERVER-70.html).

**Comment by muuki88** [comment]
@wsargent if I understood the issue correctly we would either

- add `-` the `ExecStart` parameter
- or add an `ExitSuccessStatus` setting

in the [systemd template](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/java_server/systemloader/systemd/start-template)

**Comment by wsargent** [comment]
I think he's asking for "ExecStart=-143" in the systemd template, yes.
