### ISSUE TITLE
Support for Alpine Linux with only sh

### ISSUE THREAD

**Issue by nlhkh** [sbt/sbt-native-packager#773]
I was trying to use Alpine Linux base Docker image. However the container from the built image cannot start because the start script has a `bash` hashbang up top, and Alpine Linux does not come with `bash` by default. I can easily install bash to Alpine Linux, but I wonder if `bash` is necessary to run an SBT program or `sh` is more than enough.

**Comment by muuki88** [comment]
Hi

Thanks for feature request. We already have a [ash configuration plugin](http://sbt-native-packager.readthedocs.org/en/latest/archetypes/misc_archetypes.html#ashscript-plugin). I'm not sure if this is enough, but you could try or use it as an example on how to create your own Sh script ( and maybe provide it as a PR :) )

**Comment by schmitch** [comment]
Actually I used the `AshScriptPlugin` and it looked working.
 
    schmitch@SHANGHAI:~/projects/schmitch/hansili$ docker run -ti -p 9092:9092 hansili:SNAPSHOT -Dhttp.port=9092
    bin/hansili: line 45: is_cygwin: not found
    bin/hansili: line 45: addJava: not found
    [info] - application - Creating Pool for datasource 'default'
    Oops, cannot start the server.

the failure is due to the database connection, but it actually started correctly. The base image was: `java:openjdk-8u77-jre-alpine`.

**Comment by nlhkh** [comment]
Yes. AshscriptPlugin works well :). Thanks

**Comment by ogirardot** [comment]
is it me, or does it seem like this plugin is no longer supported ?

**Comment by muuki88** [comment]
What concrete issue do you have? And to which plugin are you referring?

**Comment by ogirardot** [comment]
Well the Bash template of the JavaAppPackaging is not (obviously) compatible out of the box with ash of the alpine distribution. And I thought the plugin AshscriptPlugin referred to in this PR did not seem to exist anymore but with further research it seems its only available since the 1.2.0 which is not yet released right ?

**Comment by muuki88** [comment]
The `AshScriptPlugin` is available since `1.0.4`. See [the related tags](https://github.com/sbt/sbt-native-packager/commit/250ae60881ae2a7aa9a1e7c7b74160bfba140d76) in the initial commit.

In `1.2.x` the plugin was moved in another package, but that doesn't have any user impact.
