### ISSUE TITLE
add support for building 32-bit RPMs on 64-bit Linux

### ISSUE THREAD

**Issue by dpennell** [sbt/sbt-native-packager#784]
I need to build an RPM that includes a 3rd party native library and my build server is 64-bit.

If I use `noarch`, rpmbuild complains with:
> [error] error: Arch dependent binaries in noarch package

If I use `i386`, rpmbuild complains with:
> [error] error: No compatible architectures found for build

Running the following works:
> setarch i386 sbt
>rpm:packageBin

I propose to add a `setarch` setting in Rpm that will invoke:
>setarch <arch> rpmbuild ...

If noboty objects, I'll generate a pull request shortly.

Note:  running `setarch <arch> sbt...` is inconvenient as I have a multi-project build with each subproject generating a different rpm and one of the other sub-projects includes native 64-bit libraries.

**Comment by muuki88** [comment]
Thanks @dpennell for your request + proposal. Your suggestion sounds good. If I understand correctly `setarch` will is an rpm specific setting, so the setting should be named `rpmSetarch`. 

We have a small developer guide in our wiki. Looking forward :)

**Comment by muuki88** [comment]
Closed via #786
