### ISSUE TITLE
brp-java-repack-jars still running despite setting rpmBrpJavaRepackJars to false

### ISSUE THREAD

**Issue by jjunqueira** [sbt/sbt-native-packager#789]
Hi,

This is related to this http://stackoverflow.com/questions/36940733/sbt-native-packager-rpm-brp-java-repack-jars-still-running-despite-setting-rpmbr question.

I was asked to open an issue referencing this https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala#L112.

Let me know if I can provide any more information.

**Comment by muuki88** [comment]
Awesome, thanks :) 

> Let me know if I can provide any more information

A pull request would be the only thing left to do ;)

**Comment by YuvalItzchakov** [comment]
I've tried using both the mentioned workaround (http://stackoverflow.com/a/36966909/1870803) and using `rpmBrpJavaRepackJars := false` with sbt-native-packager 1.1.0-RC and 1.1.1. Both are being ignored doing rpm packaging and I still see `brp-java-repack-jars` being ran.

Am I missing something?

    lazy val rpmBuildSettings = Seq(
      rpmPrefix := Some(defaultLinuxInstallLocation.value),

      linuxPackageSymlinks := Seq.empty,
      defaultLinuxLogsLocation := defaultLinuxInstallLocation.value + "/" + name.value,

      rpmBrpJavaRepackJars in Rpm := false,
      rpmBrpJavaRepackJars := false,

      //64bit architecture
      packageArchitecture in Rpm := "x86_64",

      //name of the package will be as the project name (defined in project's build.sbt)
      packageName in Rpm := s"${name.value}",

      //Start of FAT jar configuration

      // we specify the name for our fat jar
      assemblyJarName := s"${name.value}_${version.value}.jar",
      // the bash scripts classpath only needs the fat jar
      scriptClasspath := Seq(assemblyJarName.value),
      
      // removes all jar mappings in universal and appends the fat jar
      mappings in Universal := {
        // universalMappings: Seq[(File,String)]
        val universalMappings = (mappings in Universal).value
        val fatJar = (assembly in Compile).value

        // removing means filtering
        val filtered = universalMappings filter {
          case (file, fileName) => !fileName.endsWith(".jar")
        }

        filtered :+ fatJar -> ("lib/" + fatJar.getName)
      },
      //End of FAT jar configuration

      //Takes the application.conf file from resources and puts it in conf folder during installation
      mappings in Universal += {

        val resources = (resourceDirectory in Compile).value
        val conf = resources / "application.conf"
        conf -> "conf/application.conf"
      }
    )

**Comment by muuki88** [comment]
Thanks for your report. Try the following to verify that this is an issue with native-packager

1. Build your rpm with `rpm:packageBin`
2. Open the `spec` file in the `/target/rpm/...`. It must include

```
%define __os_install_post \
%{_rpmconfigdir}/brp-compress \
%{!?__debug_package:%{_rpmconfigdir}/brp-strip %{__strip}} \
%{_rpmconfigdir}/brp-strip-static-archive %{__strip} \
%{_rpmconfigdir}/brp-strip-comment-note %{__strip} %{__objdump} \
%{nil}
```

which [gets inserted here](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala#L108-L116) ( [source](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/rpm/brpJavaRepackJar
) )

If this is all okay, can you add some information of your build system?
- OS
- rpm version

cheers,
Muki

**Comment by jannylund** [comment]
The problem is that the setting is actually inversed (as suggested here https://github.com/sbt/sbt-native-packager/pull/199#commitcomment-17127981 )

Setting `rpmBrpJavaRepackJars in Rpm := true` will skip the repackaging, but documentation refers to setting it to `false` for skipping.

**Comment by mr-git** [comment]
are there any plans to fix this issue?

**Comment by muuki88** [comment]
hi @mr-git 

> A pull request would be the only thing left to do ;)

If you have the time to fix this, I'm happy  to merge it :)
