### ISSUE TITLE
Usage of JavaAppPackaging scriptClasspath

### ISSUE THREAD

**Issue by luigiberrettini** [sbt/sbt-native-packager#793]
I do not want to use a wildcard classpath to avoid having a different ordering from the one used by sbt and I saw that you defined scriptClasspath as "A list of relative filenames (to the lib/ folder in the distribution) of what to include on the classpath."

1. If I don't override it is there a default value used to create the launcher / classpath jar?
2. If not, what is the right way to override it preserving sbt ordering and specifying filenames with a path relative to the lib folder?
3. Are only files in lib allowed or also files in other folders (provided I can get their path as a relative path to the lib folder)?

Thank you!
Luigi.

**Comment by muuki88** [comment]
Thanks for your questions @luigiberrettini . What is the issue you are facing and which problem are you trying to solve?

> If I don't override it is there a default value used to create the launcher / classpath jar?

Yes. If you take a look at the generated start scripts (bash/bat), you will see that every dependency is listed explicitly. You don't have to configure anything if you use the `JavaAppPackaging` archetype. The `LauncherJarPlugin` and `ClasspathJarPlugin` just alter the start command to avoid [long classpath problems](http://sbt-native-packager.readthedocs.io/en/latest/recipes/longclasspath.html)

> If not, what is the right way to override it preserving sbt ordering and specifying filenames with a path relative to the lib folder?

You can just append/prepend stuff the `scriptClasspath` if needed.

> Are only files in lib allowed or also files in other folders (provided I can get their path as a relative path to the lib folder)?

You can add anything you want to the classpath as long it's accessible on your target system.

**Comment by luigiberrettini** [comment]
Thank you!
I managed to create the launcher JAR and the manifest contains the full classpath without me writing anything.

I also managed to alter mappings so that the launcher JAR is moved to the folder containing lib and conf folders.
How can I modify classpath to add "lib/" in front of each entry?

**Comment by muuki88** [comment]
This is strange. Acutally by using

```scala
enablePlugins(ClasspathJarPlugin)
```

everything should just work.

**Comment by luigiberrettini** [comment]
Indeed, but I wanted to change the behavior: instead that all JARs (included the launcher) inside the lib folder I wanted to have the launcher in the folder containing the lib one and all other JARs in the lib folder.

**Comment by muuki88** [comment]
Ah. Now I get it. Is there any particular reason for this?

**Comment by luigiberrettini** [comment]
Just to separate the launcher: in this way I can also guarantee the "without launcher JAR" behavior using a * classpath
