### ISSUE TITLE
support multiple main classes in a single module

### ISSUE THREAD

**Issue by sclasen** [sbt/sbt-native-packager#80]
While it is possible to get native packager to output start scripts for each of a multi-module project, it would be nice if there was an optional way to pass the main class to the bin script, `target/universal/stage/bin/<module> -m some.main.Clazz`

this might also bring for free a repl without sbt needed? (not sure of the mechanics)
`target/universal/stage/bin/<module> -m the.scala.repl.main.Clazz`

**Comment by divijan** [comment]
Hi, I have come across this issue searching for a way to package a project with two main classes. The OP states it is possible, but more recent [StackOverflow discussion](http://stackoverflow.com/questions/25059613/can-sbt-native-packager-generate-multiple-start-scripts-for-one-project?rq=1) suggests the opposite. I am confused.

**Comment by tpunder** [comment]
The sbt-native-packager generated script allows you to pass in a `-main` argument to specify the main class you want to run.  Here's what I do for a project named `foo`:

Create a `run.sh` script with whatever common options you want that calls the sbt-native-packager generated script:
```
#!/bin/bash

./target/universal/stage/bin/foo -main "$@"
```
Then I create a separate script for each main class I want to run.  For example `first.sh`:
```
#!/bin/bash

export JAVA_OPTS="-Xms512m -Xmx512m"

./run.sh com.example.FirstApp -- "$@"
```
and `second.sh`:
```
#!/bin/bash

export JAVA_OPTS="-Xms2048m -Xmx2048m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC"

./run.sh com.example.SecondApp -- "$@"
```

**Comment by divijan** [comment]
that makes sense. Can I then package the two scripts into two upstart services, or one which would run both scripts?

**Comment by tpunder** [comment]
Not sure about upstart.  I'm usually packaging up my stuff using docker (although I don't use the sbt-native-packager docker functionality for that).

**Comment by muuki88** [comment]
@tpunder thanks for sharing! saw your SO answer, too late before suggesting an edit.

@divijan So your use-case is starting two different applications, right? The recommended way would be to package two applications by adding two submodules for each package. This way you have redudant code, but a clear separation.

**Comment by divijan** [comment]
@muuki88 not sure I understand your suggestion. I have one sbt project with two main classes I would like to run. Should I package my project twice with different main class selected in build.sbt?
