### ISSUE TITLE
Multimodule: `docker:publish` error in virtual root

### ISSUE THREAD

**Issue by alaz** [sbt/sbt-native-packager#800]
I have a multimodule project in SBT where root project is a virtual project to aggregate both subprojects. It looks similar to this code:

```
lazy val root = (project in file("."))
  .aggregate(web, backend)
  .settings(
    publishArtifact := false
  )

lazy val web = project
  .enablePlugins(PlayScala, BuildInfoPlugin, DockerPlugin)

lazy val backend = project
  .enablePlugins(BuildInfoPlugin, JavaServerAppPackaging, DockerPlugin)
```

The subprojects generate own Docker containers and this works perfectly. When I call `docker:publishLocal`, the whole build succeeds. But I experience the problem when calling `docker:publish`. Both subprojects get pushed, but I still get the error from "root" project:

```
[trace] Stack trace suppressed: run last root/*:publishConfiguration for the full output.
[error] (root/*:publishConfiguration) Repository for publishing is not specified.
```

Is there a way to get rid of this false error?

**Comment by muuki88** [comment]
Thanks for your detailed description. You need to disable the `publish in Docker`  task for your root project.

```scala
lazy val root = (project in file("."))
  .aggregate(web, backend)
  .settings(
    publish in Docker := {}, // something like this
    publishArtifact := false
  )
```

This way `root/docker:publish` won't be executed.

**Comment by alaz** [comment]
Thank you
