### ISSUE TITLE
Rpm and Deb packaging is missing 'provides' and 'conflicts' tags/sections

### ISSUE THREAD

**Issue by 412b** [sbt/sbt-native-packager#801]
Those sections are essential for package management and package relationship descriptions.

**Comment by muuki88** [comment]
Thanks for the info. You mean `rpmConflicts` and more keys are missing from the documentation?
Would you like to make a pull request?

**Comment by 412b** [comment]
@muuki88 I mean that I don't see a way to set those in control file for rpm or deb package.
e.g. for debian there are `debianPackageDependencies` and `debianPackageRecommends`, but nothing like `debianPackageProvides` and `debianPackageConflicts`...
Or is there a straight-forward way to set those I'm missing?

**Comment by muuki88** [comment]
For the debian there is only `debianPackageRecommends` and `debianPackageDependencies`.

`rpm` however has `rpmProvides`, `rpmRequirements`, `rpmPrerequisites`, `rpmObsoletes`, `rpmConflicts` and `rpmDependencies`.

So debian may need some additional settings. Unfortunately the `DebianPlugin` is a bit more confuse. However if you want, I can help you with making a pull request, adding the requested debian features.

**Comment by 412b** [comment]
@muuki88 yep, let's give it a try then, we need those features
