### ISSUE TITLE
Disable service autostart during package install

### ISSUE THREAD

**Issue by jpic** [sbt/sbt-native-packager#807]
Currently, our service packaged with sbt-native-package auto-starts after apt-get install. In our case, it may fail to start with the default configuration. We might want to 0. apt-get install 1. do our config file and 2. start the service. Is this use case supported ?

Note that I haven't tested [inhibiting rc.d](https://jpetazzo.github.io/2013/10/06/policy-rc-d-do-not-start-services-automatically/) which might work too, so I'm unsure about the importance of this use case.

**Comment by muuki88** [comment]
This is currently hard coded in the [SystemloaderPlugin](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemloaderPlugin.scala#L81-L96).

You could filter out the specific lines from `maintainerScripts in Debian`, which is kind of hacky and breaks if we change a little bit of the bash code.

More over the [startService bash method](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/loader-functions#L5-L19) currently does two things: _register_ the service and _start_ it. 

So this would be a feature request to refactor those into two functions and provide an option to disable the auto start.

**Comment by jpic** [comment]
Just wanted to let you know that my friends affected by this are currently unable to work on this because they are at the Scala days in Berlin if I'm not wrong.

Will pick it up next week.

Thanks for your patience.

**Comment by muuki88** [comment]
Oh no! I was in Berlin, too. We could have paired this 🤗

**Comment by jpic** [comment]
<3 the idea, can we perhaps pair on that some time this week ?

**Comment by muuki88** [comment]
Sure thing. Hangout or Skype would be fine. Just write me an email or a twitter pn.

**Comment by redarqas** [comment]
i'll start working on play showcase app, to share problems that we encounter.

**Comment by jpic** [comment]
Question: how should this feature look like for the user ? should we add a file like "no_autostart" in a directory or should we set the option elsewhere ?

**Comment by muuki88** [comment]
Good question. The obvious way would be to add a setting `serviceAutostart = settingKey[Boolean]` in the `SystemloaderPlugin`, which is by default _true_ to preserve current behaviour. This solution doesn't scale if we would want to make more customizations to the systemloader behaviour, but I can't think of a lot more things you should be able to customize via settings. So I would go for a simple setting.

**Comment by dpennell** [comment]
if nobody objects, I'd like to take this and submit a pull request later today.  I encountered the same issue a few weeks ago and hacked something in my local build to unblock my team.  I'll incorporate the `serviceAutostart` setting described above.

**Comment by muuki88** [comment]
Looking forward to your pr 😃

**Comment by dpennell** [comment]
PR submitted, all tests passed

**Comment by muuki88** [comment]
Closed with #847
