### ISSUE TITLE
Parametrized java home

### ISSUE THREAD

**Issue by cquiroz** [sbt/sbt-native-packager#816]
I want to make my packages (tarball and rpm) include the jre. I have managed to include the jre but I cannot make the `-java-home` parameter work correctly. I'd like to do something like

`-java-home ${app_home}/../jre`

but the bash script doesn't support recursive variable expansion. Specifically this line

`     -java-home) require_arg path "$1" "$2" && java_cmd="$2/bin/java" && shift 2 ;;`

Ideally `$2` could be `eval` before running. I changed the script to this and it works but I cannot claim it is the best way to do it

`     -java-home) require_arg path "$1" "$2" && jre=`eval echo $2` && java_cmd="${jre}/bin/java" && shift 2 ;;`

Is there another way to go?

**Comment by muuki88** [comment]
If you want to package the jre, I would recommend using the [JdkPackagerPlugin](http://sbt-native-packager.readthedocs.io/en/latest/formats/jdkpackager.html). It requires java 8 on your build system, but you can easily include the jre.

Regarding your bash script additions: I'm really not an expert considering bash. In my personal experience it's always a good idea to keep that bash magic as small possible.

**Comment by cquiroz** [comment]
I'd like to produce a tarball and rpm containing the jre, it seems neither option is very well supported by `JdkPackagerPlugin` hence the modification of the launch script

I can fix this by doing my own bash launcher template but this maybe useful more generally

**Comment by muuki88** [comment]
Can you post your complete build configuration that is necessary to achieve this? The _how_ to do this is definitely useful.

**Comment by cquiroz** [comment]
This is a condensed version of my build configuration

```
  lazy val app_server = project.in(file("app/server"))
    .enablePlugins(JavaServerAppPackaging)
    .settings(
      // Main class for launching
      mainClass in Compile := Some("MainClass"),
      // Name of the launch script
      executableScriptName := "server",
      // No javadocs
      mappings in (Compile, packageDoc) := Seq(),
      // Don't create launchers for Windows
      makeBatScript := None,
      // Specify a different name for the config file
      bashScriptConfigLocation := Some("${app_home}/../conf/launcher.args"),
      // Launch options
      javaOptions in Universal ++= Seq(
        // -J params will be added as jvm parameters
        "-J-Xmx512m",
        "-J-Xms256m",
  
        "-java-home ${app_home}/../jre"
      ),
      
      // Put the jar files in the lib dir
      mappings in Universal <+= (packageBin in Compile) map { jar =>
        jar -> ("lib/" + jar.getName)
      },

      // Put the jre in the tarball
      mappings in Universal ++= {
        val jresDir = (ocsJreDir in ThisBuild).value
        // Map the location of jre files
        val jreLink = "JRE64_1.8"
        val linux64Jre = jresDir.toPath.resolve("linux").resolve(jreLink)
        directory(linux64Jre.toFile).map { j =>
          j._1 -> j._2.replace(jreLink, "jre")
        }
      }      
    )

```

The `-java-home` option requires the fix on the launcher to replace the `${app_home}` variable
