### ISSUE TITLE
docker: tag -f is deprecated

### ISSUE THREAD

**Issue by ahjohannessen** [sbt/sbt-native-packager#818]
As of docker 1.10.1 `-f flag on docker tag` is deprecated and removed in 1.2.0:

```scala
val latestCmd = Seq("docker", "tag", "-f", tag, name)
```

https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L284

They explain the motivation for removing it as follows:
>To make tagging consistent across the various docker commands, the -f flag on the docker tag command is deprecated. It is not longer necessary to specify -f to move a tag from one image to another. Nor will docker generate an error if the -f flag is missing and the specified tag is already in use.

So, can we please remove that usage?

**Comment by muuki88** [comment]
Happy to accept a pull request. Will release ASAP :)

**Comment by ahjohannessen** [comment]
@muuki88 I think @sgrankin beat me to it 👍
