### ISSUE TITLE
Specify default memory parameters of java_application BASH script in the build

### ISSUE THREAD

**Issue by abrutus** [sbt/sbt-native-packager#82]
I downloaded a sample app for the latest version of play
packaged it using debian:packageBin and then installed it in my VM with 512 megs of ram
but when I try to run it I get this

    Error occurred during initialization of VM
    Could not reserve enough space for object heap

While you can specify `-mem` to the script to fix this, it'd be nice if the default configuration for memory requirements was configurable.

**Comment by huntc** [comment]
I'd like to re-visit this issue. As more microservice style applications are developed then having a default of `-Xms1024m -Xmx1024m` seems excessive. I recently observed a medium sized EC2 machine running out of space within only 3 services running.

Why not just lean on the default `mx` of Java which is 64m respectively. `ms` could still equal `mx`.

Developers need to think about the memory required for their apps. Unfortunately the current settings do little to provoke that thought in practice.

**Comment by muuki88** [comment]
@huntc the easiest way of doing the shell part would be to remove the `-mem` option. It adds a lot of possible errors in the bash script and doesn't add any convenience as the jvm figures out most of the stuff itself.

@jsuereth I really would like to remove this part as it only gets more tricky with each additional request.

**Comment by kardapoltsev** [comment]
+1 for removing `-mem`.
