### ISSUE TITLE
DockerPlugin overwrites version

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-native-packager#830]
If you define `version.in(Docker) := "latest"`, your `version` will also be `"latest"`:

For some reason `version` delegates to `docker:version`:
```
[reactive-flows]> inspect version
[info] Setting: java.lang.String = latest
[info] Description:
[info] 	The version/revision of the current module.
[info] Provided by:
[info] 	{file:/Users/heiko/projects/scala/reactive-flows/}reactive-flows/docker:version
[info] Defined at:
[info] 	/Users/heiko/projects/scala/reactive-flows/build.sbt:31
[info] Reverse dependencies:
[info] 	docker:dockerTarget
[info] Delegates:
[info] 	docker:version
...
```

**Comment by muuki88** [comment]
Can you provide a failing test as a pull request?

**Comment by hseeberger** [comment]
How should I test this? Would a link to a GitHub project which shows this behavior also work?

**Comment by muuki88** [comment]
We have `sbt scripted` integration tests. One could inspect that setting a `version in Docker` doesn't affect `version`.

**Comment by muuki88** [comment]
I can't reproduce this with the test project in native-packager. What I did

1. Change the `build.sbt` in _test-project-docker_ to contain
```scala
enablePlugins(JavaAppPackaging, DockerSpotifyClientPlugin)
name := "docker-test"

version := "0.1.0"
version in Docker := "latest"

maintainer := "Gary Coady <gary@lyranthe.org>"
```
2. Fire up sbt and `; show version ; show docker:version`. Printing the expected results.

**Comment by hseeberger** [comment]
All right, the issue might be related to using sbt-git with `GitPlugin.autoImport.git.useGitDescribe := true`.

You can reproduce it with https://github.com/hseeberger/reactive-flows.

**Comment by muuki88** [comment]
Famous quote:

> This is not a bug, it's a feature

You have no `version := "x.y.z"` setting in your build definition, so it seems sbt picks up the next best definition of `version` and uses it.

**Comment by hseeberger** [comment]
Have you seen that I'm using versionWithGit?

**Comment by hseeberger** [comment]
I wanted to say useGitDescribe, see project:Build.scala.

**Comment by muuki88** [comment]
Then there seems to be a conflict between these two plugins. Setting a concrete version works :/

**Comment by hseeberger** [comment]
All right, I have investigated the issue. sbt-native-packager (at least `JavaAppPackaging`) seems to overwrite the version of each project:

```
> inspect version
[info] Setting: java.lang.String = 0.1-SNAPSHOT
[info] Description:
[info] 	The version/revision of the current module.
[info] Provided by:
[info] 	{file:/Users/heiko/tmp/version-issue/}version-issue/debian:version
[info] Defined at:
[info] 	(com.typesafe.sbt.packager.debian.DebianPlugin) DebianPlugin.scala:94
```

sbt-git on the other hand sets the `version.in(ThisBuild)`, hence sbt-native-packager wins.

The workaround is setting the version accordingly: `version := version.in(ThisBuild)`.

**Comment by hseeberger** [comment]
I think this is rather an issue of sbt-git by using the build settings rather than the project settings. Sorry for the noise!

**Comment by muuki88** [comment]
No problem 😉
