### ISSUE TITLE
How to customize launcher script's `-h` output to include my application's own options?

### ISSUE THREAD

**Issue by alexeyr** [sbt/sbt-native-packager#831]
I would expect this to be a common requirement, but couldn't find it in http://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/index.html.

**Comment by muuki88** [comment]
Thanks for your feature request, but I think this feature is out of scope for native packager.

The command line options are for the start script alone. I can't see the advantage in defining your cli options in the bash script and in your application. If you use [scopt](https://github.com/scopt/scopt) or _finagle flags_ you will get parsing, validating and help messages all in one.

**Comment by alexeyr** [comment]
That's precisely it: if the users pass `-h` or `-help`, they get one set of options; if they pass `--help` (or perhaps `-- -h`), they get another. And the usage message of the start script can't tell them about `--help`.

**Comment by alexeyr** [comment]
I definitely _wouldn't_ want to define the options in two places.

**Comment by muuki88** [comment]
So a more helpful `help` message from the bash start-script would at least ease this confusion? There is a friction between the built application and the default start script. I'm not sure how we could close this gap in a user friendly and easy way.

**Comment by alexeyr** [comment]
Yes. One approach I thought of is to have an SBT setting telling `sbt-native-packager` what arguments to pass for usage information. If it's e.g. `Some("--help")`, `<start-script> -h` ends with printing `Usage message for the application:` and then calling `<java-command> --help`.

**Comment by muuki88** [comment]
Yeah, that would be possible, but can get tricky.

1. Custom `mainClass` definitions must be taken into account when [processing the app args](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template#L221)
2. What usage is printed on an invalid input?
3. What happens with non-parsed inputs? 

I'm not saying this is not possible, nor not useful. My main concern is making the bash-script more complex that it already is. If the "usage printing logic" can be optionally plugged in, then this would be nice, but I fear this is not simple possible either.
