### ISSUE TITLE
docker:publishLocal results in error with Docker 1.12.0-rc3

### ISSUE THREAD

**Issue by maciej** [sbt/sbt-native-packager#838]
Calling `docker:publishLocal` on a project from SBT results in:

```
[info] Built image [REDACTED]/[REDACTED]:prod
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.
```

I'm using sbt-native-packager 1.1.2, latest OSX / MacOS and _Docker for Mac_.

```
✗ docker --version
Docker version 1.12.0-rc3, build 91e29e8, experimental
```

**Comment by nlhkh** [comment]
I am seeing the same issue. Must be that the packager did not accommodate for update in Docker command.

**Comment by nlhkh** [comment]
[818](https://github.com/sbt/sbt-native-packager/issues/818)

**Comment by maciej** [comment]
I've created a backport of the PR to the `1.1.x` branch: #845.

@muuki88 would it be possible to get it accepted in the 1.1.x branch and released? :-)

**Comment by muuki88** [comment]
@maciej perfect. I will take a look and get a release out ASAP.

**Comment by maciej** [comment]
@muuki88 awesome, thank you!
