### ISSUE TITLE
Adding support for docker build args

### ISSUE THREAD

**Issue by rsemlal** [sbt/sbt-native-packager#844]
During docker:publishLocal, it would be nice to be able to customize the docker build command or at least having support for adding docker build args (https://docs.docker.com/engine/reference/commandline/build/#/set-build-time-variables-build-arg)

**Comment by muuki88** [comment]
I posted a suggestion on how to implement this here #806 Maybe you can try a pull request?

**Comment by NeQuissimus** [comment]
Is this not solved by #854 ?

**Comment by muuki88** [comment]
True! Thanks for mentioning 😃

**Comment by pawelkaczor** [comment]
The support for docker build options (#854) is not enough. The Docker `build args` require the ARG instruction in the Dockerfile:  
https://docs.docker.com/engine/reference/builder/#arg
