### ISSUE TITLE
serverAutostart not available to configure

### ISSUE THREAD

**Issue by christophercampbell** [sbt/sbt-native-packager#852]
The docs indicate that the systemloaders can be set to not start after install, and I really need to be able to do this.

http://www.scala-sbt.org/sbt-native-packager/archetypes/systemloaders.html

This for example works:

serverLoading in Rpm := ServerLoader.Systemd

But this does not:

serverAutostart in Rpm := false

I am using sbt-native-packager 1.1.4

**Comment by muuki88** [comment]
H

Sorry for the confusion. The github page somehow shows the wrong version. If you go to http://sbt-native-packager.readthedocs.io/en/latest you will see that this is only for `1.2.0-M3` not in the `1.1.4` version.

**Comment by christophercampbell** [comment]
It does not exist in 1.2.0-M3 either.

**Comment by muuki88** [comment]
You are right! This hasn't been released yet. Will create a `1.2.0-M4`

**Comment by muuki88** [comment]
Released
