### ISSUE TITLE
If there are two 'App' objects in project, `docker:publishLocal` task will silently produce invalid image without `bin/app-name` file

### ISSUE THREAD

**Issue by Ajk4** [sbt/sbt-native-packager#858]
If there are two 'App' objects in project, `docker:publishLocal` task will siliently produce invalid image without `bin/app-name` files, which will fail upon running container.

Expected behaviour would be to fail fast - at `docker:publishLocal` time with proper message.

Adding explicit 

`mainClass in Compile := Some("my.Class")`

solves the issue

**Comment by muuki88** [comment]
This part is not covered [in the docs](http://sbt-native-packager.readthedocs.io/en/latest/archetypes/java_app/index.html#usage). Feel free to make a pull request to add this information.

We are currently working on a more generic solution in #839
