### ISSUE TITLE
ash-template doesn't have the addApp function like in bash template

### ISSUE THREAD

**Issue by botany** [sbt/sbt-native-packager#862]
This creates some pain cause the configuration flags can't be passed to the application when using an ash template.

**Comment by muuki88** [comment]
Thanks for your feature request. Would you be able to add this in a pull request?

**Comment by botany** [comment]
Okay, I'll try.

**Comment by NeQuissimus** [comment]
This can be closed because of #866 and friends, right? @muuki88

**Comment by muuki88** [comment]
I guess only `addJava` was added. So this is still valid
