### ISSUE TITLE
Environment Variables in Command Not Handled

### ISSUE THREAD

**Issue by apeschel** [sbt/sbt-native-packager#868]
Relevant code:

https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/bash-template#L248-L255

If an environment variable is passed in via the command string, it is never interpolated.

For example:

```
command: ['-Dfoo.bar=$FOOBAR']
```

Will result in this script executing the program with the literal flag `-Dfoo.bar=$FOOBAR`

This means that there is no mechanism to handle shell interpolation via the command string/array at the moment.

**Comment by muuki88** [comment]
I think this feature is still not resolved, but at this point in time I would rather not implement this. There are plenty of options to deal with environment variables

- the `JavaServerAppPackaging` supports sourcing of a etc configuration file
- your application can read environment variables itself
- you can add arbitrary code to the bash script
- you can override the bash script if all other options are not enough
