### ISSUE TITLE
System Loader scripts are not being generated

### ISSUE THREAD

**Issue by MojoJojo** [sbt/sbt-native-packager#869]
Followed the documentation at [offical page](http://www.scala-sbt.org/sbt-native-packager/index.html) and created a new simple scala project (Mac OS) with the following:

plugins.sbt:
```
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.0-M5")
```

build.sbt:

```
enablePlugins(JavaServerAppPackaging)
enablePlugins(SystemVPlugin)
startRunlevels  :=Option("3")
maintainer := "Donald Duck"
packageSummary := "Native packager test project"
packageDescription := "Native packager test project"
stopRunlevels :=Option("3")
rpmVendor:="Donald Duck"
```

src/main/scala/Hello.scala:

```
object Hi {
  def main(args: Array[String]) = println("Hi!")
}
```

when I run `sbt packageBin` I get a zip file with a bash script to run the java server application but no script to install/uninstall the SystemV service. Am I missing something or is there something wrong with the plugin?

*Edit*: Link to git repo: https://github.com/MojoJojo/sbt-native-packager-test

**Comment by muuki88** [comment]
Your configuration is correct. Your sbt command isn't :)

with `packageBin` ( which IIRC triggers `universal:packageBin` ) generates only a universal zip file. A systemloader is a operating system specific part. That's why it's not included in a universal zip.

Generate a debian or rpm file with

```
debian:packageBin
rpm:packageBin
```

The generated `deb` or `rpm` package will have the systemloader files included, because they are in the place a rpm/debian based system would expect them.

**Comment by MojoJojo** [comment]
Ah. I see. I was hoping that just enabling the right plugin would automagically tell the pluing to generate the right scripts 😛 . thank you for your help.

I installed the rpm and rpm-build packages but now I get the error below:

```
error: Group field must be present in package: (main package)

```

I tried:

```
rpmGroup := "Applications/MyApp"
```

but it still gives me the error. Not sure what I am missing now?

**Comment by MojoJojo** [comment]
Tested a bit more and turns out that the exact build script works perfectly on Fedora and fails on Mac OS. Not sure if building an RPM is supported on Mac OS?

**Comment by MojoJojo** [comment]
Okay, seems like I figured it out. A root project has to be defined with the correct `rpmGroup` in order for the plugin to work:

```

 val main = Project("sbt-native-packager-test",base = file("."))

.enablePlugins(JavaServerAppPackaging)
.enablePlugins(SystemVPlugin)
.settings(rpmGroup:=Some("Applications/SomeGroup"))
.settings(startRunlevels  :=Option("3"))
.settings(maintainer := "Donald Duck")
.settings(packageSummary := "Native packager test project")
.settings(packageDescription := "Native packager test project")
.settings(stopRunlevels :=Option("3"))
.settings(rpmVendor:="Donald Duck")
.settings(rpmRelease:="1")
.settings(version:="0.0.1")
.settings(serverLoading:= Option(ServerLoader.SystemV))
.settings(rpmLicense := Some("BSD"))
```

Now it gives the following errors:
```
[info] Executing(%install): /bin/sh -e /var/folders/4m/t8_hjrk16kncmz84wq7z9sgw0000gn/T/sbt_1ce9e82a/rpm-tmp.12111
[error] + umask 022
[error] + cd /Users/donaldduck/Projects/temp/sbt-native-package-test/target/rpm/BUILD
[error] + /bin/rm -rf /Users/donaldduck/Projects/temp/sbt-native-package-test/target/rpm/buildroot
[error] + /bin/rm -rf /Users/donaldduck/Projects/temp/sbt-native-package-test/target/rpm/buildroot
[error] + '[' -e /Users/donaldduck/Projects/temp/sbt-native-package-test/target/rpm/buildroot ']'
[error] + mv /Users/donaldduck/Projects/temp/sbt-native-package-test/target/rpm/tmp-buildroot /Users/donaldduck/Projects/temp/sbt-native-package-test/target/rpm/buildroot
[error] + exit 0
```

Permission issue perhaps?

**Comment by MojoJojo** [comment]
Oh..guess I can safely ignore this one? #103

**Comment by muuki88** [comment]
> Ah. I see. I was hoping that just enabling the right plugin would automagically tell the pluing to generate the right scripts

You still have to tell sbt what package you want to generate ;) By enabling the `JavaAppArchetype` you can build `zip`, `dmg`, `tar`, `msi`, `deb`, `rpm` and `docker`.

> Oh..guess I can safely ignore this one? #103

Yes, rpm outputs are printed via stderr :(

> Okay, seems like I figured it out. A root project has to be defined with the correct rpmGroup in order for the plugin to work

Hm. Not really. Your [example](https://github.com/MojoJojo/sbt-native-packager-test) looks good. This is [a minimal example from native-packager](https://github.com/sbt/sbt-native-packager/blob/master/test-project-simple/build.sbt).

> Tested a bit more and turns out that the exact build script works perfectly on Fedora and fails on Mac OS. Not sure if building an RPM is supported on Mac OS?

We try to, but the main goal of native-packager is provide a working build on the native platform ( in this case Fedora/RHEL/CentOS)

**Comment by MojoJojo** [comment]
Thank you for the quick responses and the support. Much appreciated. 

I cloned the repository and the [minimal example](https://github.com/sbt/sbt-native-packager/blob/master/test-project-simple/build.sbt) and tried to build it:

```
> rpm:packageBin
[info] Updating {file:/Users/sanketsharma/Projects/temp/sbt-native-packager/test-project-simple/}test-project-simple...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Packaging /Users/sanketsharma/Projects/temp/sbt-native-packager/test-project-simple/target/scala-2.10/test-project-simple_2.10-0.2.0-sources.jar ...
[info] Resolving com.typesafe#config;1.2.1 ...
[info] Done packaging.
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/sanketsharma/Projects/temp/sbt-native-packager/test-project-simple/target/scala-2.10/classes...
[info] Main Scala API documentation to /Users/sanketsharma/Projects/temp/sbt-native-packager/test-project-simple/target/scala-2.10/api...
[info] Wrote /Users/sanketsharma/Projects/temp/sbt-native-packager/test-project-simple/target/scala-2.10/test-project-simple_2.10-0.2.0.pom
model contains 3 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /Users/sanketsharma/Projects/temp/sbt-native-packager/test-project-simple/target/scala-2.10/test-project-simple_2.10-0.2.0-javadoc.jar ...
[info] Done packaging.
[info] Packaging /Users/sanketsharma/Projects/temp/sbt-native-packager/test-project-simple/target/scala-2.10/test-project-simple_2.10-0.2.0.jar ...
[info] Done packaging.
[error] error: Group field must be present in package: (main package)
[info] Building target platforms: noarch-typesafe-Linux
[trace] Stack trace suppressed: run last rpm:packageBin for the full output.
[error] (rpm:packageBin) Unable to run rpmbuild, check output for details. Errorcode 1
[error] Total time: 2 s, completed 21 Aug 2016 12:34:22 PM
```

You are right about the root project, but it still requires `rpmGroup:=Some("Applications/MyGroup")` to package on Mac. On Fedora, it works out of the box.

**Comment by muuki88** [comment]
Interesting. Thanks for testing. What version of `rpm` are you using?
