### ISSUE TITLE
Is there a way to retrieve the path/filename of the generated rpm?

### ISSUE THREAD

**Issue by MojoJojo** [sbt/sbt-native-packager#870]
Hi,

I would like to use the native packager plugin with another plugin that uploads the generated rpm file to AWS S3. Is there a way to access the name/path of the generated rpm in the build?

Thank you for your help and assistance.

**Comment by muuki88** [comment]
Hi,

Sure :) SBT task and settings can be used in any other task/setting you have.
As an example

```scala
s3Upload := {
   // now s3Upload depends on the the rpm:packageBin task and you have the resulting file
   val rpm = (packageBin in Rpm).value 
   // use it
}
```

You can inspect settings in order to get their return value with `inspect rpm:packageBin`.

**Comment by MojoJojo** [comment]
Yip. Figured it out..thank you for the awsome support! 👍
