### ISSUE TITLE
Documentation of dockerUpdateLatest needs updated

### ISSUE THREAD

**Issue by thrykol** [sbt/sbt-native-packager#871]
Release 1.2.0-M5 documentation needs to be updated to indicate that when using `dockerUpdateLatest := true`, needs a minimum Docker version of 1.10 to be installed.  Earlier versions only create the `latest` tag since they only process the last `-t` flag when building an image.  See [https://github.com/docker/docker/issues/863#issuecomment-149771365](https://github.com/docker/docker/issues/863#issuecomment-149771365) for details.

**Comment by muuki88** [comment]
Thanks for opening this issue @thrykol . Would you like to make a small pull request adding this?

**Comment by NeQuissimus** [comment]
This was closed by #874, right?

**Comment by muuki88** [comment]
True. Thanks for writing :)
