### ISSUE TITLE
Use a Dockerfile rather than Scala?

### ISSUE THREAD

**Issue by JontyMC** [sbt/sbt-native-packager#875]
Is it possible to use an actual Dockerfile rather than specify it in Scala? Docker uses would expect to see a Dockerfile so they can easily see the dependencies of the app.

**Comment by fiadliel** [comment]
If you have a Dockerfile, what benefit do you expect from a plugin, over "docker build ."?

**Comment by JontyMC** [comment]
Yeah, realised this after posting. New to play and sbt. I think I just want to call "sbt stage" then docker build. Thanks.

**Comment by muuki88** [comment]
If you call `docker:stage` you'll get a Dockerfile in your staging directory
