### ISSUE TITLE
Docker Image 'chown -R daemon:daemon' duplicates application layer

### ISSUE THREAD

**Issue by gavares** [sbt/sbt-native-packager#883]
sbt-native-packager versions 1.2.0-M5 and 1.1.4

Affer adding application contents to a docker image, another layer is created with command:

```
chown -R daemon:daemon .
```

This touches every file in the application and creates new layer that has the same size as the application. In my case, after adding ~130mb layer containing my app, another 130mb layer is added as a result of touching every file in the my app layer.

`docker history` shows:
![image](https://cloud.githubusercontent.com/assets/46012/18822590/7d4770f8-8366-11e6-8bb0-34a2d59924d9.png)

Wondering if this is necessary and/or if it could be done before adding the files from the application layer to the container.

**Comment by gavares** [comment]
Seems this is caused by a very annoying docker issue that has had years of discussions and github issues opened but still hasn't been fixed.

The current workaround is to perform chown/chmod locally, create a tar of the contents and then ADD the tar which docker will magically unpack, preserving permissions of the contents.

Not sure if there will be any issues getting this to work since a user (probably) won't have the `daemon` user and group locally on their dev machine and, even if they did, the uid/gid probably wouldn't match what is present in the container anyway.

**Comment by muuki88** [comment]
There have already been some discussions on [gitter](https://gitter.im/sbt/sbt-native-packager) on this topic ( I couldn't find unfortunately ).

For docker we have some options to optimize this (e.g. splitting the app jars from the lib jars to enable caching). However this needs time, testing and verification. So if you have good solution with proper research we I'm happy to discuss this on a pull request from you :)

cc @fiadliel

**Comment by NeQuissimus** [comment]
You'll want to follow docker/docker#30110.

If you don't have volumes, it should be reasonably safe to just remove the `USER` and `chown` from the build instructions and thereby save the space. That will, however, cause your applications to be `root`, albeit inside a container.

**Comment by fiadliel** [comment]
Thanks, I'll keep an eye on it, an alternative is the "squash" command (when it becomes stable).

But I would disagree that it's safe to remove USER/chown - the proof lies in decades of escapes from chroots on Unix systems (and Docker containers are just chroots on steroids).

**Comment by NeQuissimus** [comment]
Personally, I am using https://github.com/goldmann/docker-squash, which gets rid of the "root-owned files"-layer altogether.

**Comment by ivantopo** [comment]
hey people, I did a quick and dirty hack to improve layer caching on our projects that basically copies the libraries in one layer and the project files in another layer and completely skips the chown.. I think that the chown could be less problematic if it was also separated in one command for the libs and one for the projects but didn't test it. See this comparison of new/old images:

![image](https://cloud.githubusercontent.com/assets/1302854/25842137/38006ccc-34a3-11e7-8331-8963eda51d2d.png)

before the change we would need to upload 2 layers of 44.4MB every time we do a release, now (if no dependencies change) we would only be uploading 412Kb :tada: 

here is a gist with the changes: https://gist.github.com/ivantopo/8dbc581723458a1614be3c6c11ab90da

@muuki88 would you be interested in a PR?

**Comment by muuki88** [comment]
Thanks @ivantopo for sharing this 😍

I guess we have to start at some point and your gist was the best looking *and* working solution I have seen so far. As a first step I would like to add this as a separate archetype plugin, so people can turn it on if they feel brave enough. Also I would keep the chowing in the first place. Or introduce an setting `dockerChownMappings: Setting key[Boolean]` which triggers this behaviour , but only for the new plugin.

If you need any guidance, feel free to ask. Also don't hesitate to open a pull request early and we discuss details there .

Thanks again and looking forward  to this 😎

**Comment by mosche** [comment]
@muuki88 Just saw this issue. Here's another idea we ended up using.
https://gist.github.com/mosche/0a2ebf0966c449b1c48feb8e52dedd97

The idea is to map libraries and their transitive dependencies into multiple layers that can even be shared between different services :) The only downside: it's using `sbt-dependency-graph` to resolve dependencies. But the result is pretty amazing...

**Comment by muuki88** [comment]
Thanks @mosche for sharing :)

It looks interesting, but I guess would be to specific for native-packager. Creating shared docker images from a single build is something more special. I would also like to avoid a dependency on sbt-dependency-graph.

Splitting application and dependencies into two layers is a performance optimization ( that's really what it's all about ) which yields a hopefully small amount of complexity. And must be explicitly enabled. Creating multiple layers from regex and a 3rd party plugin, won't be maintainable with our limited resources.

Still this is pretty crazy what you can do with this :D

**Comment by NeQuissimus** [comment]
Update: moby/moby#34263 has a fix for this now

**Comment by muuki88** [comment]
Thanks for sharing @NeQuissimus :heart:

**Comment by mrfyda** [comment]
@muuki88 I guess this was also fixed by #1044
