### ISSUE TITLE
Add all jars in lib directory to classpath

### ISSUE THREAD

**Issue by mig-foxbat** [sbt/sbt-native-packager#885]
consider the below scenario,

A application that is distributed as a zip archive to end users has few **provided dependencies**. The end users are expected to provided these **provided dependencies** by dropping in all the **provided dependencies** jars in lib directory. It seems currently any new jars added to the lib directory is not automatically added to the classpath. 

so basically we need a setting/flag in native packager to add all jars in the lib directory to the application classpath. so the following change should take place in the start-up script. 

#### from:
`java -cp /var/path/lib/libary1.jar:/var/path/lib/library2.jar... com.example.Main`

#### to:
`java -cp "/var/path/lib/*" com.example.Main`

**Comment by muuki88** [comment]
Hi,

Thanks for your detailed description. Native-packager already as support for [wildcard classpath](http://sbt-native-packager.readthedocs.io/en/latest/recipes/longclasspath.html#configure-a-wildcard-classpath). You can achieve this by setting

```scala
scriptClasspath := Seq("*")
```

However we won't make this the default behaviour for a couple of reasons

- security. The application only adds things to the classpath it knows about. 
- predictability. Your application will start with the same classpath order each time.
