### ISSUE TITLE
universalArchiveOptions setting tar CLI command arguments: incorrect order (maybe)

### ISSUE THREAD

**Issue by mackler** [sbt/sbt-native-packager#886]
I'm unsure whether or not I'm seeing a bug.  I added this line to my `build.sbt`

    universalArchiveOptions in (Universal, packageZipTarball) := Seq("--exclude", "*~")

and I got a new `tar` error, including (in part) the following output:

    Running with tar --exclude *~ /tmp/sbt_726bf22d/myApp-0.1.tar myApp-0.1
    tar: Must specify one of -c, -r, -t, -u, -x

It looks as if my custom `tar` option may need to come after the tar-file name rather than before.  It might also be causing a `-c` switch to go missing, but that might be a default and unnecessary; I am unsure.

Or maybe I'm doing something wrong.

**Comment by muuki88** [comment]
I guess your configuration is not correct. The options are used [like this](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala#L258).

```scala
val cmd = Seq("tar") ++ options ++ Seq(tmptar.getAbsolutePath) ++ distdirs
```scala

The error message you are seeing also states what is _missing_. As you override the [default configuration](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala#L99), which is

```scala
universalArchiveOptions in (Universal, packageZipTarball) := Seq("-pcvf")
```

the `tar` command isn't complete.
