### ISSUE TITLE
UNRESOLVED DEPENDENCIES - org.scala-sbt#sbt;0.13.12 not found

### ISSUE THREAD

**Issue by jdjasperson** [sbt/sbt-native-packager#887]
I used Homebrew to install scala version 2.11.8 and sbt version 0.13.12 on my mac which is running on El Capitan.

When I execute the "sbt -version" command, I get the following output:
### OUTPUT
    sbt -version
    Getting org.scala-sbt sbt 0.13.12 ...

    :: problems summary ::
    :::: WARNINGS
		module not found: org.scala-sbt#sbt;0.13.12

	==== local: tried

	  /Users/someguy/.ivy2/local/org.scala-sbt/sbt/0.13.12/ivys/ivy.xml

	  -- artifact org.scala-sbt#sbt;0.13.12!sbt.jar:

	  /Users/someguy/.ivy2/local/org.scala-sbt/sbt/0.13.12/jars/sbt.jar

	==== Maven2 Local: tried

	  file:///Users/someguy/.m2/repository/org/scala-sbt/sbt/0.13.12/sbt-0.13.12.pom

	  -- artifact org.scala-sbt#sbt;0.13.12!sbt.jar:

	  file:///Users/someguy/.m2/repository/org/scala-sbt/sbt/0.13.12/sbt-0.13.12.jar

	==== secured-central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.12/sbt-0.13.12.pom

	  -- artifact org.scala-sbt#sbt;0.13.12!sbt.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.12/sbt-0.13.12.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;0.13.12: not found

		::::::::::::::::::::::::::::::::::::::::::::::

    :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
    unresolved dependency: org.scala-sbt#sbt;0.13.12: not found
    Error during sbt execution: Error retrieving required libraries
    (see /Users/someguy/.sbt/boot/update.log for complete log)
    Error: Could not retrieve sbt 0.13.12

When examing the update.log, it simply restates the same thing; "Error retrieving required libraries"

Is there a Maven repository somewhere out there that has the appropriate release?

**Comment by muuki88** [comment]
Hi @jdjasperson 

I'm afraid you are asking this question in the wrong place. Your description sounds like [this problem](https://www.lightbend.com/blog/incident-report-for-repolightbendcom-and-other-bintray-backed-repositories), which should be solved by now.

If not, please go to the sbt repo or gitter channel and asked for help there :)

cheers,
Muki
