### ISSUE TITLE
Don't override packageName in UniversalPlugin

### ISSUE THREAD

**Issue by muuki88** [sbt/sbt-native-packager#902]
Remove [this line](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala#L87)

**Comment by nafg** [comment]
You should use links based on a commit or tag, not a branch. I don't think the link refers to the line you intended anymore.

**Comment by muuki88** [comment]
Damn, you are right. I messed this one up 😩 
Thanks for the hint

**Comment by muuki88** [comment]
I actually meant [this line](https://github.com/sbt/sbt-native-packager/blob/e4e6504c1f6a75fb346958f68d0f7c13fec26877/src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala#L87).

I'm not happy with past-me. He provided not enough information why this is relevant.
