### ISSUE TITLE
please publish to sonatype or somehow sync with maven central

### ISSUE THREAD

**Issue by jozic** [sbt/sbt-native-packager#906]
ready to help if needed

**Comment by muuki88** [comment]
Thanks for your feature request. SBT has the bintray resolver enabled by default.
Do you have company restrictions which restrict you to maven central?

The whole sbt-plugin universe is build around bintray. I would rather ask the sbt folks if they plan to add a general solution for this. Then we would just need to add the necessary meta information, but not a more complicated publishing process.

**Comment by jozic** [comment]
>Do you have company restrictions which restrict you to maven central?

exactly

I would also prefer easier publishing process, but as far as i understand, at the moment the easiest thing is to publish to sonatype. What do you think?

**Comment by muuki88** [comment]
For `sbt` the easiest publishing platform is bintray ATM. There is a sync for bintray to maven central AFAIK, but the project must have all the necessary requirements. Native-packager is currently missing

- [ ] required pom entries (IIRC url, developers, license..)
- [ ] maven style publishing

Still this is an issue that should be solved in general for the sbt-plugin ecosystem.

As a workaround you can publish native-packager to your own, hosted nexus/artifactory instance. The publishing is pretty strait forward.

- checkout the release tag
- point the `publishTo` to the correct direction
- `sbt publish`

**Comment by jozic** [comment]
I'm aware that I can publish it myself, but as you may imagine it's not very convenient to repeat this after new release is published
I also agree that a more general solution would be great, but AFAIK to solve this sbt plugins somehow get it to maven central. Publishing to Sonatype is one way, which is not super easy, but not that hard either. 
Setting up sync of  bintray with maven central is another option, which is probably superior to publishing to Sonatype. 
I can send a PR with missing parts to the build if  that helps. As well setting up sync with central

**Comment by muuki88** [comment]
A PR with the missing parts would be awesome. There is a [sbt documentation](http://www.scala-sbt.org/0.13/docs/Using-Sonatype.html) on this.

It's not that I'm against publishing to sonatype. It adds just another complexity, credentials must be shared, etc. Also this project is maintained mostly in the free time of all developers. Your company hopefully pays you for doing this :)

**Comment by jozic** [comment]
hey @muuki88 
I've just sent a tiny PR with required metadata #922 

artifact has to be signed, but that's already the case according to build.sbt
If you can setup this sync process between bintray and sonatype that would be awesome
If you want me to do that, I'm ready to help, but will probably need some additional access

Please let me know if you need any help to make this happen
Thanks
