### ISSUE TITLE
rpm help show summary of linux default config

### ISSUE THREAD

**Issue by shijinkui** [sbt/sbt-native-packager#912]
hi @muuki88 
can we provide rpm help to show summary of linux default config, such as defaultLinuxInstallLocation/defaultLinuxConfigLocation and so on.

Thanks

**Comment by muuki88** [comment]
What do you mean with _rpm help_? An `sbt` task that prints that to the console? You can define this on your own with `addCommandAlias` (see [stackoverflow](http://stackoverflow.com/a/16435620/709351)

E.g.

```scala
addCommandAlias("show defaultLinuxInstallLocation", "show defaultLinuxConfigLocation")
```

**Comment by shijinkui** [comment]
@muuki88 Thanks 👍
