### ISSUE TITLE
universal:packageBin not working with spaces in path (windows / play application)

### ISSUE THREAD

**Issue by xyztobixyz** [sbt/sbt-native-packager#913]
Hi

My Problem:
When I use `activator dist` to produce a zip file of my play application, unzip this application in a path with spaces 
let's say `D:\unfinished-path with spaces\myproj-1.0`
and run the .bat file I get the following Error:

`Error: Unable to access jarfile D:\unfinished-path`

build.sbt:
```
name := """MyProj"""

version := "1.0"

lazy val root = (project in file(".")).enablePlugins(
  PlayJava,
  JavaAppPackaging,
  UniversalPlugin,
  SonarRunnerPlugin,
  LauncherJarPlugin
)

scalaVersion := "2.11.7"

...

mappings in Universal ++= directory(baseDirectory.value / "public")
mappings in Universal += Tuple2(file("conf/production.conf"), "conf/production.conf")
mappings in Universal += Tuple2(file("conf/logback.xml"), "conf/logback.xml")
....
```

and plugins.sbt

```
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.1.4")
```

Adding `"` to the generated .bat file in `D:\unfinished-path with spaces\myproj-1.0\bin\myproj.bat`

on line 132 before %APP_LIB_DIR%... changing it from
`set "APP_MAIN_CLASS=-jar %APP_LIB_DIR%\myproj.myproj-1.0-launcher.jar"`
to
`set "APP_MAIN_CLASS=-jar "%APP_LIB_DIR%\myproj.myproj-1.0-launcher.jar"`

lets the application start without the error

**Comment by muuki88** [comment]
Use the [launcher jar archetype](http://sbt-native-packager.readthedocs.io/en/latest/recipes/longclasspath.html#generate-a-launcher-jar) to solve this issue.

#577 fixed that issue.
