### ISSUE TITLE
Native package heavily uses and recommends `<+=`, which is deprecated

### ISSUE THREAD

**Issue by clhodapp** [sbt/sbt-native-packager#919]
The now-deprecated sbt dsl operator, `<+=`, is used frequently in the source, build, and docs for native packager. This operator is deprecated as of the latest release of sbt, is going away in sbt 1.0, and should be replaced with just a `+=` and a postfix call to `.taskValue`. It's especially problematic that the docs recommend using it because it sets users up for having to update their builds later and could cause them to see deprecation warnings, as well as requiring them to learn about a concept that isn't explained in the sbt documentation (since it's deprecated).

**Comment by muuki88** [comment]
Yes, you are absolutely right. All newer stuff already uses the recommended operators, but there's a lot of untouched, old code.

I'm happy for every pull request that replaces a deprecated operator 😃

**Comment by muuki88** [comment]
I hope I fixed them all in #931

**Comment by clhodapp** [comment]
Wonderful!

**Comment by clhodapp** [comment]
That was a lot of work, thanks for picking it up!
