### ISSUE TITLE
dockerEntrypoint has no effect in 1.1.4 and 1.1.5

### ISSUE THREAD

**Issue by tsillan** [sbt/sbt-native-packager#927]
I'm trying to override the default ENTRYPOINT of my dockerized Play Framework 2.5 application with dockerEntrypoint by setting the following in my build.sbt:

`dockerEntrypoint := Seq("bin/my-app", "-Dconfig.resource=application-prod.conf")`

but no matter what I do, when I run the _docker:stage_ task the ENTRYPOINT in the generated Dockerfile is always

`ENTRYPOINT ["bin/foobar"]`

where _foobar_ is the name defined for my application in build.sbt:

`name := """foobar"""`

I have tried both sbt-native-packager 1.1.4 and 1.1.5.

I also tried setting `dockerCommands := Seq()` to start from scratch as described here [http://www.scala-sbt.org/sbt-native-packager/formats/docker.html#configuration](http://www.scala-sbt.org/sbt-native-packager/formats/docker.html#configuration) but again no effect. I can change FROM, MAINTAINER and EXPOSE without problems.

Is this known to work in 1.1.4 and 1.1.5 for sure?

**Comment by muuki88** [comment]
Have you found the issue?

**Comment by tsillan** [comment]
A stupid user error not related to sbt-native-packager. Therefore I closed the issue asap. Being pretty new to sbt, I did not realize it does not reload build.sbt automatically (I was running the sbt console).

**Comment by muuki88** [comment]
Build systems tend to be tricky in the beginning 😉
Hope native-packager doesn't get in the way.

Happy hacking.
