### ISSUE TITLE
Docker base image is deprecated

### ISSUE THREAD

**Issue by edouardKaiser** [sbt/sbt-native-packager#928]
The Docker base image used by the packager has been deprecated in Docker hub:

![image](https://cloud.githubusercontent.com/assets/7731641/21481186/0aac4680-cb65-11e6-95f9-66ddfe12e2ee.png)

It should use `openjdk:latest` now.

**Comment by muuki88** [comment]
Thanks for reporting. Would you like to open a pull request to fix this?

**Comment by edouardKaiser** [comment]
I realised it was fixed actually:

https://github.com/sbt/sbt-native-packager/commit/050b3294839dda1229e55696b45132a50bf7fc9b

But it hasn't been picked for the 1.1.5 release

**Comment by edouardKaiser** [comment]
Would it be possible to get a 1.1.6 with that fix?

**Comment by muuki88** [comment]
Sure :) I'll try when I have time. With a small PR on the `1.1.x` branch I might be able to do this  today :)
