### ISSUE TITLE
Support JAVA_OPTS for Ash template, similar to bash

### ISSUE THREAD

**Issue by kwinter** [sbt/sbt-native-packager#940]
It appears as though there is no way to pass JVM options from the environment when using the Ash script plugin, only by declaring them in the ini file or within the build process.  The bash template allows doing this via a JAVA_OPTS environment variable, it would be great to be able to do the same thing with the ash template.

bash handling: https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template#L244

Our specific scenario is that we're using Docker (Alpine) and the AshScriptPlugin, and don't see a way to pass in JVM options from the environment

**Comment by muuki88** [comment]
Sorry for the late reaction. I think this was added with 5b696b9cb6abfd0555314fc1606d3c6ce2959fb2
