### ISSUE TITLE
`rpm:packageBin` reports "`rpmVendor in Rpm` is empty" despite a value being set

### ISSUE THREAD

**Issue by leifwickland** [sbt/sbt-native-packager#943]
Beginning with 1.2.0-M5, attempting to `rpm:packageBin` always fails with the error:
```
`rpmVendor in Rpm` is empty
```
even if a value is set.

Example project to reproduce the problem:
https://github.com/leifwickland/native-bug

**Comment by muuki88** [comment]
Hi @leifwickland 

Thanks for this well done bug report. The error you get is expected. There [is a section in the release notes](https://github.com/sbt/sbt-native-packager/releases/tag/v1.2.0-M5) for this release.

> All settings prefixed with `rpm` were moved out of the `Rpm` scope. This means that you should
remove the `in Rpm` configuration scope for settings and tasks prefixed with rpm.

This should fix your build.

**Comment by leifwickland** [comment]
Thanks for explaining, Nepomuk!

**Comment by LeifW** [comment]
Is this error message going to get update to remove the `in Rpm` part?

**Comment by muuki88** [comment]
IIRC the error message comes from rpm itself. However we plan a validation task in #1026 that will help you figure out the configuration.
