### ISSUE TITLE
Windows: error CNDL0014 $number is not a legal identifier

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-native-packager#946]
## steps

clone sbt/sbt-launcher-package

```
> windows:packageBin
```

## problem

```
[info] C:\xxx\sbt-launcher-package\target\windows\sbt-launcher-packaging.wix(4378) : error CNDL0014 : The ComponentRef/@Id attribute's value, '48dd0744422128446aee9ac31aa356ee203cc9f4_jars_ivy_jar_sha1190649008', is not a legal identifier.  Identifiers may contain ASCII characters A-Z,
a-z, digits, underscores (_), or periods (.).  Every identifier must begin with either a letter or an underscore.
```

## expectations

No error.

## notes

`cleanStringForId` might have to prefix with underscore when the ID starts with a number.

https://github.com/sbt/sbt-native-packager/blob/56e2fc61c5b98410a6c77cbf4a1c944ce0835af7/src/main/scala/com/typesafe/sbt/packager/windows/WixHelper.scala#L259-L260

**Comment by muuki88** [comment]
Hi @eed3si9n 

Thanks for your bug report. 

Do you have a test case where I can reproduce this? ATM I'm testing against the
appveyor test system, so I would open a PR with this test case and then I can fix it.

cheers,
Muki

**Comment by eed3si9n** [comment]
Clone https://github.com/sbt/sbt-launcher-package/tree/v0.13.14, and run

```
$ sbt windows:publish
```
