### ISSUE TITLE
packageName in Docker has no effect

### ISSUE THREAD

**Issue by asarkar** [sbt/sbt-native-packager#947]
I've a [multimodule project](https://github.com/asarkar/spark/tree/master/ufo-sightings) where each module creates a Docker image. I'd like to customize the image name but the following statement has no effect. The image names are still taken from the project names.
```
packageName in Docker := "ufo-sightings-" + name.value
```

Image names:
```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
asarkar/consumer        1.0-SNAPSHOT        8cebb22ff45f        10 minutes ago      393 MB
asarkar/producer        1.0-SNAPSHOT        1684ac156186        45 minutes ago      198 MB
```

**Comment by muuki88** [comment]
Thanks @asarkar for you report. This seems to be a bug.

[This line](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L80) doesn't scope the `packageName` setting correcty.

It should be

```scala
dockerAlias := DockerAlias(dockerRepository.value, None, (packageName in Docker).value, Some((version in Docker).value))
```

Would you like to open a PR to fix this?

**Comment by asarkar** [comment]
@muuki88 I'm just a basic SBT user and also working on other things. I think I'll leave it to the maintainers to fix this issue. Based on your comment, it appears to be a simple fix.

**Comment by muuki88** [comment]
@asarkar no problem :)

Yes, defining your own alias is the way. Sorry that I kept that a bit vague.

**Comment by asarkar** [comment]
@muuki88 Which version is this fix going to be available in?

**Comment by muuki88** [comment]
In the next `1.2.x` milestone release
