### ISSUE TITLE
Add support for HEALTHCHECK in DockerPlugin

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-native-packager#949]
For more information see https://docs.docker.com/engine/reference/builder/#healthcheck.

**Comment by muuki88** [comment]
Thanks @hseeberger for the feature request. Can you give some details on how this support should look like and why this can't  be added via `dockerCommands` :)

**Comment by hseeberger** [comment]
I guess this can easily be added via `dockerCommands` – I just forgot about this feature ;-)

Could you please point me to the documentation of `Cmd` versus `ExecCmd`? If there is any ...

Feel free to close this issue.

**Comment by muuki88** [comment]
Perfect 😉

Regarding `Cmd` and `ExecCmd`. IIRC the difference are the brackets. One with and the other without.
