### ISSUE TITLE
Custom upstart script is append to postinst causing dpkg to fail

### ISSUE THREAD

**Issue by levinson** [sbt/sbt-native-packager#953]
I'm using the latest released version of the sbt-native-packager (1.2.0-M8) and SBT 0.3.11, and enabled the UpstartPlugin on the project, and added the file to src/templates/systemloader/upstart . I built the Debian package using debian:packageBin. I attempted to install this deb package on a Linux server and it failed with an error in postinst script. Upon inspecting the package, I noticed the supplied upstart script as well as being packaged /etc/init was also appended to the generated postinst script, causing it fail, since the syntax is invalid for Debian control files.

I would expect that supplying a custom upstart script would not modify the postinst script.

**Comment by muuki88** [comment]
Thanks @levinson for your bug report. This seems to be the same issue reported in #952
