### ISSUE TITLE
RPM with `killtimeout`

### ISSUE THREAD

**Issue by mr-git** [sbt/sbt-native-packager#957]
SBT: 0.13.13
Server OS: Centos 7.2.x
Development OS: macOS 10.12.4
Scala: 2.11.8
Version: 1.2.0-M8
RPM: 4.8.0

I am trying to use `killTimeout` (http://www.scala-sbt.org/sbt-native-packager/archetypes/systemloaders.html?highlight=killtimeout) feature to delay the server killing, but I cannot get it done.

Related parts in code are:

```
    override def requires: Plugins = RpmPlugin && JavaServerAppPackaging && BashStartScriptPlugin && SystemVPlugin
//...
    killTimeout in Linux := 153, 
//...
```

I expected that this will add the value somewhere in startup scripts, but I cannot find them in locally generated RPM buildroot.

Am I missing something or am I doing something wrongly?

Thanks!

**Comment by muuki88** [comment]
Have you activated any kind of systemloader plugin? For RPM you normally use the `SystemVPlugin` or `SystemdPlugin`.

**Comment by mr-git** [comment]
Doh.. the github issues do not like to have backticks and first line of code on same line.
```
override def requires: Plugins = RpmPlugin && JavaServerAppPackaging && BashStartScriptPlugin && SystemVPlugin
```
This is the line of enabled plugins

**Comment by mr-git** [comment]
The expected result would be to have `-d <seconds>` parameter added to `killproc` command in init script, but in generated code I see only this:
```
stop() {
    echo -n $"Stopping $prog: "
    killproc -p $PIDFILE $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
}
```

**Comment by mr-git** [comment]
https://github.com/sbt/sbt-native-packager/blob/02519e1a7636489723518c4208f0ee6c03c6a3ad/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-rpm-template#L89 - seems that here it is missing

**Comment by muuki88** [comment]
Thanks for the resarch @mr-git 
The systemv rpm startup script doesn't implement this feature. Only the [systemv debian script](https://github.com/sbt/sbt-native-packager/blob/02519e1a7636489723518c4208f0ee6c03c6a3ad/src/main/resources/com/typesafe/sbt/packager/archetypes/systemloader/systemv/start-debian-template#L61) does.

Would you like to a open a pull request for this?
