### ISSUE TITLE
Versioned docs

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-native-packager#963]
Apparently the docs for a milestone version got published and as a result the docs for the latest stable version are no longer available. See https://github.com/playframework/playframework/issues/7217

**Comment by muuki88** [comment]
Thanks for the issue @benmccann I answered on the related play issue.
The documentation can still be accessed here: http://sbt-native-packager.readthedocs.io/en/stable/

**Comment by benmccann** [comment]
thanks!!
