### ISSUE TITLE
Forbidden access on bintray

### ISSUE THREAD

**Issue by max5599** [sbt/sbt-native-packager#966]
It seems that all access on bintray are forbidden.
For example: [https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.2.0-M9/ivys/ivy.xml](https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.10/sbt_0.13/1.2.0-M9/ivys/ivy.xml)

**Comment by ymeymann** [comment]
Happened to me too, but I think the problem just went away.

**Comment by NeQuissimus** [comment]
https://twitter.com/scala_sbt/status/854087720511123457 It was an issue with the SBT bintray.
