### ISSUE TITLE
Systemd packaging doesn't support multiple `EnvironmentFile` options

### ISSUE THREAD

**Issue by 412b** [sbt/sbt-native-packager#968]
## Expected behaviour

Multiple files/options to be sourced can be provided
`man systemd.exec`: "This option may be specified more than once in which case all specified files are read."

## Actual behaviour

Only single file/option can be provided

## Information

- sbt-native-packager 1.2.0-M8
- sbt 0.13.15
- Ubuntu 17.04, systemd, deb
- Target system is Ubuntu 16.04

currently `EnvironmentFile` is bounded to `bashScriptEnvConfigLocation`, but for example in my case I also want to source `/etc/environment` and it can be achieved only by overriding a template, which is not the best way, IMHO.

**Comment by muuki88** [comment]
Thanks for your feature request @412b 

The `bashScriptEnvConfigLocation` is just a string. So you could concat the files as you like. This may not be a very nice solution, but it works.

We could also implement this feature by adding a new setting in the [SystemLoaderKeys](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/archetypes/systemloader/SystemloaderKeys.scala). This would also require

- decouple this setting from the `bashScriptEnvConfigLocation`
- make a clear distinction when to use the `bashScriptEnvConfigLocation` or the env files
- Implement this properly for all the systemloaders (systemv, upstart, systemd)

**Comment by 412b** [comment]
@muuki88 actually I had in mind one more option: make systemd specific setting (as upstart and systemv doesn't have such or alike feature) and append `bashScriptEnvConfigLocation` as last entry to override vars set in sourced files, so that custom script is there as well as others.
though it's not a generic way across systemloaders, having setting with sequence of files/strings/urls for known-to-not-support systemloaders is also not transparent.
WDYT?

**Comment by muuki88** [comment]
This is a reasonable approach if the bashScriptEnvConfigLocation is only used in systemloaders.  I hadn't had the time to check that, but if this is the case , I'm happy to discuss this in depth on a pull request if you have the time 😊

**Comment by muuki88** [comment]
I used the wrong close 🥲
