### ISSUE TITLE
Support -SNAPSHOT versions when generating RPMs by default

### ISSUE THREAD

**Issue by keirlawson** [sbt/sbt-native-packager#971]
## Expected behaviour

Running `rpm:packageBin` with a version of 1.0.0-SNAPSHOT produces an rpm with name myapp-1.0.0-SNAPSHOT.rpm

## Actual behaviour

Running `rpm:packageBin` with a version of 1.0.0-SNAPSHOT produces a stack trace as hyphens are not supported in RPM versions

## Information

Using version 1.1.5 with SBT 0.13.5.2 on Fedora.

It is possible to work round this by manually setting `version in Rpm` and `rpmRelease`, however it would be nice if the default behaviour was to do this automatically, as the Maven RPM plugin does.

**Comment by muuki88** [comment]
Thanks for your feature request @keirlawson .

If you have time and motivation to add this feature, I'm happy to give you some guidance on this. It should be pretty straightforward.

**Comment by keirlawson** [comment]
Yep, should be able to carve out some time next week, pointers appreciated!

**Comment by muuki88** [comment]
Awesome :)

As you pointed out the `version in Rpm` is the one we should validate / transform. I guess you could write a simple method replacing the invalid characters in `version in Rpm`.

The responsbile line is here: https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/rpm/RpmPlugin.scala#L108

**Comment by keirlawson** [comment]
Have submitted a PR for master, should I also create one for the stable branch (1.1.x?) or is a stable release of 1.2.0 imminent?

**Comment by muuki88** [comment]
I'll plan to release the 1.2.0 this week 😊
Nevertheless thanks for asking 😃
