### ISSUE TITLE
An equivalent to --no-cache

### ISSUE THREAD

**Issue by LeoAref** [sbt/sbt-native-packager#973]
I'm wondering how we can achieve the same behaviour of using `--no-cache` option, like:

```
docker build --no-cache -t my-awesome-app .
```

Currently, each time I run `sbt docker:publishLocal`, it builds on top of the latest built image

**Comment by muuki88** [comment]
Thanks for your question. I guess you are looking for this setting: `dockerBuildOptions`. You can extend this with the options you like.

```scala
dockerBuildOptions += "--no-cache"
```

See the documentation: http://sbt-native-packager.readthedocs.io/en/latest/formats/docker.html#publishing-settings
