### ISSUE TITLE
docker:publish should skip non-Docker projects

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-native-packager#974]
cheating a bit, this short test project for this standardisation plugin (the vast majority of which can be ignored)

https://github.com/cakesolutions/sbt-cake/blob/master/src/sbt-test/sbt-cake/simple/build.sbt

defines 3 projects, only two of which enable the `DockerPlugin`. If I type `sbt docker:publishLocal` it bails when it hits the `logging` project. But since the plugin hasn't been enabled I would have expected it to just skip this project, much as `it:test` only runs for projects with integration tests.

**Comment by fommil** [comment]
ok, somebody added a `dockerRepository` key to every project... which probably confused the plugin. They have been scolded appropriately.

**Comment by muuki88** [comment]
Hm. Setting a key enables the plugin? That wouldn't be very intuitive IMHO

**Comment by fommil** [comment]
aha! The problem seems to be with `docker:publish` not `docker:publishLocal`. It seems to aggregate everything even if the `DockerPlugin` is not enabled.

**Comment by muuki88** [comment]
So when you start your example project and list the plugins in sbt with `sbt plugins` the `DockerPlugin` is not enabled, but still `docker:publish` calls the `docker:publish` task on the logging project?

**Comment by muuki88** [comment]
Ahhh.. I have a guess. The `inConfig` contruct not only  sets tasks in the actual configuration scope you supply, but even more.

I guess [these lines](https://github.com/sbt/sbt-native-packager/blob/2c3946a235ee35b8f19e9a985a6ea3fc1ae362b0/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L126-L132) are responsible that the `publish` task also executes some docker stuff. Still I wonder why `publishLocal` works?

What does `inspect logging/docker:publish` return?

So, the quick fix is to override the `publish` task in the `logging` project.

**Comment by Qthunder** [comment]
Why was this closed? Still seems to be an issue

**Comment by muuki88** [comment]
I closed this as there wasn't any activity for a long time. Feel free to open a pull request if this is an issue for you :smiley: If you need any guidance aside from the comments above, don't hesitate to ask.

**Comment by muuki88** [comment]
From  @nigredo-tori 

The issue here is that `Docker/publish` falls through to `Compile/publish` even if `DockerPlugin` is not enabled.

 `DockerPlugin` is not enabled. This has to do with how Docker configuration is defined.

As a quick workaround, you can add a plugin like this:

```scala
object DockerForwardPlugin extends AutoPlugin {
  override requires = DockerPlugin
  override trigger = allRequirements

  object autoImport {
    val forwardedDockerPublish = taskKey[Unit]("Docker/publish for projects with DockerPlugin")
  }
  import autoImport._

  val projectSettings = Seq(
    forwardedDockerPublish := (Docker / publish).value
  )
}
```
, and use `forwardedDockerPublish` instead. forwardedDockerPublish will only be defined for projects with DockerPlugin.
