### ISSUE TITLE
Documentation incorrect -- Docker v1.10 or higher required

### ISSUE THREAD

**Issue by apeschel** [sbt/sbt-native-packager#981]
The documentation for the Docker packager states that Docker v1.3 or higher is required, as seen here:

https://github.com/sbt/sbt-native-packager/blob/2c3946a235ee35b8f19e9a985a6ea3fc1ae362b0/src/sphinx/formats/docker.rst

However, the packager takes advantage of features that were only added in Docker v1.10. The packager uses a docker build command of the form `docker build -t [version] -t [latest] .`, which lists multiple tags:

https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L92-L97

However, support for multiple tags with the build command was only added in Docker v1.10:

https://github.com/moby/moby/pull/15780

I'm not sure if the preference would be to modify the code to support Docker v1.3 as stated, or to update the documentation to require v1.10.

**Comment by muuki88** [comment]
Thanks @apeschel for recognizing. We should update the documentation. Would you like to make a pull request?
