### ISSUE TITLE
Packaging deb package with 1.2.0-M9 doesn't generate `conffiles` file

### ISSUE THREAD

**Issue by sshobotov** [sbt/sbt-native-packager#984]
## Expected behaviour

`sbt Debian:package-bin` generates DEBIAN/conffiles file

## Actual behaviour

`sbt Debian:package-bin` doen't generate DEBIAN/conffiles file

## Information

- sbt-native-packager version 1.2.0-M9
- sbt version 0.13.15
- build system MacOS
- building deb package
- Debian 'dpkg' package management program version 1.18.23 (darwin-amd64)
- target system Ubuntu 14.04

## Hint

If you call via task `debianConffilesFile.value` directly file will be generated. It seems we should put same call for debianConffilesFile as https://github.com/sbt/sbt-native-packager/blob/3b1adc481917913bbe5423670876b010d2823e0c/src/main/scala/com/typesafe/sbt/packager/debian/DebianPlugin.scala#L194.

**Comment by muuki88** [comment]
Thanks @sshobotov for your bug report. I think this got lost during the refactoring to the stage task.

Ideally we would refactor the stage task like this

```scala
stage := {
  // ... implementation
},
stage := (stage dependsOn debianConffiles).value,
stage := (stage dependsOn debianChangelog).value,
stage := (stage dependsOn debianConffilesFile).value
```

Would you like to make a pull request for this? A regression test would also be nice for this :)
