### ISSUE TITLE
You probably access the destination server through a proxy server that is not well configured.

### ISSUE THREAD

**Issue by ronimokdom** [sbt/sbt-native-packager#988]
I am a beginer for play framework. Please help me.
I am facing the following error while I wanted to take steps as giving command "./activator"
______________________________________________________________________________

You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.

:: problems summary ::
:::: WARNINGS
	Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/releases/org/scala-sbt/main/0.13.11/main-0.13.11.pom

	Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/releases/org/scala-sbt/main/0.13.11/main-0.13.11.jar

	Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.11/ivys/ivy.xml

		module not found: org.scala-sbt#main;0.13.11

	==== local: tried

	  /home/roni/.ivy2/local/org.scala-sbt/main/0.13.11/ivys/ivy.xml

	  -- artifact org.scala-sbt#main;0.13.11!main.jar:

	  /home/roni/.ivy2/local/org.scala-sbt/main/0.13.11/jars/main.jar

	==== activator-launcher-local: tried

	  file:/home/roni/play2project/project1/repository/org.scala-sbt/main/0.13.11/ivys/ivy.xml

	==== activator-local: tried

	  file:/home/roni/activator-dist-1.3.6/repository/org.scala-sbt/main/0.13.11/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/main/0.13.11/main-0.13.11.pom

	  -- artifact org.scala-sbt#main;0.13.11!main.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/main/0.13.11/main-0.13.11.jar

	==== typesafe-releases: tried

	  http://repo.typesafe.com/typesafe/releases/org/scala-sbt/main/0.13.11/main-0.13.11.pom

	  -- artifact org.scala-sbt#main;0.13.11!main.jar:

	  http://repo.typesafe.com/typesafe/releases/org/scala-sbt/main/0.13.11/main-0.13.11.jar

	==== typesafe-ivy-releasez: tried

	  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.11/ivys/ivy.xml

	Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/releases/org/scala-sbt/compiler-interface/0.13.11/compiler-interface-0.13.11.pom

	Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/releases/org/scala-sbt/compiler-interface/0.13.11/compiler-interface-0.13.11.jar

	Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.11/ivys/ivy.xml

		module not found: org.scala-sbt#compiler-interface;0.13.11

	==== local: tried

	  /home/roni/.ivy2/local/org.scala-sbt/compiler-interface/0.13.11/ivys/ivy.xml

	  -- artifact org.scala-sbt#compiler-interface;0.13.11!compiler-interface.jar:

	  /home/roni/.ivy2/local/org.scala-sbt/compiler-interface/0.13.11/jars/compiler-interface.jar

	==== activator-launcher-local: tried

	  file:/home/roni/play2project/project1/repository/org.scala-sbt/compiler-interface/0.13.11/ivys/ivy.xml

	==== activator-local: tried

	  file:/home/roni/activator-dist-1.3.6/repository/org.scala-sbt/compiler-interface/0.13.11/ivys/ivy.xml

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/0.13.11/compiler-interface-0.13.11.pom

	  -- artifact org.scala-sbt#compiler-interface;0.13.11!compiler-interface.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/0.13.11/compiler-interface-0.13.11.jar

	==== typesafe-releases: tried

	  http://repo.typesafe.com/typesafe/releases/org/scala-sbt/compiler-interface/0.13.11/compiler-interface-0.13.11.pom

	  -- artifact org.scala-sbt#compiler-interface;0.13.11!compiler-interface.jar:

	  http://repo.typesafe.com/typesafe/releases/org/scala-sbt/compiler-interface/0.13.11/compiler-interface-0.13.11.jar

	==== typesafe-ivy-releasez: tried

	  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.11/ivys/ivy.xml

	Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/releases/org/scala-sbt/sbt/0.13.11/sbt-0.13.11.jar

	Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.11/jars/sbt.jar

		[FAILED     ] org.scala-sbt#sbt;0.13.11!sbt.jar:  (0ms)

	==== local: tried

	  /home/roni/.ivy2/local/org.scala-sbt/sbt/0.13.11/jars/sbt.jar

	==== activator-launcher-local: tried

	  file:/home/roni/play2project/project1/repository/org.scala-sbt/sbt/0.13.11/jars/sbt.jar

	==== activator-local: tried

	  file:/home/roni/activator-dist-1.3.6/repository/org.scala-sbt/sbt/0.13.11/jars/sbt.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.11/sbt-0.13.11.jar

	==== typesafe-releases: tried

	  http://repo.typesafe.com/typesafe/releases/org/scala-sbt/sbt/0.13.11/sbt-0.13.11.jar

	==== typesafe-ivy-releasez: tried

	  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.11/jars/sbt.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#main;0.13.11: not found

		:: org.scala-sbt#compiler-interface;0.13.11: not found

		::::::::::::::::::::::::::::::::::::::::::::::

		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;0.13.11!sbt.jar

		::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#main;0.13.11: not found
unresolved dependency: org.scala-sbt#compiler-interface;0.13.11: not found
download failed: org.scala-sbt#sbt;0.13.11!sbt.jar
Error during sbt execution: Error retrieving required libraries
  (see /home/roni/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.11

**Comment by muuki88** [comment]
Hi @ronimokdom 

This is not the correct project for your question. Either go to the sbt project or the playframework. Thanks for your understanding :)

As a quick hint: These types of questions are more suitable for Stackoverflow or a gitter channel, as they represent a usage question, not an actual bug or feature request :)

cheers,
Muki
